### ISSUE TITLE
发现一个小小的bug

### ISSUE THREAD

**Issue by cyantedyu** [tumashu/pyim#115]
刚开始上手使用，试着输入 ”李智恩“ （lizhien）
发现选择了 第一个li过后，后面是空白，但 zhi和en 中间加个分隔符后就ok了～
不过总的来说还是很好用！谢谢开发者！

**Comment by tumashu** [comment]
哈哈，这个小小的bug其实是个大坑:-)

**Comment by tumashu** [comment]
今天调整了以下 pinyin split 的代码，发现这个问题好像解决了。
