### ISSUE TITLE
非拼音、五笔输入方案

### ISSUE THREAD

**Issue by erstern** [tumashu/pyim#166]
希望支持非拼音、五笔的方案。
或者增加自定义方案的功能，方便一些小众方案的输入。
比如山人，这几年才涌现的优秀方案，之前很多输入法都没有收录；郑码，因为版权等原因很多输入法软件也没有收录；就算是五笔也有一些用98版的；还有粤语、吴语等方案，除了 RIME ，也很少有平台支持。
希望可以更方便地修改或加入不同的输入方案，本来想对五笔方案的词库做下修改试试，我用 spacemacs ，提示 dict 文件夹不存在，同样希望 wiki 中加入对 spacemacs (chinese layer) 的支持。
谢谢！

**Comment by tumashu** [comment]
如果输入法类似五笔，支持比较容易，不顾我需要合作维护者，不然添加的功能是累赘，没法测试和改进

**Comment by erstern** [comment]
是这样的，比如我现在用郑码方案，但是版权在中易公司手里，为了避免不必要的麻烦，最好能用户自己修改安装使用，不涉及 pyim 本身。仓颉不存在版权的问题，但是常用的有三代、五代、六代之分，也不易统一。山人开放了小字库的编码，一般的使用应该不存在纠纷。这些和五笔字型都是相似的，如果规定固定的格式，不同的使用者导入汉字对应的编码就可以了，不方便的只是相同编码时的词频问题，跟同音字类似。
比较麻烦的是音码，粤语、吴语、中古音这些，用来表示声母、韵母的字母跟汉语拼音有出入，可能需要写正则。不过 RIME 上都有相应的方案（schema.yaml），我也可以帮助维护方案。而协助维护 pyim 的话，我可能就没有这个能力了，有很多函数我是看不懂的。

**Comment by tumashu** [comment]
仓颉和山人有可能，但前提是有 emacser 有这个需求，并且乐意维护一个词库。 其他的几种可能性不大了， 音码处理起来特别复杂和麻烦， 全拼和双拼已经让pyim的代码有点凌乱了。。。。

**Comment by tumashu** [comment]
你如果需要添加仓颉或者山人， 就开启一个词库项目， 类似 https://github.com/tumashu/chinese-pyim-wbdict ，等 melpa 接受之后，我就会试着添加对它的支持，我只使用全拼，你说的几个输入法我只是听说过。。。。

**Comment by tumashu** [comment]
cangjie 已经支持.

**Comment by erstern** [comment]
还有一点小问题，
常见的、用户比较多的被称为「倉頡輸入法」的方案，分为三代、五代和六代（六代或称蒼頡檢字法），这几种的规则和码表都略有不同。我感觉现在这个仓颉方案还是注明是五代更好一点吧。

**Comment by tumashu** [comment]
如果它们的最长码都是5, 就可以通用, 如果不是,就需要特殊处理

**Comment by erstern** [comment]
这三者码长都是5码为主，但这个dict文件是给五代用户的。我的意思是 pyim-cangjie5dict.pyim 这个文件不能通用。
三代、五代与六代之间的差别主要在码表，比如「非」：三代是「lmyyy」，五代「lmsy」，检字法是「lsy」。

**Comment by tumashu** [comment]
这个无所谓，只要都是5码就可以， 只不过安装不同的词库罢了， 五代的安装五代的词库，3代的安装3带的词库， 一般不会有人既使用五代的词库，又使用三代的词库吧？

**Comment by tumashu** [comment]
即使同时安装了3代的词库，和五代的词库， 结果就是，你输入一个码，选词框里面同时显示五代的词和三代的词，
