### ISSUE TITLE
Suddenly the input method swtich stops working

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#170]
In the area used to display the input method on the modeline now displays
"column-number"+"m". Restarting emacs fixed this bug. But it happens again after
some use. I am using the lates pyim from melpa. 
![screenshot-01](https://user-images.githubusercontent.com/8192731/28299968-c1b4b1b6-6bae-11e7-8852-94cf0118d799.png)

**Comment by tumashu** [comment]
stop avy-window and test again

**Comment by QiangF** [comment]
不知到什么原因，好像是在中文文档出现乱码后出现的，就是下面这种：

    （3）时间：15

发现默认输入法被修改了，重设后貌似又好了。

    (setq default-input-method "chinese-pyim")

**Comment by QiangF** [comment]
这个问题不时冒出来，有些buffer能输入中文，有些不能，感觉跟ace－window没关系，今天又发现一个新图标：
![img_2017_07_26__11_02_09](https://user-images.githubusercontent.com/8192731/28602880-2c814f96-71f3-11e7-804f-8b426646eccc.png)

**Comment by tumashu** [comment]
你是不是直接用的README 里面的配置？ 如果是， 那么反应就是正常的

**Comment by tumashu** [comment]
```
  ;; 设置 pyim 探针设置，这是 pyim 高级功能设置，可以实现 *无痛* 中英文切换 :-)
  ;; 我自己使用的中英文动态切换规则是：
  ;; 1. 光标只有在注释里面时，才可以输入中文。
  ;; 2. 光标前是汉字字符时，才能输入中文。
  ;; 3. 使用 M-j 快捷键，强制将光标前的拼音字符串转换为中文。
```

**Comment by QiangF** [comment]
确实，第二个截图是探针设置的结果，第一个我还不是很确定，一顿重启后又正常了，今天
就打扰到这里了。谢谢！
