### ISSUE TITLE
在多个emacs中使用pyim

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#171]
我用EXWM做窗口管理，在EXWM中再开一个emacs窗口（有时候需要sudo编辑比较方便）,
切换到pyim，无法输入中文，原来的“灵通”变成“m”。

**Comment by tumashu** [comment]
不应该呀

**Comment by tumashu** [comment]
你禁用 exim 看看什么情况

**Comment by tumashu** [comment]
最近 pyim 有较大的变化，是不是你的设置过期了？ 贴出来看看

**Comment by QiangF** [comment]
I have updated pyim, but I can't type chinese at all now. Here is my setting:

    (use-package pyim
    :ensure t
    :bind
        (("C-\\" . toggle-input-method)
        ("C-c a". my-create-word-from-selection)
        ("M-f" . pyim-forward-word)
        ("M-b" . pyim-backward-word))
    :init
        (bind-key "C-\\" #'toggle-input-method) 
        (require 'pyim)
    :config
        (use-package pyim-basedict
        :ensure t
        :config (pyim-basedict-enable))

        (setq pyim-dicts
            '((:name "user"
                    :file "~/Nutstore/dotfiles/pyim/user.pyim"
                    :coding utf-8-unix
                    :dict-type pinyin-dict)
            (:name "sogou"
                    :file "~/.dotfiles/.emacs.d/extra/pyim-sogou.gz"
                    :coding utf-8-unix
                    :dict-type pinyin-dict)))

        (setq pyim-use-tooltip 'nil
            pyim-page-tooltip 'nil
            pyim-default-pinyin-scheme 'quanpin
            pyim-page-length 5
            pyim-company-max-length 6
            default-input-method "pyim")

        (setq-default pyim-english-input-switch-functions
                    '(pyim-probe-program-mode
                        pyim-probe-isearch-mode
                        pyim-probe-org-structure-template))

        (setq pyim-isearch-enable-pinyin-search t)

        (add-hook 'emacs-startup-hook
                #'(lambda () (pyim-restart-1 t)))

        (defun read-lines (file-path)
        "Return a list of lines of a file at filePath."
        (with-temp-buffer
            (insert-file-contents file-path)
            (split-string (buffer-string) "\n" t)))
        (defvar user-dict-path "~/Nutstore/dotfiles/pyim/user.pyim")
        (defvar user-dict (read-lines user-dict-path))

        (defun convert-word-list-to-pyim (file-path)
        (interactive)
        (with-temp-buffer
            (let ((word-list (read-lines file-path)))
            (dotimes (i (length word-list))
                (insert (concat (pyim-hanzi2pinyin (elt word-list i) nil "-" nil nil t) " " (elt word-list i) "\n")))
            (write-file (concat file-path ".pyim")))))

        (defun my-create-word-from-selection ()
        "Add the selected text as a Chinese word into the user dictionary."
        (interactive)
        (when (region-active-p)
            (let* ((string (buffer-substring-no-properties (region-beginning) (region-end)))
                (string-with-pinyin (concat (pyim-hanzi2pinyin string nil "-" nil nil t) " " string)))
            ( if (not ( member string-with-pinyin user-dict))
                (progn
                (pyim-create-or-rearrange-word string)
                (write-region
                (concat "\n" string-with-pinyin) nil user-dict-path 'append) 
                (message "将词条: %S 插入 user file。" string-with-pinyin))))))

        (defun pyim-export-user-dict ()
        (interactive)
        (with-temp-buffer
        (maphash
        #'(lambda (key value)
            (insert (concat key " " (mapconcat #'identity value " ") "\n")))
        pyim-dcache-icode2word)
        (write-file "~/.emacs.d/pyim/user.pyim"))))

**Comment by QiangF** [comment]
If exim is disabled, can you still make chinese input in an x window?

**Comment by tumashu** [comment]
现在你在 emacs buffer 中能不能使用pyim？

**Comment by tumashu** [comment]
```
    (setq-default pyim-english-input-switch-functions
                '(pyim-probe-program-mode
                    pyim-probe-isearch-mode
                    pyim-probe-org-structure-template))
```
把这个设置取消了，试试

**Comment by tumashu** [comment]
pyim-probe-program-mode 这个探针激活后，只能在comment或者字符串里面输入中文，所以我感觉是这个的问题

**Comment by QiangF** [comment]
如果配置文件只保留pyim，就没有问题，肯定是其他包和pyim有冲突，我一会一个一个添加，看是哪个，然后再来汇报。

**Comment by QiangF** [comment]
没找到罪魁祸首，暂时用这个函数切换输入法：

    (defun my-toggle-input-method ()
    (interactive)
    (if current-input-method (deactivate-input-method)
        (activate-input-method "pyim")))
