### ISSUE TITLE
总是默认英文输入

### ISSUE THREAD

**Issue by xishi00** [tumashu/pyim#172]
我采用的purcell的基本框架，pyim直接采用的是tumashu推荐的配置，大字库，前些日子使用中都是好好的。前天我更新了emacs的packages，pyim输入便不正常了。具体现象为：可以用C-\把输入法切换为灵通，但是输入却是英文；输入英文字母后按M-j可以调出输入法候选词托盘，但是输入后再输入便又成英文了。
下面是我的配置文件：

(require 'pyim)
(require 'pyim-greatdict) ; 拼音词库设置，五笔用户 *不需要* 此行设置

(use-package pyim
  :ensure nil
  :config
  ;; 激活 basedict 拼音词库
  (use-package pyim-greatdict
    :ensure nil
    :config (pyim-greatdict-enable))

  ;; 五笔用户使用 wbdict 词库
  ;; (use-package pyim-wbdict
  ;;   :ensure nil
  ;;   :config (pyim-wbdict-gbk-enable))

  (setq default-input-method "pyim")

  ;; 我使用全拼
  (setq pyim-default-scheme 'quanpin)

  ;; 设置 pyim 探针设置，这是 pyim 高级功能设置，可以实现 *无痛* 中英文切换 :-)
  ;; 我自己使用的中英文动态切换规则是：
  ;; 1. 光标只有在注释里面时，才可以输入中文。
  ;; 2. 光标前是汉字字符时，才能输入中文。
  ;; 3. 使用 M-j 快捷键，强制将光标前的拼音字符串转换为中文。
  (setq-default pyim-english-input-switch-functions
                '(pyim-probe-dynamic-english
                  pyim-probe-isearch-mode
                  pyim-probe-program-mode
                  pyim-probe-org-structure-template))

  (setq-default pyim-punctuation-half-width-functions
                '(pyim-probe-punctuation-line-beginning
                  pyim-probe-punctuation-after-punctuation))

  ;; 开启拼音搜索功能
  (setq pyim-isearch-enable-pinyin-search t)

  ;; 使用 pupup-el 来绘制选词框
  (setq pyim-page-tooltip 'popup)

  ;; 选词框显示5个候选词
  (setq pyim-page-length 5)

  ;; 让 Emacs 启动时自动加载 pyim 词库
  (add-hook 'emacs-startup-hook
            #'(lambda () (pyim-restart-1 t)))
  :bind
  (("M-j" . pyim-convert-code-at-point) ;与 pyim-probe-dynamic-english 配合
   ("C-;" . pyim-delete-word-from-personal-buffer)))

(setq default-input-method "pyim")
(global-set-key (kbd "C-\\") 'toggle-input-method)

(provide 'init-local)

**Comment by lung-zijim** [comment]
是这个";; 设置 pyim 探针设置，这是 pyim 高级功能设置，可以实现 无痛 中英文切换 :-)的问题"吧。
我什么配置都没要。就可以一直保持中文，或者英文，直到你想换。

**Comment by tumashu** [comment]
对头， 你激活了动态中英文切换了

**Comment by xishi00** [comment]
动态切换很方便，我前面就是这么用的，为什么突然不行了？原来启动后总显示 pyim重启已完成，现在总提示 end of  file during parsing.怀疑某个地方出问题了。

**Comment by tumashu** [comment]
配置括号不匹配了

**Comment by xishi00** [comment]
好像pyim-greatdic 源没有了，在list-packages 找不到了

**Comment by tumashu** [comment]
哎，版权问题，被下架了

**Comment by ReimuXMX** [comment]
现在上架Melpa的软件包必须使用GPL v3或者与之兼容的协议……否则就被下架……

**Comment by ReimuXMX** [comment]
现在上架Melpa的软件包必须使用GPL v3或者与之兼容的协议……否则就被下架……

**Comment by tumashu** [comment]
这个issue先关了
