### ISSUE TITLE
Snapshot 中两个png文件名不对

### ISSUE THREAD

**Issue by Jiffies-Duke** [tumashu/pyim#173]
Cygwin 和 Windows 的图互换了，文件名和内容不一致。

**Comment by tumashu** [comment]
没有吧? 哪两个文件?

**Comment by Jiffies-Duke** [comment]
在snapshots中，文件名为：pyim-winxp-term.png的，图片实际上是Cygwin的。而图片名字为pyim-window-Cygwin.png的，图片内容是Windows下的Emacs-w32 。

**Comment by tumashu** [comment]
term 只是说 emacs 在 term 下运行,   cygwin 那个好像也没问题, 因为那个确实是cygwin下安装的 emacs :-)

**Comment by Jiffies-Duke** [comment]
是我理解错了，抱歉 :P
