### ISSUE TITLE
如何输入中文标点符号？

### ISSUE THREAD

**Issue by whatacold** [tumashu/pyim#174]
比如：`，。、？`等。

我参考readme尝试了`M-x pyim-punctuation-toggle`，输入.得到的还是英文点号`.`；
搜了下issue，没有找到相关的问题。

求指点，谢谢~

**Comment by tumashu** [comment]
你有没有激活探针？

**Comment by whatacold** [comment]
应该没有，我`grep -nr probe ~/.emacs.d`没有结果。（.emacs.d fork Bin Chen的，还不太熟悉）

**Comment by whatacold** [comment]
不好意思，是设置的问题，陈斌在[配置](https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-chinese-pyim.el#L68)中设置了始终使用半角符号：
>     ;; use western punctuation (ban jiao fu hao)
>     (setq pyim-punctuation-dict nil)

去掉这个配置就可以输入中文符号了。

另外，这个变量没有文档，能否麻烦加一下？
谢谢~

**Comment by tumashu** [comment]
我靠，这个变量还能这么用，太粗暴了。。。

**Comment by tumashu** [comment]
也许应该添加一个新命令，让用户可以设置 标点输入模式 。。。。

**Comment by tumashu** [comment]
切换全角标点与半角标点

    第一种方法：使用命令 `pyim-punctuation-toggle'，全局切换。 这个命令主要用来设置变量： `pyim-punctuation-translate-p', 用户也可以 手动设置这个变量， 比如：

    (setq pyim-punctuation-translate-p '(yes no auto))   ;使用全角标点。
    (setq pyim-punctuation-translate-p '(no yes auto))   ;使用半角标点。
    (setq pyim-punctuation-translate-p '(auto yes no))   ;中文使用全角标点，英文使用半角标点。

    第二种方法：使用命令 `pyim-punctuation-translate-at-point' 只切换光 标处标点的样式。

    第三种方法：设置变量 `pyim-translate-trigger-char' ，输入变量设定的 字符会切换光标处标点的样式。

**Comment by tumashu** [comment]
检查这个变量
```
(defcustom pyim-punctuation-dict
  '(("'" "‘" "’")
    ("\"" "“" "”")
    ("_" "―")
    ("^" "…")
    ("]" "】")
    ("[" "【")
    ("@" "◎")
    ("?" "？")
    (">" "》")
    ("=" "＝")
    ("<" "《")
    (";" "；")
    (":" "：")
    ("/" "、")
    ("." "。")
    ("-" "－")
    ("," "，")
    ("+" "＋")
    ("*" "×")
    (")" "）")
    ("(" "（")
    ("&" "※")
    ("%" "％")
    ("$" "￥")
    ("#" "＃")
    ("!" "！")
    ("`" "・")
    ("~" "～")
    ("}" "』")
    ("|" "÷")
    ("{" "『"))
  "标点符号表."
  :group 'pyim
:type 'list)
```

**Comment by zhixing2017** [comment]
最上面的两个是什么意思啊？
