### ISSUE TITLE
Chinese-pyim 改名成 pyim 之后会导致 spacemacs 报找不到包

### ISSUE THREAD

**Issue by scarletsky** [tumashu/pyim#176]
![image](https://user-images.githubusercontent.com/2386165/30050170-03639e20-9250-11e7-90bb-bcbfc673eca9.png)

其实这个更像是 spacemacs 的 issue，但我不会改...  :rofl: 
所以请问下应该怎么修改才能正常使用 ?

**Comment by et2010** [comment]
这个已经在 spacemacs 的 develop branch 修复了，你可以切换到 develop branch

**Comment by scarletsky** [comment]
@et2010 哦哦！！感谢告知！
