### ISSUE TITLE
org-mode下，候选词的显示会受影响

### ISSUE THREAD

**Issue by zhixing2017** [tumashu/pyim#178]
如图，候选词的显示受到影响，有的时候的排版乱的很。

![snipaste_2017-09-15_10-19-55](https://user-images.githubusercontent.com/26316963/30463700-d3a13258-99ff-11e7-96f3-db48e4fcd394.png)

![snipaste_2017-09-15_10-24-41](https://user-images.githubusercontent.com/26316963/30463740-1cefb1c8-9a00-11e7-8933-955e9cfa5bfb.png)

**Comment by et2010** [comment]
你试一下用 pos-tip
```
(setq pyim-page-tooltip 'pos-tip)
```

**Comment by tumashu** [comment]
这个是正常反应， overlay 冲突， 你可选择 pos-tip， 也可以使用单行显示模式： (setq pyim-page-style 'one-line)

**Comment by et2010** [comment]
BTW, pos-tip 显示更新的时候闪烁的问题解决了吗？

**Comment by tumashu** [comment]
没有，估计emacs 没有10年8年解决不了这个事情

**Comment by zhixing2017** [comment]
使用了pos-tip之后，候选词的个数只会出现一个，不知是什么原因

词数是默认的，没有更改啊
```
pyim-page-length is a variable defined in ‘pyim.el’.
Its value is 5
```

**Comment by tumashu** [comment]
你可能使用的是竖排，在pos-tip上，竖排是没有测试过的， 因为这个backend太慢了，几乎没法用，所以我也懒得折腾了。

**Comment by zhixing2017** [comment]
对啊，竖排显示有问题，横排显示没有问题

**Comment by tumashu** [comment]
因为pos-tip那个框太小，所以后面的就显示不出来了。。。。

**Comment by tumashu** [comment]
BTW： pyim.el, 836行，vertical拼写有误

welcome pull request  :-)

**Comment by zhixing2017** [comment]
哦，在我这里，pos-tip的界面是白色的，与我的白色背景不大配置，不好看。

我喜欢用vertical，还是用回popup吧

**Comment by tumashu** [comment]
你那 pos-tip 不闪烁吗？ 如果开启gtk支持， pos-tip在linux 下速度是最快的

**Comment by zhixing2017** [comment]
闪烁，还是用popup方便点吧。

pop-tip在linux下不闪烁吗？效果很好？

**Comment by lung-zijim** [comment]
@tumashu 请问怎么开启gtk支持？

**Comment by zhixing2017** [comment]
org-mode下开启缩进后，行首输入的时候，候选框是不缩进的，不大好看，这个容易hack吗？

![snipaste_2017-09-17_10-51-15](https://user-images.githubusercontent.com/26316963/30517569-967076b2-9b96-11e7-969a-ef65ae337fb0.png)

**Comment by tumashu** [comment]
(setq pyim-page-tooltip 'pos-tip)
     (setq x-gtk-use-system-tooltips t)

我测试了一下, 开启gtk后, pos-tip可以正常使用

**Comment by tumashu** [comment]
你说的两个问题我已经修复, 不过如果不开启gtk支持,你还能坚持使用pos-tip, 你就是神人....

**Comment by tumashu** [comment]
如果你开启了gtk模式， pos-tip 在linux下是最好使的，速度最快， 如果不开启，那速度就是渣

**Comment by et2010** [comment]
我有一个思路不知道能不能修复闪烁。比如你把 message 放到 post-command-hook 的时候，每次输入都会在 minibuffer 出现 message，因此会一直闪烁。但是 eldoc 没有这个问题，eldoc 也是通过 post-command-hook ，但是不会闪烁。也许能有点启发？

**Comment by tumashu** [comment]
我感觉pos-tip的闪烁，是因为频繁的生成tooltip窗口和删除窗口造成的，而生成tooltip窗口的速度比较慢，所以就出现了闪烁，这个需要仔细研究研究。。。。。也许有戏
