### ISSUE TITLE
出现 "error in process sentinel: End of file during parsing: .../emacs/25.3/lisp/loadup.el" 的错误

### ISSUE THREAD

**Issue by bokuno** [tumashu/pyim#179]
Termux里面的emacs 25.3在加载、使用pyim时出现 "error in process sentinel: End of file during parsing: /data/data/com.termux/files/usr/share/emacs/25.3/lisp/loadup.el" 的错误，求教怎么回事，谢谢。

**Comment by tumashu** [comment]
这个错误消息太少了, 直观的感觉像你的配置里面有括号不匹配的问题.

**Comment by bokuno** [comment]
就这一个包有这个问题。现在用的是 chinese-wbim 这个输入法，正常。更多细节貌似也没有了。

**Comment by tumashu** [comment]
你怎么安装pyim的，是不是没有安装 async? 删除~/.emacs.d/pyim试试

**Comment by bokuno** [comment]
直接通过 melpa-stable 安装的。安装完成，调出输入法时，会出现上面的错误提示，但是默认的拼音输入法可以打出汉字。另外安装了 py-wbdict 并设置了 (setq pyim-default-scheme 'wubi) 后，发现五笔打不出汉字。也许你需要找一台 android 5的手机亲自安装一下termux才能发现这问题的原因吧。

**Comment by tumashu** [comment]
我感觉这个是emacs-async的问题，没有仔细研究过

**Comment by tumashu** [comment]
我测试了一下,  发现 emacs-async 根本无法在 termux 的emacs 下运行, 具体原因未知,  pyim 依赖这个库异步的加载词库,所以这个包不能工作, pyim就残废了.

**Comment by tumashu** [comment]
https://github.com/jwiegley/emacs-async/issues/90

**Comment by tumashu** [comment]
我暂时添加了一个临时解决的方式, 你可以试一试:

1. 明天或者后天, 更新 pyim
2. 从其他机子上拷贝 ~/.emacs.d/pyim 目录到 Termux 
3. (setq pyim-dcache-auto-update nil)

这样 pyim 就可以正常运行了, 虽然有一点功能缺失,但影响不大, 等 emacs-async 的问题解决后, 
就回到正常设置就可以了.

**Comment by bokuno** [comment]
按照你的说法，目前的确可以在termux-emacs里面正常使用了……

**Comment by tumashu** [comment]
emacs-async 我调试了2天，也没有找到原因， 去提交issue也没有什么实质性的反馈， 等emacs26吧，到时候直接用 emacs thread 功能了， 也就没这个问题了。

**Comment by bokuno** [comment]
emacs-async好像更新了，然而问题依旧没解决。另外我今天发现了个通过company-mode 来实现五笔输入的包，用了一下，发现挺好用的，然而并不在melpa 里面。url: https://github.com/Yevgnen/company-wubi

**Comment by tumashu** [comment]
你是不是用 termux？ 我感觉是 termux 的 emacs 的问题。。。。

**Comment by tumashu** [comment]
我也用termux，这个问题调试了很久，最后我感觉不像 async 的锅，而是 termux 中 emacs 的问题，但具体却不知道什么原因。

**Comment by bokuno** [comment]
我觉得也是Termux 的打包问题，毕竟安卓平台和普通PC平台有差别，有些东西在安卓上实现不了。（举个例子，play-sound-internal 这个函数是没有的，要自己写一个）

**Comment by tumashu** [comment]
Termux Termux 上的 emacs 已经升级到 26.1, 我更新了 pyim, 让它在 emacs26 上
使用 thread 功能更新 dcache, 这个问题估计就解决了

**Comment by bokuno** [comment]
Ok...

**Comment by sherylynn** [comment]
现在用termux 里的emacs 29.3 还是有这个问题，并且会导致 base dict词库等没法用
