### ISSUE TITLE
五笔输入模式无法添加新词和动态调整排序

### ISSUE THREAD

**Issue by HengGeZai** [tumashu/pyim#181]
五笔输入模式无法添加新词和动态调整排序，能不能添加这两个功能？另外，我发现即使是用五笔输入模式，pyim还是会按拼音输入模式生成缓存文件。

**Comment by tumashu** [comment]
```
五笔输入模式无法添加新词和动态调整排序
```
这个功能我没有打算添加，因为添加后， pyim 代码就太复杂了，很难维护， 由于五笔词库的稳定性，你完全可以手动维护一个五笔词库

**Comment by tumashu** [comment]
```
我发现即使是用五笔输入模式，pyim还是会按拼音输入模式生成缓存文件。
```
对的， 唯一的区别就是 五笔词库的编码都必须以 "." 开头

**Comment by HengGeZai** [comment]
嗯嗯，好的，谢谢。
