### ISSUE TITLE
(toggle-input-method)启动出现错误： (error "Odd number of elements in hash table data")

### ISSUE THREAD

**Issue by damon-kwok** [tumashu/pyim#182]
`Debugger entered--Lisp error: (error "Odd number of elements in hash table data")
  read(#<buffer  *temp*>)
  pyim-dcache-get-value-from-file("~/.emacs.d/pyim/dcache/pyim-dcache-icode2word")
  pyim-dcache-set-variable(pyim-dcache-icode2word)
  pyim-dcache-init-variables()
  pyim-start("pyim")
  apply(pyim-start "pyim" nil)
  activate-input-method("pyim")
  toggle-input-method(nil 1)
  funcall-interactively(toggle-input-method nil 1)
  call-interactively(toggle-input-method nil nil)
  command-execute(toggle-input-method)`

**Comment by damon-kwok** [comment]
删除~/.emacs.d/pyim/dcache后可以解决

**Comment by tumashu** [comment]
估计是 dcache 不知什么原因破坏了

**Comment by damon-kwok** [comment]
建议再出现类似错误时，自动删除出错的cache文件，作为默认的异常处理方式

**Comment by tumashu** [comment]
用户的个人词库也在 dcache 目录里面， 如果我随意删除 dcache， 那是会招来仇恨的，况且 dcache 也是
简单的文本文件，熟悉 elisp 的同学甚至可以手动修复 dcache。。。。

**Comment by QiangF** [comment]
我把保存到个人词库文件了，下面这个可以自动删除错误文件

    (defun pyim-dcache-get-value-from-file (file)
    "读取保存到 FILE 里面的 value."
    (when (file-exists-p file)
        (condition-case nil
            (with-temp-buffer
            (insert-file-contents file)
            (eval (read (current-buffer))))
        (error nil))))

**Comment by tumashu** [comment]
今天我这边也遇到了类似的cache损坏的情况。。。。。 汗！

**Comment by damon-kwok** [comment]
有解决思路了吗？

**Comment by tumashu** [comment]
现在是转储有错误的dcache

**Comment by Leyls** [comment]
删除dcache目录后重启emacs也是一样的报错，删除之前dcache内容如下：
![image](https://user-images.githubusercontent.com/45854583/155832066-3dcfdb0e-6b14-455e-a73b-fea7d3f90822.png)
像这样的话，我还可以怎么debug呢？
