### ISSUE TITLE
TAB启用后，输入标点是半角的好点？

### ISSUE THREAD

**Issue by whatacold** [tumashu/pyim#183]
你好：
记得Windows上的输入法，按TAB后输入的标点是半角的，与输入的英文大写字母的“风格”一致，个人感觉这样体验好点，目前pyim的行为不是这样的。

我使用`emacs -Q`，然后从melpa全新安装pyim进行测试：启用TAB后，输入的标点还是全角的。

所以我觉得在这种情况下，应该改为默认输入半角标点，如果觉得没有必要请忽略。

**Comment by tumashu** [comment]
tab 对于 emacs 来说太重要了，随便改它会被其他程序员打死的。。。。

**Comment by whatacold** [comment]
啊……我怎么把Caps Lock说成Tab了:(

针对我的情况，我发现使用你README中的中英切换探针`pyim-english-input-switch-functions`基本能够解决问题，先关闭了:)
