### ISSUE TITLE
我编制了一个“单手笔顺输入法”的码表，希望您能在您正在开发的输入法中加入这个功能。

### ISSUE THREAD

**Issue by YQ-YSY** [tumashu/pyim#184]
我编制了一个“单手笔顺输入法”的码表，希望您能在您正在开发的输入法中加入这个功能。（我不会编程）
其中已经包括了近3万汉字、15万核心词汇、150万扩展词汇，全部都是TXT文本码表（而且都带拼音）。

笔顺的国家标准编码就是数字12345，我设计的六全码和精简码是0～9，
因此，“单手笔顺输入法”使用数字小键盘作为输入工具，不会与您开发中的输入法有冲突，
相反，两个输入法能成为互补关系，大大提高汉字输入效率。
用户不记得您的输入法时，就输入笔顺；用户不记得笔顺时，就输入您的输入法。

“单手笔顺输入法”开源项目网址：
https://github.com/YQ-YSY/stroke-seq_MB
发布在Ubuntu论坛的帖子介绍：
http://forum.ubuntu.org.cn/viewtopic.php?f=35&t=484603

因为笔顺码有个优点，它和拼音一样，每个人在上小学时就已经学会了，不用背字根。
所以，继五笔、拼音之后，笔顺输入也许是汉字输入法的又一个重大的改进机会，
未来甚至可以替代拼音输入法，成为最主流的汉字输入法。

**Comment by tumashu** [comment]
如果你这个输入法重码率不高， 我感觉用emacs 内置的输入框架 quail 实现应该是最简单的， pyim的框架中0-9是用来选词的按键，估计很难作为code使用。

**Comment by tumashu** [comment]
最近重构pyim，看看能不能做一些突破。。。

**Comment by tumashu** [comment]
我从心里佩服你，能花一年的时间来设计优化这套编码。。。。对了，你平时用emacs么？

**Comment by YQ-YSY** [comment]
在刚学Linux的时候，也学习过emacs，但在各种平台上，文字处理软件到处都是，随手拈来就能用，平时当然也就不太使用Emacs。但如果能在Emacs里嵌入这个“单手笔顺输入法”的话，我肯定会经常用它来打字的——因为，我发出过很多请求，都没有人编写这个输入法，而我又不会写程序、又没有钱聘请程序员。
如果您有兴趣，我建议您将此输入法开发成为一个独立的软件，在哪里都可以用，让大家体会到笔顺输入的方便，甚至——改变现代汉字输入以“拼音输入”为主现状，变成以笔顺输入为主，也是有可能的。

**Comment by yefeiyu** [comment]
问一下笔顺输入的速度您能到多少？快的话我也学学。
五笔在高手里面，近年来使用极点的在一些比赛中能达到200字\分钟。普通人的速度到70字就已经非常快\\
了。
我最早学习的五笔，打字有快感产生，手摸键盘会有快感。后来改用郑码，无论怎么练怎么用，都难以产\\
生这样的感觉。后来又回到五笔，这个感觉一直没有找回来。
输入法涉及诸多很微小的细节性的东西。如郑码多了一个增加准确率的次根、次末根的设计，反而拖泥带\\
水影响输入感觉（个人认为）。笔顺输入的话，会不会过于详细一笔一笔的拖慢速度？（我就简单一问哈\\
，希望能推广成功）
关于您问的独立摘出一输入法来说，好像不太可能吧？因为pyim本身是依附emacs存在的。emacs本身几乎\\
是一个计算机系统，单摘它输入法的，应该是类似于从linux移植到windows。不知道看法是否正确。

**Comment by tumashu** [comment]
对这个输入法基本的支持，pyim相对来说容易处理，不过我看了一下说明，好像有许多特殊的规则，看起来很复杂的样子

**Comment by YQ-YSY** [comment]
我勉强做了个“单手笔顺输入法（ibus-table实验版）”，http://forum.ubuntu.org.cn/viewtopic.php?f=35&t=488891 但存在有很多的问题，其中最大的问题是：使用回车键上屏时会多一个回车，也就是字打上之后，会自动换下一行。

该输入法的原理，是基于网上的一种商业的“数字五笔输入法”，我曾使用该输入法多年。“单手笔顺输入法”包含有“笔顺码、六全码、精简码”三种编码，使用熟练的话，用于会议速记都没问题。但可惜，现在只有码表，还没有一个真正能用的输入法软件。

Readme里的各种规则，是经过多次实验、推敲、总结而得出的“最佳”方案，相信能给用户带来方便、快捷的汉字输入体验。

Linux平台下现有的 ibus、fcitx 和 rime 输入法，从网友的评论上看，各有各的优点、也各有各的缺点。这几个输入法的开发者我都联系过了，可惜他们都不感兴趣。

**Comment by tumashu** [comment]
数字五笔输入法 有没有申请相关专利？

**Comment by yefeiyu** [comment]
数字五笔是不是就是银行用的小键盘打字的那种？
单手笔顺，从使用场景上来说，只使用单手？那适配范围很窄啊。要么是手机用？这角度看倒是前景很大，大多数人用手机。况且手机正好符合“单手“，”数字”
但是大多数人懒得学习啊。有拼音，人们不会再去学笔顺。

**Comment by yefeiyu** [comment]
楼主还可以试试“清歌”
https://www.v2ex.com/t/86848

**Comment by yefeiyu** [comment]
https://www.zhihu.com/question/19697270/answer/143321004
```
之前在Windows系统中使用两款五笔输入法：分别是极点五笔和小鸭五笔。更换为Mac系统后尝试过几款五笔输入法，如百度、QQ和清歌等。到目前为止，系统中保留了上述三款输入法，但使用率最高的还是清歌，主要是因为将原来极点的习惯和词库全部带过来了，因为因为理科，用到特殊符号和定制词库的时候较多，清歌在这方面有优势。不喜勿喷，欢迎讨论。

作者：李一博
链接：https://www.zhihu.com/question/19697270/answer/143321004
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

从这段话里看，极点和清歌的词库是一致的。
同时，清歌和极点的词库，都是自由分享的。

上一楼的链接是清歌作者的贴子。

清歌的词库目前直接是txt文本，可以自由添加删除词语。

**Comment by YQ-YSY** [comment]
在我的单手笔顺输入法的Readme第一段，就已经注明了，没有专利侵权的问题，因为“数字五笔”的专利已经过期失效了：
编码原理基于专利权已终止的（CN03159505.7）“一种数字笔画汉字输入方法”，原发明人：马晓光 <232937@QQ.com>

虽然叫做“数字五笔”，但是与传统的“五笔字型输入法”没有任何的关系，它在十几年前刚发明时，也许是想蹭“五笔字型输入法”的热度，来方便宣传而已。

使用小键盘输入汉字有很多好处，一是解放了另一只手，你甚至可以一边打字一边喝水、吃东西、看手机……
二是因为用的是数字小键盘，所以能和拼音、英文输入等用字母键盘的输入法同时使用，不用按ctrl
+Shift键切换。
三是在平板电脑优势明显。使用字母输入的输入法，在平板电脑上需要调用虚拟键盘，一下子就占据了一半的屏幕，让人感觉很不爽。而单手笔顺输入法的虚拟数字小键盘，只占用右下角的位置而已，感觉就好很多。

笔顺输入法不需要学习，因为每个人小学时就学过笔顺。即使是使用可以输入边旁部首“六全码、精简码”，这两种编码也是依据“笔顺”的规律来编制的，所以也不用学，全靠猜都能八九不离十，打字多了自然就记得了。（这些我在Reaadme里都有详细的说明。）

我是Linux爱好者，我不知道“清歌输入法”只否支持LInux系统？

**Comment by yefeiyu** [comment]
清歌目前是mac下输入法
以及开发了ios下app

**Comment by shuxiao9058** [comment]
@YQ-YSY rime不能解决你这个问题吗？

**Comment by YQ-YSY** [comment]
> @YQ-YSY rime不能解决你这个问题吗？

问过rime的开发者了，他说rime里数字键只能用来选字，不能用来输入代码。

**Comment by tumashu** [comment]
@YQ-YSY  我今天试了一下，这个输入法的最基本哦功能，pyim应该可以实现，但其他复杂的功能就很难了

```
(add-to-list
 'pyim-schemes
 '(onehand
   :document "单手笔顺输入法"
   :class xingma
   :first-chars "1234567890."
   :rest-chars "1234567890."
   :code-prefix "!"
   :code-split-length 6
   :prefer-trigger-chars nil))

(setq pyim-default-scheme 'onehand)
(setq pyim-page-select-word-by-number nil)

(define-key pyim-mode-map "." 'pyim-page-select-word)

```

```
!124 彐
!1184 聿
!3396 建
!20662 衋
!45244 䢖
!43071 䀌
!42470 㶳
!126131 𦘒
!10420 畫
!8444 晝
!6625 書
!13766 劃
!13765 鄩
!12216 畵
!20745 彠
!10419 尋
!40883 㝷

```

**Comment by YQ-YSY** [comment]
谢谢！我用的是Ubuntu Linux，应该如何安装试用pyim输入法，以及如何调用这个我自己的字库/词库？

**Comment by tumashu** [comment]
按照那个格式保存文件，然后用pyim-dict-manager添加词库，然后保存重启pyim
