### ISSUE TITLE
display error in ivy buffers

### ISSUE THREAD

**Issue by AmaiKinono** [tumashu/pyim#186]
The tooltip is pushed to the very bottom in ivy buffers.

e.g. swiper:

![screenshot_20180101_144154](https://user-images.githubusercontent.com/28714352/34466043-166c43c8-ef02-11e7-8f4b-b33eb81691e6.png)

![screenshot_20180101_144352](https://user-images.githubusercontent.com/28714352/34466051-33d683d8-ef02-11e7-9202-f1bd71ad0541.png)

counsel-grep:

![screenshot_20180101_144445](https://user-images.githubusercontent.com/28714352/34466054-5213673a-ef02-11e7-9926-e8f85c8e8667.png)

Is it possible for the tooltip to display in the same line with the cursor when in minibuffer？

**Comment by tumashu** [comment]
Added 1868d2dbcd73b072bf63a7dfe7c034068c9c4ebf

**Comment by AmaiKinono** [comment]
Thanks, that's cool.

**Comment by tumashu** [comment]
:-)
