### ISSUE TITLE
How to configure autoload for pyim correctly?

### ISSUE THREAD

**Issue by AmaiKinono** [tumashu/pyim#187]
My configuration:

``` lisp
(use-package pyim
    :bind (("C-\\" . toggle-input-method)
           ("M-f" . pyim-forward-word)
           ("M-b" . pyim-backward-word))
    :init
    (progn
      (setq pyim-use-tooltip t
            ;; ... set some variables...
      )))
```

After starting Emacs, I can't activate pyim. The minibuffer says:

```
activate-input-method: Can't activate input method 'pyim'
```

But as long as I press `M-f` or `M-b`, `C-\` works as well. It seems that `pyim` is not loaded after `C-\`, but after `M-f` and `M-b`.

Now I remove the keybindings in my configuration and it works. But I wonder how to configure autoload for `pyim` correctly?

**Comment by tumashu** [comment]
把配置放到 :config 试一试

**Comment by AmaiKinono** [comment]
Thanks a lot, it do works.

But I want `pyim` to be load after I `toggle-input-method`. I tried `:commands toggle-input-method` and it doesn't work as well. I just wonder why...

**Comment by tumashu** [comment]
maybe toggle-input-method is not pyim's function

**Comment by AmaiKinono** [comment]
So the function in the `:commands` statement should belong to the package itself? I see...

Anyway, do you have any idea how can one configure `pyim` to be load after switching to this input method?

**Comment by tumashu** [comment]
```
Anyway, do you have any idea how can one configure pyim to be load after switching to this input method?
```
seem to no at the moment.

**Comment by boost2017** [comment]
You need cheat emacs to load the package on demand.
```
(use-package pyim
    :ensure t
    :bind 
      ("C-\\" . pyim-toggle-input-method)
    :config
    (defalias 'pyim-toggle-input-method 'toggle-input-method)
    (setq-default default-input-method "pyim")
   ;;  other configuration goes here
)
```
You may encounter situation where `toggle-input-method` can not actually toggle the input method, then you can define `pyim-toggle-input-method` to wrap `toggle-input-method` as below other than `defalias`.
```
    (defun pyim-toggle-input-method (&optional arg interactive)
      "Force toggle input method from/to pyim."
      (interactive "P\np")
      (setq input-method-history nil)
      (setq default-input-method "pyim")
      (call-interactively 'toggle-input-method arg))
```
