### ISSUE TITLE
We should use more reasonable dir path

### ISSUE THREAD

**Issue by kaiwk** [tumashu/pyim#188]
I made a pull request for the [no-littering](https://github.com/emacscollective/no-littering), which is a package to keep Emacs home clean.

~~However, considering this package is not used by common Emacs user, we might change our default directory path to adapt the 'standard'.~~

We might should make some modification for the PR.

See also: https://github.com/emacscollective/no-littering/pull/72#issuecomment-355833314

**Comment by tumashu** [comment]
pyim-directory is useless at moment,
pyim-dcache-directory is used to store  pyim dict cache and personal dict cache.  very important.

**Comment by tumashu** [comment]
try again.

**Comment by tarsius** [comment]
> pyim-directory is useless at moment,

@tumashu You might want to remove it for the time being to avoid confusion.
@kaiwk Please remove the respective line from your `no-littering` pull request.

> try again.

Okay ;-)

Regardless of whether you keep `pyim-directory` you should

1. Define the type of each option.
2. Use `directory` as the type of `pyim-dcache-directory` and use a value that ends with a slash.

**Comment by tumashu** [comment]
I do not familar defcustom, is the below code enough?

```
(defcustom pyim-dcache-directory (locate-user-emacs-file "pyim/dcache/")
  "一个目录，用于保存 pyim 词库对应的 cache 文件."
  :type 'directory
  :group 'pyim)

```

**Comment by tarsius** [comment]
Yes, that's what you should do.

**Comment by tumashu** [comment]
Finished.

**Comment by tarsius** [comment]
Thanks!
