### ISSUE TITLE
the lastest commit breaks child-frame display

### ISSUE THREAD

**Issue by albert748** [tumashu/pyim#189]
Hi, bro:

Looks like the latest commit (maybe yesterday after I've upgrade?) breaks the display of child-frame?

the potision of child-frame not at the right cursor position, few pixels shifted.

take a look?

**Comment by albert748** [comment]
here's evidence:

![screenshot from 2018-01-08 12-01-30](https://user-images.githubusercontent.com/57474/34658653-ba484438-f46b-11e7-9028-313aa12ea93f.png)

**Comment by tumashu** [comment]
this may fixed, just wait melpa update

**Comment by albert748** [comment]
Tested, It's works now.

**Comment by albert748** [comment]
It works on ordinary buffers, but still shifted on org-capture buffer, because it's narrowed?

![screenshot from 2018-01-09 03-19-47](https://user-images.githubusercontent.com/57474/34688149-199fd056-f4ec-11e7-8a44-bf6a347c7fef.png)

**Comment by tumashu** [comment]
Fixed, try again

**Comment by albert748** [comment]
tested && fixed, thanks for your work.
