### ISSUE TITLE
可以根据标点符号前的字符自动切换全半角模式吗

### ISSUE THREAD

**Issue by wpchou** [tumashu/pyim#192]
感觉在中英文混输的时候还是挺常见的需求。

**Comment by tumashu** [comment]
(setq pyim-punctuation-translate-p '(auto yes no))   ;中文使用全角标点，英文使用半角标点。

**Comment by wpchou** [comment]
有没有办法做一个 pyim-probe-punctuation-after-punctuation 一样的探针？

**Comment by tumashu** [comment]
应该可以，不过我没研究过，你可以试试整一个，难度估计也不大

**Comment by wpchou** [comment]
谢谢
