### ISSUE TITLE
希望双拼能加入 自然码 支持

### ISSUE THREAD

**Issue by lvii** [tumashu/pyim#195]
希望双拼输入法能加入 **自然码** 码表，感谢！

**Comment by tumashu** [comment]
你如果需要添加自然码， 就开启并维护一个词库项目， 类似 https://github.com/tumashu/pyim-wbdict ，等 melpa 接受之后，我就会试着添加对它的支持。

注意：如果实现它导致pyim代码复杂度提升很大，我就不会去实现它。

**Comment by lvii** [comment]
@tumashu **自然码** 是 **双拼** 的一个码表。我看 `pyim.el` 有定义 **微软** 、**小鹤** 的双拼码表：

https://github.com/tumashu/pyim/blob/37be07e2e585d1cb5964d7187fca22e863714056/pyim.el#L653

**双拼** 码表也需要重新添加词库么？

**Comment by tumashu** [comment]
如果你只需要自然码双拼的部分的话， 就不需要词库， 如果想双拼+型码的话，只能按五笔的处理模式，是需要词库的。

**Comment by lvii** [comment]
@tumashu 文档有提到说可以自定义，又对 elisp 不太熟悉，文档也没有示例。所以前来提 issue

**自然码** 相对其他码表不需要借助 **标点符号按键** 因此也很适合手机键盘

**Comment by tumashu** [comment]
```
自然码 相对其他码表不需要借助 标点符号按键 因此也很适合手机键盘
```
这个我就不太了解了， 如果用pyim现有的 双拼框架去支持 自然码的话，支持起来比较简单，只是
你无法使用形码来降低选词的频率，你需要提供声母和韵母的对照表

如果按照五笔的框架来支持 自然码的话， 是需要你制作一个词库，将编码和汉字对应出来

**Comment by tumashu** [comment]
```
文档也没有示例
```
文档是给使用者使用的， 开发者相关的信息都在代码注释里

**Comment by tumashu** [comment]
This feature has been added by @realasking
