### ISSUE TITLE
Debugger entered--Lisp error: (void-function posframe-show)

### ISSUE THREAD

**Issue by xshumeng** [tumashu/pyim#198]
DEBUG 的信息
> Debugger entered--Lisp error: (void-function posframe-show)
> posframe-show(" *pyim-tooltip-posframe-buffer*" :string "=> j [1/23]: \n1.将 2.给 3.叫 4.就 5.件 " :position 145 :min-width 35 :background-color "#333333" :foreground-color "#dcdccc")
> pyim-tooltip-show("=> j [1/23]: \n1.将 2.给 3.叫 4.就 5.件 " 145)

EMACS 版本
> GNU Emacs 26.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26)

编译选项
> ./configure --prefix=/application/emacs-26/ --with-pop --with-mailutils --with-modules --with-xwidgets --with-x-toolkit=gtk3

插件配置
> (setq pyim-page-tooltip 'posframe)

**Comment by tumashu** [comment]
手动安装 posframe 包
