### ISSUE TITLE
词库在线更新的支持

### ISSUE THREAD

**Issue by Qquanwei** [tumashu/pyim#200]
我对pyim非常依赖，它是我在emacs环境中使用的唯一输入法。不过不足之处也很明显，就是常用的词库真的很少，选词的频率非常高。

不知道目前有没有一个在线更新词库文件的方案，可以定期手动更新词库文件，也可以由手动提交本地词库到云端优化主词库。不过这样也势必会造成相应的资金成本。。。

另外目前的开源输入法好像都没有在线更新词库的功能，导致根本无法和商业输入法相匹敌，或许可以制定一套第三方国家通用离线词库的标准格式。

**Comment by tumashu** [comment]
其实主要的问题是没有同学愿意开发词库：-）
