### ISSUE TITLE
似乎有几率多个异步进程会同时写dcache文件

### ISSUE THREAD

**Issue by whatacold** [tumashu/pyim#202]
`M-x list-processes` 偶尔会看到有 emacs 进程没有退出，`(setq async-debug t)` 打开 aync 的调试开关，可以看到未退出进程的buffer 内容是：

    Lisp expression: ...dcache-ishortcode2word locked by whatacold@KE... (pid 16292): (s, q, p, ?)? 

所以是并发写导致的？`16292`这个进程已经不存在了，一天使用下来，有三个这样未退出的 emacs 进程。

系统是Win7，`M-x version`:

    GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-27

Linux 系统上也有碰到过。

**Comment by tumashu** [comment]
暂时我这边还没碰到，如果确实有这个问题， 我估计也是 async 的bug :-)
