### ISSUE TITLE
Conflict with fci-mode

### ISSUE THREAD

**Issue by yanghaoxie** [tumashu/pyim#205]
When `fci-mode` is enabled, the popup of `pyim` is shift; this happens in `company-mode` too. I found a work around for `company-mode` (turning off `fci-mode` when `company` is completing, turn on `fci-mode` when `completion` is done, basically). Is there any work around for `pyim`. The code for `company-mode` is:
`;; solve fci mode conflicts with company mode`
`(defvar-local company-fci-mode-on-p nil)`

`(defun company-turn-off-fci (&rest ignore)`
`  (when (boundp 'fci-mode)`
`    (setq company-fci-mode-on-p fci-mode)`
`    (when fci-mode (fci-mode -1))))`

`(defun company-maybe-turn-on-fci (&rest ignore)`
`  (when company-fci-mode-on-p (fci-mode 1)))`

`(add-hook 'company-completion-started-hook 'company-turn-off-fci)`
`(add-hook 'company-completion-finished-hook 'company-maybe-turn-on-fci)`
`(add-hook 'company-completion-cancelled-hook 'company-maybe-turn-on-fci)`

**Comment by tumashu** [comment]
pyim-active-hook?  pyim-page-select-finish-hook?

**Comment by yanghaoxie** [comment]
It seems that my code does not work, maybe something is wrong?
The column indicator does not turn off when I input chinese.
```
;; solce fci mode conflicts with pyim
(defvar-local pyim-fci-mode-on-p nil)
 
(defun pyim-turn-off-fci (&rest ignore)
  (when (boundp 'fci-mode)
    (setq pyim-fci-mode-on-p fci-mode)
    (when fci-mode (fci-mode -1))))

(defun pyim-maybe-turn-on-fci (&rest ignore)
  (when pyim-fci-mode-on-p (fci-mode 1)))
(add-hook 'pyim-active-hook 'pyim-turn-off-fci)
(add-hook 'pyim-page-select-finish-hook 'pyim-maybe-turn-on-fci)
(provide 'init-fill-column-indicator)

```

**Comment by tumashu** [comment]
Maybe you can try to  advice : pyim-tooltip-show and pyim-terminate-translation two functions.

**Comment by yanghaoxie** [comment]
Sorry, I am noob in elisp, could you please give me some hint to do the trick? maybe some guide from stack exchange or something? I really appreciate that!
