### ISSUE TITLE
pyim-convert-code-at-point 匹配不了全角的一些中文标点

### ISSUE THREAD

**Issue by godscat** [tumashu/pyim#206]
发现一个不算bug的bug，是emacs 没有把 全角的  **：** 和全角的 **－** 划入 [:punct:] 的匹配中，运行pyim-convert-code-at-point 的时候不能转换回去（从全角转半角的时候），我自己把 3441 行改了下就好了。目前就找到这两个不能转的。我不会 Pull requests 只能发这里了。

**Comment by tumashu** [comment]
Fixed, 谢啦
