### ISSUE TITLE
pyim decache 占用内存空间大小对于小内存电脑 有些庞大

### ISSUE THREAD

**Issue by c0001** [tumashu/pyim#207]
你好 tumashu：

我是一个pyim的忠实用户，首先感谢你对pyim的实现所做的努力，因为正如你的介绍，pyim使得emacs的中文输入和emacs的契合度提升很多，这惠及了很多像我一样的emacs中文使用者。

为了阐述我的问题，我需要带上我使用的词库，因此我贴上我使用[词库的git项目地址](https://github.com/c0001/entropy-pyim-dicts/tree/master/) 以及我所使用的操作系统是win10-1803，emacs版本27.0.50。

近期我忽然间发现pyim对于词库的缓存于内存中的映射空间有些庞大，具体数据如下：

> 我使用词库的分布是以一个核心词库作为输入基础，然后以一个扩展词库（包含一些流行词汇和专业术语）来使得pyim输入潇洒连贯。

1. 使用大词库
- 词库总大小：约100M （使用词库 sogou 和 pyim-greatdict）
- 内存扩增大小：约800M

2. 使用小词库
- 词库大小：约40M (使用词库 sogou 和 rime)
- 内存扩增大小：约500M

综上数据的简单分析，我得出内存中的缓存映射大约有8倍的大小扩增于词库。

另外当重新缓存词库（删除词库缓存后重新写入dcache）的时候，内存扩增是暂时的16倍，最后回落到8倍（因为缓存重新写入完毕）。

这对于我所使用的小内存pc（仅有6g内存）是一个打击，因为试想：
> 我开机使用内存是2.6g，浏览器使用firefox日常内存占用2g，本来emacs日常占用空间大小50到70兆，它的内存空间尚且不会频繁由于内存不足而被切到虚拟内存页中，但是如果我启用了pyim，那么情况就有些尴尬了。

我知道也许应该加几根金条了，但是我还是想是否办法减少这种内存占用？毕竟老机子了还是有感情的（没钱 -^-! ）。

**Comment by tumashu** [comment]
感谢同学的支持，不过可惜的是，内存这一块，我做不了多少工作，词库加载后，会生成一个hashtable，这是它消耗内存的原因，由于emacs的单线程，以我现在的能力，实在想不到更快搜索词条的方式了，另外吐槽一下，你老机器用6g内存？ 我的linux机子才2g。。？

**Comment by tumashu** [comment]
另外greatdict实在是太大了，我用的一个中等大小的词库，bigdict，效果也不错，不过词条来源不是来源，所以无法发布到melpa，你到我的项目emacs-helper里面可以找到

**Comment by redguardtoo** [comment]
我以前用C写过输入法,也有内存消耗更大的问题. 后来不再建立hash表,直接查找单词(有效率的前提是词必须在字典里已排序),这样100M的文件只要消耗100M内存.

**Comment by tumashu** [comment]
嗯，不过这些算法怎么用 elisp 已有的函数实现，我暂时还木有时间思考， 但如果真要搞，那估计就是大工程

**Comment by c0001** [comment]
谢谢两位的回答，抱歉2天后才回复。

其实我也只是抱着试试看的心态想找到解决办法，因为提问前我也意识到了想要在当前的emacs lisp机制上弥合输入响应速度和节约内存空间这是一个鱼和熊掌的事情，很难。

我想通过使用索引的方式转而使用词库文件搜索作为辞典交互机制是个好主意，但是输入延迟的问题我想与内存哈希表对比......（虽然使用了索引优化,但是emacs单线程的效率问题很头疼,还关乎磁盘延迟等）。我想如果使用外部输入法的与emacs做交互,就像lsp一样会是一个方向,但是这就没有了emacs的原汁原味了,也就无从谈起内置输入法了。

虽然我是个编程刚入门（也许入门还谈不上），因此现在我只能空有一颗想要使pyim变好的心了。还是谢谢两位国内emacs元老了，以后有什么emacs问题，还请多多指教。

以后待我水平提升，我会第一个来尝试解决这个问题的 :smile: 。

**Comment by c0001** [comment]
@tumashu  老机子 6g 都已经好多年了，那个时候刚开始也是2g，这个4g内存条是我某鱼上淘的，很难想象 win上只有2g还能扫雷吗？除非是linux上的xface等这类的X前端或想i3之类那种，现在单单gnome3 2g都会卡出翔的啦 😺

**Comment by tumashu** [comment]
```
以后待我水平提升，我会第一个来尝试解决这个问题的 smile 。
```
绝对欢迎，有这个心思就是好的开始，当年我折腾 eim 的时候，也是一个新手，折腾了一年，对 elisp也熟悉了， pyim也折腾出来了
