### ISSUE TITLE
用小鹤双拼，打不出 “嗯”这个字？

### ISSUE THREAD

**Issue by cnshsliu** [tumashu/pyim#208]
用小鹤双拼，打不出 “嗯”这个字？

**Comment by 275761919** [comment]
解决了吗？不仅 en , 而且 an 也是无效的。

**Comment by cireu** [comment]
这里是Windows 10，使用Spacemacs的develop分支。小鹤双拼没有任何问题。包括我这段字都是emacs里用pyim的小鹤打的……
![tim 20181015190131](https://user-images.githubusercontent.com/18224684/46947383-3a401d00-d0ad-11e8-9186-f5d0fc873930.png)
![tim 20181015190114](https://user-images.githubusercontent.com/18224684/46947394-3f9d6780-d0ad-11e8-9bed-35a1bfd8c463.png)
![tim 20181015190154](https://user-images.githubusercontent.com/18224684/46947397-41672b00-d0ad-11e8-88c2-edc126300f4b.png)

**Comment by tumashu** [comment]
我 revert 这个PR了， 因为后来发现，这个PR会导致： 小鹤双拼模式a开头的击键序列不能直接上屏 #224 

("ac" "ao") 
（ao” “ao”） 

上面两个对应关系只能存在一个，因为在内部流程中， 还存在反向查找的过程，如果存在两条规则，反向查找就会出问题
--
