### ISSUE TITLE
自动切换在有的 major mode 中失灵

### ISSUE THREAD

**Issue by whatacold** [tumashu/pyim#212]
平时在 org md等文件中是可以自动切换的，但是有时候又不行，猜测跟 major mode 有关，比如 html 文件、 plantuml-mode 文件。

比如在 plantuml-mode 中，我在 “你好” 后接着输入 n 就直接输入 n 了，用 `C-h k` 看了下直接就执行了 `self-insert-command` 了。

该怎么排查及解决？

**Comment by tumashu** [comment]
plantuml-mode属于prog mode?

**Comment by whatacold** [comment]
是的：

    (define-derived-mode plantuml-mode prog-mode "plantuml"
    "Major mode for plantuml.

    Shortcuts             Command Name
    \\[plantuml-complete-symbol]      `plantuml-complete-symbol'"

**Comment by tumashu** [comment]
那就是预期的行为， prog-mode 写编码为主，只有注释可能写写大篇中文， plantuml 比较特殊

···
;; (setq-default pyim-english-input-switch-functions
;;               '(pyim-probe-dynamic-english
;;                 pyim-probe-isearch-mode))
···

**Comment by whatacold** [comment]
有定制方法吗？ `web-mode` 也是这样

**Comment by tumashu** [comment]
我已经给你配置了呀？

**Comment by whatacold** [comment]
哦，原来是这个意思 :( 刚才没看明白是由于 `pyim-probe-program-mode` 返回 `t` 导致直接输入英文了。

我稍微作了一些封装，希望更给别人一些参考。

感谢！

    (defun whatacold/pyim-probe-program-mode ()
    "Predicate whether to input ASCII character for current major mode."
    (and (not (member major-mode '(web-mode plantuml-mode)))
        (pyim-probe-program-mode)))

    (setq-default pyim-english-input-switch-functions
                    '(pyim-probe-dynamic-english
                    pyim-probe-isearch-mode
                    whatacold/pyim-probe-program-mode
                    pyim-probe-org-structure-template))
