### ISSUE TITLE
error in process sentinel: Opening input file: No such file or directory, /tmp/pyim-bigdict.pyim.gz

### ISSUE THREAD

**Issue by Qquanwei** [tumashu/pyim#215]
我随手删掉了 /tmp 目录里的内容。然后切换到pyim就报这个错误
```
error in process sentinel: Opening input file: No such file or directory, /tmp/pyim-bigdict.pyim.gz
```

我尝试删除.emacs.d目录下的pyim文件夹也无法修复这个问题。重启emacs也不行

emacs version: GNU Emacs 25.3.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.5) of 2018-01-12

**Comment by tumashu** [comment]
检查 .emacs 文件

**Comment by Qquanwei** [comment]
在`.emacs.d/init.el` 里找到了这句话

```
(pyim-dicts
     (quote
       ((:name "pyim-bigdictg" :file "/tmp/pyim-bigdict.pyim.gz"))))
```

删掉确实好了。能够在代码里修复/tmp目录被删掉的问题？

**Comment by tumashu** [comment]
这个是你自己设置成使用tmp的，和pyim没多大关系

**Comment by Qquanwei** [comment]
我不记得有过这个设置。如果未来再出现这种情况再reopen这个issue。
