### ISSUE TITLE
pyim-forward/backward-word 在英文字符下移动太慢

### ISSUE THREAD

**Issue by manateelazycat** [tumashu/pyim#220]
Emacs 默认的 forward/backward-word 会尽量在 "[^a-Z]" 的字符内尽可能调到最远的下一个单词边界.
pyim-forward/backward-word 在英文字符区域内, 有时候是一个字符一个字符的移动.

比如下面是两种方法的光标跳转的位置:
字符串: ("s-x f" . one-key-menu-magit)
Emacs 移动距离:   |("s|-x| f|" . one|-key-menu-magit)
pyim 移动距离: |(|"|s|-|x| |f|"| |.| |one|-key-menu-magit)

pyim 在英文区域的字符移动策略应该和 forward/backward-word 一样.

建议改进方法:
1. 记住当前位置
2. 然后分别用 emacs 的 forward/backward-word 方法以及 pyim 中文的方法进行跳转
3. 如果 pyim 的跳转在中文区域, 采用 pyim 的方法, 如果 pyim 跳转后还是英文, 直接用 emacs 的方法

这样应该能够兼顾 emacs 原生方法的距离和 pyim 在中文分词方面的细腻.

**Comment by manateelazycat** [comment]
> 这样搞的化，逻辑就比较复杂了，不知道实现之后可靠不？

只是建议, 没试过.
现在的实现移动要把人急死. 🤣

**Comment by tumashu** [comment]
我不用这两个命令，说实话真的没有动力优化， 先关了，如果确实需要这个功能， 发PR吧  。。。。
