### ISSUE TITLE
仓颉候选字乱码

### ISSUE THREAD

**Issue by lampui** [tumashu/pyim#222]
![image](https://user-images.githubusercontent.com/15785343/46397174-1501f500-c724-11e8-9df9-9e3ed794b351.png)

![image](https://user-images.githubusercontent.com/15785343/46397673-6494f080-c725-11e8-92a4-b01a2389edb6.png)

使用仓颉方案，候选字发生乱码，查看 dcache 目录下生成的 hash 表，也是乱码的。

version info:

![image](https://user-images.githubusercontent.com/15785343/46397552-167fed00-c725-11e8-8396-1acf76b6e6c1.png)

**Comment by tumashu** [comment]
字体问题吧？

**Comment by lampui** [comment]
solved.
的确是字体缺失问题，最后安装了Noto Sans CJK 字体，再重新安装了 pyim 和 pyim-canjie5dict 解决了。

[参考ibus 下 rime 候选词乱码](https://github.com/rime/ibus-rime/issues/28#issuecomment-304433180)
