### ISSUE TITLE
小鹤双拼模式a开头的击键序列不能直接上屏

### ISSUE THREAD

**Issue by cireu** [tumashu/pyim#224]
使用小鹤双拼时, 遇上a开头的序列双拼输入法会对击键序列进行转换, 此时按RET会将双拼转换后的字母上屏, 并非原来的击键序列直接上屏

有时候会出现一些很尴尬的情况
原来的击键序列为"emacs"
![tim 20181022222218](https://user-images.githubusercontent.com/18224684/47298663-f28c3900-d64a-11e8-9dc5-975e3401828e.png)

**Comment by tumashu** [comment]
应该修复了，可以试试
