### ISSUE TITLE
Feature request: 以u或者i开头的词库

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#226]
因为拼音没有u和i开头的，能不能把u和i开头作为acronym词库，这个词库格式如下：
u_code 词（如 uzg 中华人民共和国， 当然词可以是英文或者符号。

**Comment by tumashu** [comment]
```
或者符号
```
标点符号暂时不可以

**Comment by QiangF** [comment]
自从更新到最新版本，u和i开头的词没法使用了

**Comment by tumashu** [comment]
不应该呀，这块代码没动过呀，，，

**Comment by QiangF** [comment]
pyim-imobj-validp在
Feng Shu: Simplify pyim-imobjs-create:quanpin [Wed Jan 30 13:19:47 2019 +0800 (6 个月前)]
不见了

**Comment by QiangF** [comment]
问题在pyim-pinyin-split 
比如我的词典

    idegc ℃

    (pyim-pinyin-split  "idegc")

returns nil

**Comment by QiangF** [comment]
大师你看看我改的：

    (defun pyim-pinyin-split (pinyin)
    "将一个代表拼音的字符串 PINYIN, 分解为声母韵母对组成的列表. 以u和i开头的不分解。

    这个过程通过循环的调用 `pyim-pinyin-get-charpy' 来实现，整个过程
    类似用菜刀切黄瓜片，将一个拼音字符串逐渐切开。"
    (let (charpy spinyin (input pinyin))
        (while (when (string< "" pinyin)
                (setq charpy (pyim-pinyin-get-charpy pinyin))
                (if (equal (car charpy) '("" . ""))
                    (progn
                    (setq spinyin nil)
                    (setq pinyin ""))
                (setq spinyin (append spinyin (list (car charpy))))
                (setq pinyin (cdr charpy)))))
        (or spinyin (list (list input)))))

**Comment by tumashu** [comment]
我现在都想不起来，当时因为什么原因吧 pyim-imobj-validp 删除了。。。。 汗！

**Comment by redguardtoo** [comment]
@tumashu , 可以考虑建立CI, 参考 https://github.com/redguardtoo/evil-nerd-commenter . 很简单的.
创建`Makefile`和`.travis.yml`. 用github帐号登录 https://travis-ci.org/ 启动CI就可以了.

**Comment by tumashu** [comment]
@redguardtoo 现在 pyim 没有 test 文件，建立CI的意义就大打折扣了

**Comment by tumashu** [comment]
@QiangF 我试着修复了一下，再试试吧
