### ISSUE TITLE
isearch: too many spaces for whitespace matching

### ISSUE THREAD

**Issue by RenWenshan** [tumashu/pyim#228]
发现当 (pyim-isearch-mode 1) 的时候，C-s 然后输入字符串可以工作，但是如果是 select 一个字符串，M-w, C-s , C-y，minibuffer 里面就会显示：too many spaces for whitespace matching

**Comment by tumashu** [comment]
我这边无法重现你说的这个问题

**Comment by RenWenshan** [comment]
我也只能在 Mac 上重现，emacs-version 27.0.50，最新的 pyim，在 Debian 上使用正常。

**Comment by tumashu** [comment]
估计emacs27的 isearch 作了某种更新吧。。。。

**Comment by tumashu** [comment]
只能做到这地步了。。。。祝好运
