### ISSUE TITLE
pyim-import bug

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#230]
这一行，把icode2word变量重置，导致导入失败。建议删除。

    (pyim-dcache-update-icode2word-dcache t)

**Comment by QiangF** [comment]
另外写了一个函数，可以把一个org文件中的链接作为新词导入

    (defun my-pyim-import (file)
      "words are file links in org mode, eg [[file:王八蛋]]" 
      (interactive "FFile path:")
      (let ((temp-file "/tmp/my-temporary-dict"))
        ;; parse file
        (let ((word-list
              (with-temp-buffer
                (let ((coding-system-for-read 'utf-8-unix))
                    (insert-file-contents file))
                (org-element-map (org-element-parse-buffer) 'link
                        (lambda (link)
                            (when (string= (org-element-property :type link) "file")
                            (org-element-property :path link)))))))
             (with-temp-file temp-file
                (insert ";;; -*- coding: utf-8-unix -*-\n")
                (insert (string-join word-list "\n"))
                (when (file-writable-p file)
                (write-region (point-min) (point-max) temp-file))))
        (pyim-import temp-file)))

**Comment by QiangF** [comment]
反正加上那行就导入失败，测试如下
1. 创建一个文件 test

    ;;; -*- coding: utf-8-unix -*-
    田田田

2. （pyim-import "./test"）
3. 输入tiantiantian，没有
4. 把那一行删除重新import，就有了
5. （pyim-delete-words-in-file "./test"） 再试还是如此。

**Comment by QiangF** [comment]
是(defun pyim-dcache-update-icode2word-dcache (&optional force) 里面有一行
将pyim-dcache-icode2word 重置了

          (pyim-dcache-set-variable 'pyim-dcache-icode2word)

**Comment by QiangF** [comment]
是不是要加一句           ,(async-inject-variables "^pyim-dcache.+?directory$")

**Comment by tumashu** [comment]
应该修复了
