### ISSUE TITLE
error in process sentinel: async-handle-result: Symbol’s value as variable is void: content

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#231]
大师救命！最新pyim。把dcache文件夹删除，重起emacs，dcache文件夹有3个文件：
pyim-dcache-shortcode2word pyim-dcache-ishortcode2word pyim-dcache-icode2word
我的设置和backtrace在这里：
https://gist.github.com/QiangF/cd736a2b8fa2061d370b9efd0b44f075

**Comment by QiangF** [comment]
pyim-dcache-word2code is a variable defined in ‘pyim.el’.
Its value is #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data
              ())

**Comment by QiangF** [comment]
/home/q/.dotfiles/.emacs.d/pyim/symbol.pyim  内容：

    ;;; -*- coding: utf-8-unix -*-
    idegc ℃
    ipm ±
    ideg °
    imicro µ
    itimes ×
    icheckmark ✓

以i和u开头的拼音没法用。

**Comment by QiangF** [comment]
GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian

**Comment by tumashu** [comment]
应该修复了
