### ISSUE TITLE
Feature request:pyim-translate成对转换标点

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#233]
大师能不能把这个设为默认

    (setq pyim-wash-function #'pyim-delete-last-word)

但是pyim-translate不能成对转换标点， 比如编辑org文件，插入链接用英文[[]]，我用
electric-pair-mode，中文环境下输入【就自动补全了，光标在括号中间，按v进行标点符
号转换，后面一半没法处理。能不能在pyim-translate删除成对的标点和插入都用
electric-pair-mode中的函数，这样不用担心不成对。

ps: 强烈推荐 https://github.com/kjambunathan/org-mode-ox-odt

**Comment by QiangF** [comment]
https://github.com/twlz0ne/fuck.el

这个fuck可以成对转换，怎么把pyim的 “v” 设成 运行fuck呢？

    (defun pyim-punctuation-translate-at-point ()
    "切换光标处标点的样式（全角 or 半角）。"
    (interactive)
    (fuck))

**Comment by QiangF** [comment]
这样可以:

    (defun pyim-punctuation-translate-last-n-puncts (&rest args)
    "切换光标处标点的样式（全角 or 半角）。"
    (interactive)
    (fuck))

建议设成缺省，原因如下：
1. 现在成对标点基本上都是成对输入，光标在中间。
2. 用户不可能在输入一大串相连的字符串才发现中英文标点错了，同时转换光标前所有符号不是很实用

**Comment by tumashu** [comment]
cool

**Comment by tumashu** [comment]
也许我应该把 pyim-punctuation-translate-last-n-puncts 函数设置成一个可设置变量

**Comment by QiangF** [comment]
也许这样
1个v： something like (fuck)
2个v连按： 光标附近（前、后）全部替换

**Comment by QiangF** [comment]
大师，还是你的好，我改了一下，更符合一般的工作习惯：
1. 现在成对标点基本上都是成对输入，光标在中间。
2. 用户不可能在输入一大串相连的字符串才发现中英文标点错了，并且标点符号要么是一个，要么是一对，同时 转换光标前所有符号不是很实用

    (defun pyim-char-after-to-string (num)
    "得到光标前第 `num' 个字符，并将其转换为字符串。"
    (let* ((point (point))
            (point-after (+ point num)))
        (char-to-string (char-after point-after))))

    (defun pyim-punctuation-translate-last-n-puncts (&optional punct-style)
    "将光标前1个或前后连续成对的n个标点符号进行全角/半角转换，当 `punct-style' 设置为 `full-width' 时，
    所有的标点符号转换为全角符号，设置为 `half-width' 时，转换为半角符号。"
    (interactive)
    (let ((punc-list (pyim-flatten-list pyim-punctuation-dict))
            (punct-style
            (or punct-style
                (intern (completing-read
                        "将光标处的标点转换为" '("full-width" "half-width")))))
            ;; lnum : puncts on the left (before point)
            ;; rnum : puncts on the right (after point)
            (lnum 0) (rnum 0) (point (point)) last-puncts result)
        (catch 'break
        (while t
            (let ((str (pyim-char-after-to-string rnum)))
            (if (member str punc-list)
                (incf rnum)
                (throw 'break nil)))))
        (catch 'break
        (while (<= lnum rnum)
            (let ((str (pyim-char-before-to-string lnum)))
            (if (member str punc-list)
                (incf lnum)
                (throw 'break nil)))))
        ;; 右侧与左侧成对匹配
        (setq rnum (min lnum rnum))
        (setq last-puncts (buffer-substring (- point lnum) (+ point rnum)))
        ;; 删除旧的标点符号
        (delete-char rnum)
        (delete-char (- 0 lnum))
        (dolist (punct  (split-string last-puncts ""))
        (dolist (puncts pyim-punctuation-dict)
            (let ((position (cl-position punct puncts :test #'equal)))
            (when position
                (cond
                ((eq punct-style 'full-width)
                (if (= position 0)
                    (push (pyim-punctuation-return-proper-punct puncts) result)
                    (push punct result)))
                ((eq punct-style 'half-width)
                (if (= position 0)
                    (push punct result)
                    (push (car puncts) result))))))))
        (insert (mapconcat #'identity (reverse result) ""))
        (backward-char rnum)))

**Comment by tumashu** [comment]
大师这个词让我感觉自己好像神棍。。。

**Comment by tumashu** [comment]
你先使用一段时间，如果觉得好用，就pr一下

**Comment by QiangF** [comment]
特别好用，比如我的org文档引用，现在就特别方便。

    见图[[fig1]]. ->  见图[[fig1]]。

不会变成

    见图[[fig1]]. ->  见图[[fig1】】。

**Comment by tumashu** [comment]
添加了，
