### ISSUE TITLE
使用五笔时启动速度很慢

### ISSUE THREAD

**Issue by sheepduke** [tumashu/pyim#237]
当使用 `pyim-wbdict` 时， `pyim` 的启动速度就变得很慢（超过10秒）。

如下是我的配置。

```emacs-lisp
(use-package pyim
  :ensure
  :init
  (require 'pyim)
  ;; 设定默认输入法
  (setq default-input-method "pyim")
  ;; 使用五笔
  (require 'pyim-wbdict)
  (setq pyim-default-scheme 'wubi)
  ;; 中文使用全角标点，英文使用半角标点。
  (setq pyim-punctuation-translate-p '(auto yes no))
  ;; 作为五笔用户，我觉得自己完全不需要选词框。
  (setq pyim-page-tooltip 'minibuffer)

  ;; 设定词库文件
  (pyim-wbdict-v98-enable)

  :bind
  ("C-`" . toggle-input-method))
```
经过一番调查，看起来像是 `pyim-start` 中的下列代码导致了这个问题：

```emacs-lisp
  (when pyim-dcache-auto-update
    ;; 使用 pyim-dcache-iword2count 中的信息对 personal 缓存中的词频进行调整。
    (pyim-dcache-update-icode2word-dcache restart)
    ;; 创建简拼缓存， 比如 "ni-hao" -> "n-h"
    (pyim-dcache-update-ishortcode2word-dcache restart))
```

如下是 `profile-report` （CPU）的结果：
```
- command-execute                                                 255  56%
 - call-interactively                                             255  56%
  - funcall-interactively                                         250  55%
   - toggle-input-method                                          166  36%
    - activate-input-method                                       166  36%
     - apply                                                      166  36%
      - pyim-start                                                166  36%
       - pyim-dcache-init-variables                               144  31%
        - pyim-dcache-set-variable                                144  31%
         - pyim-dcache-get-value-from-file                        143  31%
          - insert-file-contents                                    1   0%
           - set-auto-coding                                        1   0%
              find-auto-coding                                      1   0%
       + pyim-pinyin2cchar-cache-create                            13   2%
         pyim-cchar2pinyin-cache-create                             4   0%
   + execute-extended-command                                      84  18%
  + byte-code                                                       5   1%
- ...                                                             194  43%
   Automatic GC                                                   186  41%
```

目前初步的解决方案是增加 `(setq pyim-dcache-auto-update nil)` 配置。请问有什么线索吗？

**Comment by sheepduke** [comment]
经过进一步的调查，发现：

如果使用配置 `(setq pyim-dcache-auto-update nil)` 并删除 `pyim/dcache` 文件夹，下一次开启 `pyim` 后，它将无法正常工作。

**Comment by tumashu** [comment]
dcache 里面的文件不能删除， 第一次加载 pyim 词库的时候， pyim会将词库转换为 dcache里面的文件，来减少加载时间。

**Comment by sheepduke** [comment]
@tumashu 
在不人工修改 dcache 文件的情况下，重启 Emacs 并激活 pyim，加载还是特别慢

**Comment by tumashu** [comment]
能不能用  emacs -q 测试一下，看是不是慢，linux下一般是4秒左右的加载时间

**Comment by sheepduke** [comment]
我清除了 dcache，并把无关的配置去除，仅在 `~/.emacs` 文件中保留如下配置：

```emacs-lisp
(package-initialize)
(require 'use-package)

(use-package pyim
  :ensure
  :init
  (require 'pyim)
  ;; 设定默认输入法
  (setq default-input-method "pyim")
  ;; 使用五笔
  (require 'pyim-wbdict)
  (setq pyim-default-scheme 'wubi)
  ;; 中文使用全角标点，英文使用半角标点。
  (setq pyim-punctuation-translate-p '(auto yes no))
  ;; 作为五笔用户，我觉得自己完全不需要选词框。
  (setq pyim-page-tooltip 'minibuffer)

  ;; 设定词库文件
  (pyim-wbdict-v98-enable)

  :bind
  ("C-`" . toggle-input-method))
```

初次打开 Emacs 并切出输入法，Emacs 卡住约10秒，dcache 生成。
再次打开 Emacs 并切出输入法，Emacs 卡住约10钞，dcache 文件夹写入时间未更新。

**Comment by tumashu** [comment]
看看dcache下面文件的大小

**Comment by sheepduke** [comment]
```
  -rw-rw-r-- 1 sheep sheep 1.5M Jan 16 17:47 pyim-dcache-code2word
  -rw-rw-r-- 1 sheep sheep  207 Jan 16 17:47 pyim-dcache-code2word-md5
* -rw-rw-r-- 1 sheep sheep  760 Jan 16 18:44 pyim-dcache-icode2word
* -rw-rw-r-- 1 sheep sheep  613 Jan 16 18:44 pyim-dcache-ishortcode2word
* -rw-rw-r-- 1 sheep sheep  453 Jan 16 18:44 pyim-dcache-iword2count
* -rw-rw-r-- 1 sheep sheep 2.4M Jan 16 18:45 pyim-dcache-shortcode2word
  -rw-rw-r-- 1 sheep sheep 1.6M Jan 16 17:47 pyim-dcache-word2code
```

时间标记为 `18:4x` 的四个文件会在重启 Emacs 后被更新。

**Comment by tumashu** [comment]
缓存看起来挺正常的, 而且缓存文件的大小也很小，我的词库缓存有 50M, 加载也不超过4秒

```
(load "~/.emacs.d/pyim/dcache/pyim-dcache-code2word")
```

测试以下加载缓存的速度

**Comment by tumashu** [comment]
(define-key pyim-mode-map "." 'pyim-self-insert-command)

**Comment by tumashu** [comment]
可能是使用 thread 的缘故, 测试一下下面的设置
```
(setq pyim-dcache-prefer-emacs-thread nil)
```

**Comment by yefeiyu** [comment]
> 可能是使用 thread 的缘故, 测试一下下面的设置
> 
> ```
> (setq pyim-dcache-prefer-emacs-thread nil)
> ```
with my test, the line resaluted the question.

**Comment by tumashu** [comment]
resaluted？嘛意思？

**Comment by yefeiyu** [comment]
resoluted?

**Comment by sheepduke** [comment]
@tumashu 在我的机器上，变量 `pyim-dcache-prefer-emacs-thread` 的值本来就是 `NIL`，所以我觉得它不是主要影响因素。

**Comment by tumashu** [comment]
暂时将 pyim-dcache-auto-update 设置为 nil 吧，对于五笔而言，如果词库不变化，设置为nil 也没什么影响

**Comment by sheepduke** [comment]
@tumashu 我也发现了这个解法，但是总觉得有点奇怪 XD

**Comment by yefeiyu** [comment]
> 暂时将 pyim-dcache-auto-update 设置为 nil 吧，对于五笔而言，如果词库不变化，设置为nil 也没什么影响

可是要添加自定义词语

**Comment by tumashu** [comment]
@sheepduke  我这边再次测试了一下，禁用 thread 之后，速度就会有明显提升，你可以分别 eval 一下下面几行代码，看看哪一行会导致 emacs 卡住。
```
(setq pyim-dcache-prefer-emacs-thread nil)
(pyim-dcache-use-emacs-thread-p)

(pyim-dcache-update:icode2word t)
(pyim-dcache-update:ishortcode2word t)
(pyim-dcache-update:code2word t)
(pyim-dcache-update:shortcode2word t)
```

**Comment by yefeiyu** [comment]
没看明白。
这6行、保持前2行不注释、依次注释后4行中的一行？

**Comment by tumashu** [comment]
设置 pyim-dcache-prefer-emacs-thread 为 t 和 nil 测试两次， 看看后4句哪一句卡

**Comment by yefeiyu** [comment]
最后一句会在刚调出输入法时卡一瞬间。
不管第一句是t还是nil，最后一句都使情况变严重一点点。

第一句nil与否的影响最大。如果是t，其他的即使都注释掉，也非常卡。

**Comment by tumashu** [comment]
emacs -q 试试吧，如果卡顿超过5秒，就不太正常

**Comment by yefeiyu** [comment]
> (define-key pyim-mode-map "." 'pyim-self-insert-command)

今天重装了下，发现五笔下无法输入逗号和句号上屏。
找了很久。
希望将这一行写到说明里。很重要。

**Comment by tumashu** [comment]
我突然感觉，逗号句号默认设置为前进后退可能不太合适

**Comment by yefeiyu** [comment]
确实不太合适。前进后退有约定俗成的键，就是＋和－键。

**Comment by tumashu** [comment]
已经调整了

**Comment by yefeiyu** [comment]
使用五笔自定义的词库打开emacs时启动是拖慢了。

**Comment by tumashu** [comment]
不知道是不是因为五笔提示按键功能导致启动慢了，或许应该给提示按键功能添加一个设置选项。

**Comment by sheepduke** [comment]
> 不知道是不是因为五笔提示按键功能导致启动慢了，或许应该给提示按键功能添加一个设置选项。

按键提示不应该是在按键的时候才生效的么？为什么会拖慢启动速度呢？

**Comment by xiaodongcentury** [comment]
> 当使用 `pyim-wbdict` 时， `pyim` 的启动速度就变得很慢（超过10秒）。
> 
> 如下是我的配置。
> 
> ```emacs-lisp
> (use-package pyim
>   :ensure
>   :init
>   (require 'pyim)
>   ;; 设定默认输入法
>   (setq default-input-method "pyim")
>   ;; 使用五笔
>   (require 'pyim-wbdict)
>   (setq pyim-default-scheme 'wubi)
>   ;; 中文使用全角标点，英文使用半角标点。
>   (setq pyim-punctuation-translate-p '(auto yes no))
>   ;; 作为五笔用户，我觉得自己完全不需要选词框。
>   (setq pyim-page-tooltip 'minibuffer)
> 
>   ;; 设定词库文件
>   (pyim-wbdict-v98-enable)
> 
>   :bind
>   ("C-`" . toggle-input-method))
> ```
> 
> 经过一番调查，看起来像是 `pyim-start` 中的下列代码导致了这个问题：
> 
> ```emacs-lisp
>   (when pyim-dcache-auto-update
>     ;; 使用 pyim-dcache-iword2count 中的信息对 personal 缓存中的词频进行调整。
>     (pyim-dcache-update-icode2word-dcache restart)
>     ;; 创建简拼缓存， 比如 "ni-hao" -> "n-h"
>     (pyim-dcache-update-ishortcode2word-dcache restart))
> ```
> 
> 如下是 `profile-report` （CPU）的结果：
> 
> ```
> - command-execute                                                 255  56%
>  - call-interactively                                             255  56%
>   - funcall-interactively                                         250  55%
>    - toggle-input-method                                          166  36%
>     - activate-input-method                                       166  36%
>      - apply                                                      166  36%
>       - pyim-start                                                166  36%
>        - pyim-dcache-init-variables                               144  31%
>         - pyim-dcache-set-variable                                144  31%
>          - pyim-dcache-get-value-from-file                        143  31%
>           - insert-file-contents                                    1   0%
>            - set-auto-coding                                        1   0%
>               find-auto-coding                                      1   0%
>        + pyim-pinyin2cchar-cache-create                            13   2%
>          pyim-cchar2pinyin-cache-create                             4   0%
>    + execute-extended-command                                      84  18%
>   + byte-code                                                       5   1%
> - ...                                                             194  43%
>    Automatic GC                                                   186  41%
> ```
> 
> 目前初步的解决方案是增加 `(setq pyim-dcache-auto-update nil)` 配置。请问有什么线索吗？

LZ好, 设置 pyim 探针设置，这是 pyim 高级功能设置，可以实现 *无痛* 中英文切换 :-)  这个功能您是怎么解决的?

**Comment by tumashu** [comment]
我猜测是因为五笔的按键提醒功能导致速度比较慢，不过缓存一次，

**Comment by tumashu** [comment]
然后设置(setq pyim-dcache-auto-update nil) 也可以，毕竟五笔词库几乎不变化

**Comment by tumashu** [comment]
至于探针功能，说白了就是环境测试函数，每次按键都会调用这些函数，来决定师傅输出中文

**Comment by xiaodongcentury** [comment]
> 至于探针功能，说白了就是环境测试函数，每次按键都会调用这些函数，来决定师傅输出中文

按照您的设置, 问题是现在我无法输入中文. 输入法显示“英文”

**Comment by tumashu** [comment]
按M-j试试

**Comment by xiaodongcentury** [comment]
按M-j试试, minibuffer display "the expressions to be joined are of different type"
after comment "setq-default pyim-english-input-switch-functions" and "setq-default pyim-punctuation-half-width-functions" sections, now emacs can input chinese wubi.
THX!

**Comment by tumashu** [comment]
激活这个 pyim 探针函数后，使用下面的规则动态切换中英文输入：
我用的探针是这种模式

1. 从光标往前找第一个非数字的字符，为中文字符时，输入下一个字符时默认开启中文输入
2. 从光标往前找第一个非数字的字符，为其他字符时，输入下一个字符时默认开启英文输入
3. 使用 ‘pyim-convert-code-at-point’ 可以将光标前的 code 字符串转换为中文，
   所以用户需要给 ‘pyim-convert-code-at-point’ 绑定一个快捷键，比如：

   (global-set-key (kbd "M-i") ’pyim-convert-code-at-point)

这个函数用于：‘pyim-english-input-switch-functions’ 。

**Comment by tumashu** [comment]
而且开启编程探针之后，一般只能在字符串里面连续输入中文

**Comment by xiaodongcentury** [comment]
您的probe是否只适用于拼音输入法？我尝试多次，均以失败告终。只有将"setq-default pyim-english-input-switch-functions" and "setq-default pyim-punctuation-half-width-functions"注释掉后，五笔才能正常输入。
也有可能我的设置有问题。
再次感谢！

**Comment by xiaodongcentury** [comment]
您的probe是否只适用于拼音输入法？我尝试多次，均以失败告终。只有将"setq-default pyim-english-input-switch-functions" and "setq-default pyim-punctuation-half-width-functions"注释掉后，五笔才能正常输入。
也有可能我的设置有问题。
再次感谢！

**Comment by tumashu** [comment]
这个帖子太长了，有其它问题新开帖子吧。
