### ISSUE TITLE
使用rime 的五笔时时一级简码显示拼音

### ISSUE THREAD

**Issue by mengqp** [tumashu/pyim#238]
我用pyim使用的是rime的五笔输入法，
这是我的配置
[https://github.com/mengqp/emacs.d/blob/develop/lisp/init-pyim.el]

在(setq pyim-debug t)的情况下测试的，输入一级简码后使用pyim-convert-code-at-point。
![snipaste_2019-01-18_14-47-24](https://user-images.githubusercontent.com/8331712/51369864-0d7a2680-1b30-11e9-916b-d5c958eb0c50.png)

然后，我删除rime/dcache 文件夹后，第一次输入就可以正常显示。
![snipaste_2019-01-18_14-42-21](https://user-images.githubusercontent.com/8331712/51369641-49f95280-1b2f-11e9-9805-fb7d54f033c2.png)
 第二次之后又会变成原来那样

**Comment by tumashu** [comment]
感觉像 liberime 的问题，试试：
```
(liberime-search "j")
```

**Comment by tumashu** [comment]
好像是liberime识别不了五笔，不知道是 librime的问题还是 liberime 的bug
```
(liberime-get-schema-list)
```

**Comment by mengqp** [comment]
> 
> 
> 感觉像 liberime 的问题，试试：
> 
> ```
> (liberime-search "j")
> ```

这个我试过了，liberime是正确的，我发的第一张图片里面，rime-words,也是一直是正确的，只不过用的却是personal-words，如果不出personal-words是nil的话，也能正确打出字来，我又试了试，不只是一级简码，只要我打的可以进行拼音，总是先走拼音，如果拼音不通过，才会取五笔的字

**Comment by mengqp** [comment]
> 
> 
> 好像是liberime识别不了五笔，不知道是 librime的问题还是 liberime 的bug
> 
> ```
> (liberime-get-schema-list)
> ```

确实，liberime会在.emacs.d/rime/build/ 底下多了一个pinyin_simple 的方案，我删了pinyin_simeple.*之后，重新启动emacs，打字后还是会出pinyin_simple的东西

**Comment by tumashu** [comment]
我想问一下，你有没有升级到最新的 pyim ？

**Comment by tumashu** [comment]
更新了一下，试试吧

**Comment by mengqp** [comment]
> 
> 
> 更新了一下，试试吧

![snipaste_2019-01-22_08-29-44](https://user-images.githubusercontent.com/8331712/51505152-ee291500-1e1f-11e9-9d6d-2afe01c6e629.png)

我测试了一下，在Debug模式下目前显示的都是五笔的rime-words,虽然下面还是有拼音的

**Comment by tumashu** [comment]
我又做了一次更新，应该不存在这个问题了

**Comment by mengqp** [comment]
> 
> 
> 我又做了一次更新，应该不存在这个问题了

我将这个
  (setq pyim-debug t)

输入中文的时候不出scode-list了

**Comment by tumashu** [comment]
嗯，这次我将 quanpin 和 rime 的代码分开了， quanpin因为涉及到多个词条源，所以有debug代码， rime只有一个源，不需要这段代码
