### ISSUE TITLE
请问一下`pyim-load-hook`和`pyim-active-hook`为什么要设置为buffer local variable？

### ISSUE THREAD

**Issue by galeo** [tumashu/pyim#239]
最近增加的对rime的支持，看到[liberime](https://gitlab.com/liberime/liberime)文档给的使用说明，将`setup-liberime`添加到`pyim-load-hook`，是否每次加载pyim都要运行`setup-liberime`？是否可以添加一个`pyim-first-load-hook`，可以设置第一次启动pyim的时候运行`setup-liberime`？

针对这两个hook做设定，切换buffer时，这两个hook的设定都成了`nil`，这样很不方便呀。

**Comment by tumashu** [comment]
看 pyim 文档中的 liberime 设置，里面有设置方式，不需要hook

**Comment by galeo** [comment]
谢谢。

根据 pyim 文档中的 liberime 设置，每次运行都要启动 rime session，能否需要时再启动？

我本来想在pyim启动前和关闭之后做一些设置，添加了一个hook到`pyim-active-hook`，advice了一个function到`pyim-inactivate`。结果发现上面两个hook都是buffer local variable，切换了buffer以后设置就失效了。请问一下 `pyim-load-hook` 和 `pyim-active-hook` 可以用来做什么，为什么要设置为buffer local variable？

**Comment by tumashu** [comment]
为什么设置为buffer变量，其实我也不知道，可能是随手设置的，说实话这两个hook可能还没人用过。

**Comment by tumashu** [comment]
估计当时码代码的时候，觉得这个地方该留个hook吧

**Comment by galeo** [comment]
那么能否取消设置这两个hook为buffer local变量？

**Comment by tumashu** [comment]
Fixed

**Comment by galeo** [comment]
谢谢！
