### ISSUE TITLE
能否添加五笔反查、难字拼音查输的功能

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#244]
今天转换了一个极点五笔的码表，后面本想添加拼音输入功能，我的设想是，查“火”字，就输入“zzhuo”，可是加到码表后出来的是“湖为”，“湖hu”、“为o（「为」字的一级简码是o）”。
我刚才想了想，添加拼音只能是遇到不会的字用zz+拼音开头输入这个字，还是无法知道这个字五笔编码是什么，如果输入zz+拼音后出来的字带有“火[ooo]”这样的编码提示就更好了。

**Comment by yefeiyu** [comment]
fork了一个pyim-wbdict，上传了极点的码表，添加了拼音反查功能。编码提示可不会了：）

**Comment by tumashu** [comment]
反查功能不能从 pyim-wbdict 那边搞。。。

**Comment by tumashu** [comment]
极点五笔的词库是什么协议的，如果不是gpl等来源兼容协议，是不能和pyim-wbdict一起发布的

**Comment by yefeiyu** [comment]
> 极点五笔的词库是什么协议的，如果不是gpl等来源兼容协议，是不能和pyim-wbdict一起发布的

查了下，没看到资料。不过极点词库可以自由导出为txt，是否表示可以自由使用？
极点很多不错功能，可以借鉴
不过希望新版着重输入体验上。现在上字方式比传统的要差点

另，再问下：这个新版比23日版本好像又多了一个bug，五笔下打完字词不按空格确认直接按标点的话，就会把这个词“吃掉”，不上屏、只上了标点。
是否好解决

**Comment by tumashu** [comment]
现在上字方式比传统的要差点，具体说明一下，我不用五笔，不了太了解，如果没有版权说明的话，你只能自己留着使用，不能集成到wbdict

**Comment by tumashu** [comment]
五笔下打完字词不按空格确认直接按标点的话，就会把这个词“吃掉”，不上屏、只上了标点。

这个合理的反应是什么？ 词上屏幕，还是词和标点同时上屏幕？

**Comment by yefeiyu** [comment]
词和标点同时上屏。即标点本身即有确认的意思。因为五笔打完四码后需要`选词`的情况很少，即使出现两个备选词的情况，基本也是第一个常用，所以就不做空格确认选词，而是直接继续打标点，第一顺位的备选词和标点同时上屏。

**Comment by tumashu** [comment]
词和标点同时上屏已经添加

**Comment by tumashu** [comment]
提示五笔码的功能已经添加，实现方式不太一样，但可用
