### ISSUE TITLE
成对标点后打字错误

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#245]
双括号、双引号等后面，打任何字都只上屏一级简码的字。
譬如hjkl分别对应【上是中国】，那么在双引号后打【止hh】，只上屏【上】字，【止步hhhi】，上屏的是【上 步】。

**Comment by tumashu** [comment]
这个应该修复了，试试吧

**Comment by tumashu** [comment]
我这边成对的双引号后面可以输入

**Comment by tumashu** [comment]
我这个又用 window cmd 测试了一下，最新代码也没有这个问题

**Comment by yefeiyu** [comment]
上一回复里  的“霓虹灯”效果，就是在这两幅图片里。  
请注意最后7行，就是在打字时上面的内容来回变化产生的不同

![img_0246](https://user-images.githubusercontent.com/4845104/52177709-26f1c280-2800-11e9-9825-b7932e8520d7.png)
![img_0247](https://user-images.githubusercontent.com/4845104/52177710-2b1de000-2800-11e9-816f-3f6afc86a59b.png)

**Comment by yefeiyu** [comment]
哈哈，按理说五笔确实没必要要提示框。但引号的问题没有解决啊：）

**Comment by yefeiyu** [comment]
这个问题有一定的修正吗？目前正常了，不过标点好像占用的空间较大，似乎是全角，用“auto yes no”改了没效果。

**Comment by tumashu** [comment]
我这边这块暂时没有动过

**Comment by yefeiyu** [comment]
目前是逗号和句号占用了一整个汉字的间隔。这个正常，目前各个软件都是这么设计的。
目前的单双引号占用了一整个汉字的间隔。这个稍不正常，目前各个软件都是占半个。且占用的这一整个间隔中，视觉不太舒服的问题出在=> “它是偏居在最左侧”。
如果右引号后面跟一个句号或逗号，那么句号和逗号位于右引号所占一个字符间隔的右边一半、句号/逗号本身占用的一个字符间隔完全空白。视觉非常不舒服。
类似这样：
“  你好”  他说。
“  你好”，     他说。

**Comment by tumashu** [comment]
如果用等宽字体，根本不应该存在这种情况，半角就是半角，全角就是全角

**Comment by yefeiyu** [comment]
locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by yefeiyu** [comment]
使用这个终端，我用vim打开输入了几个字，发现句号逗号都是汉字的全角的，单双引号竟然是英文的标点。

**Comment by tumashu** [comment]
设置成zh_CN.UTF-8试试

**Comment by yefeiyu** [comment]
这两天新装，把前面的东西都忘了。
刚才又折腾了一会儿双引号这个问题。
最后改成“(setq pyim-page-tooltip 'minibuffer)”暂时解决，但是还是有前面说的左侧双引号后空格太大的问题。
————
如果不使用minibuffer，就会造成左侧双引号后，输入“你好”会显示成“人　好”，两字中间多一个空格。我猜想，是输入左引号后，这个输入过程并未完成、待输入“你好wqvb”这个词的“w”第一个字母后，才算是当作一个带空格的确认键、确认了左单引号算是完成，于是出现输入了“人”字的情况。同时，因为当作空格确认键，导致“人”字后面又上了一次空格键。

**Comment by tumashu** [comment]
这个感觉不是 pyim 这边的问题，所以 issue 暂时关闭了。
