### ISSUE TITLE
五笔使用体验之重要建议

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#246]
使用体验亟待完善的方面：
打【确认选词】这里的时候，【确认dqyw】、【选tfqp】、【词yngk】，dqyw后出现【确认、确诊】两个备选项，确诊为生僻词，各输入法都是打完dqyw后不必按空格选定【确认】一词，而是接着打【选词tfyn】、此时各家输入法都是【确认】自动上屏。
但是pyim的确认依然留在待选区，屏幕上出现【dqywtfyn确认造词、确认乖戾】这样的选项。
这一情况，就是pyim出现之初即已经讨论过的【四码直接上屏】的issue了吧。
极其希望早日解决。

**Comment by yefeiyu** [comment]
四码上屏确实是个很细致很有挑战性的工作。
譬如打『平铺guqg』，打了guqg后因为是唯一单词无可选词，直接上屏了。此时反而上屏太快，给人感觉是【无可选余地】，和其他单词以及在输入过程中的整个逻辑不符，很突兀。
所以说这事和刚才说的请求一并解决，即唯一四码单词也不立即上屏，但后面有输入则立即上屏。
请您测试。

2,                                              
还有一种状况，『四成lhdc』。本来想打『四lh』『码dcg』，该词的编码按理是『四lh』＋『码dcg』＝
『四码lhdc』，但码表不包含这词，屏幕上打出来的是『四成』，而四成这词在码表中的编码是lhdn，所以『四码』这词打了后最终连『四成』这词都没能上屏。          
但此时，lhdc这四个字母并没有消失，而是在看不见的后台。。『四码上屏』这词接着输入后，最终上屏只有一个『上』字，比较乱。而中途修改的时候，lhdc这四个字母还需要连按四次backspace键才能最终消除干净。                                                                    
正常情况下，是输入lhdc后，待选框无单词、只有这四个字字母，如继续输入『上h』字，自动清除这四个字母的同时，上屏『上』字；不继续输入『上h』字，则可逐步步退格c、d、h、l，以便边退格边修改。

**Comment by tumashu** [comment]
```
此时反而上屏太快，给人感觉是【无可选余地】
```
这个特性我已经删除了

**Comment by yefeiyu** [comment]
> ```
> 此时反而上屏太快，给人感觉是【无可选余地】
> ```
> 这个特性我已经删除了

感谢，今天的修改后已经比较舒服了。
