### ISSUE TITLE
标点后小bug

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#248]
标点后输入单字母的一级简码回车键，使此单字母上屏，上屏这个字母的光标后面出现半个该简码的字。如想要最终结果是`,h`, 结果是`,h(光标)上`。

**Comment by tumashu** [comment]
这个我这边重现不了

**Comment by yefeiyu** [comment]
这个问题倒是不大，场景很少。暂时不处理没关系。
可能是我使用纯控制台没进入X系统没使用xterm的原因。

**Comment by tumashu** [comment]
做个 gif 看看，我在无法重现

**Comment by yefeiyu** [comment]
刚才试了多个终端，问题可能是由终端启动的emacs，该问题显现。
Mac下的自带终端有这问题、自带终端启动的tmux终端更严重些。我前面主要用的是linux console控制台下的终端。
在非终端启动的emacs中无此问题。

**Comment by tumashu** [comment]
我在 window 的终端下试了一下，没有这个问题，感觉像是一个 term 显示刷新慢导致的问题。

**Comment by yefeiyu** [comment]
这是linux控制台级别的纯终端。其他所有term类终端都是如此，包括mac下、linux下各类终端。
![img_0243](https://user-images.githubusercontent.com/4845104/52177144-bfd01000-27f7-11e9-8213-70479d4f3b60.gif)

**Comment by yefeiyu** [comment]
可以正常显示中文。在终端里可以打开使用emacs

**Comment by yefeiyu** [comment]
我是使用vps的console，没安装X。搬瓦工的
用来学点从入门到放弃的python
emacs写点东西
安装个docker，这玩意属于懒人用的。
这样配置下来，平时拿个小ipad出门，使用ssh（现在改用ssh变种的mosh，掉线自动重连）一连接，也能完成好多活了。
本来ipad无法外接蓝牙键盘打五笔的，有pyim，这也可以了。
如果是出差狗、记者、码农，我感觉ipad+vps基本可以应急应付一阵。
