### ISSUE TITLE
关于四码上屏着重开一帖

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#250]
1,输入四码后：
a，码表无，如lhdc：四个字母在屏、不立即清屏，便于修改（目前实现）
b，码表有，
（a）单个词：如dcge码表，四字母在屏、不立即清屏，便于修改（目前实现）
（b）多个词：如dqyw确认、确诊，四字母在屏、不立即清屏，便于修改（目前实现）
2,输入第五码后：
a，码表无，如lhdc h：清除前四个编码，屏幕出现『h上』，可继续输入『hhgy上班』
b，码表有，
（a）单个词：如dcge h码表上，『码表』直接上屏并清除dcge，屏幕出现『h上』
（b）多个词：如dqyw h确认上，『确认』直接上屏并清除dqyw，屏幕出现『h上』

概括一句话就是：
输入四码后不管有没有字、词，屏幕如实反映码表；输入第五码后前四码有字词就首选字词上屏、无字词就清除编码，第五码算新的输入的第一码的开始。

其他的即时添加自定词、编码反查、拼音辅助输入、标点符号造成的问题、异形字和符号输入、分号上屏第二选项、大小字符集切换，都可滞后解决。

**Comment by tumashu** [comment]
今天研究了一下，完全不用空格选择，实现难度很大，暂时没找到实现方法，不过一句话按一次空格的话，相对来说实现起来比较简单，你可以试试最新的代码。

**Comment by tumashu** [comment]
1. 拼音辅助输入(已经添加)
3. 异形字(我不打算自己弄, PR is welcome)
4. 符号输入(看起来像一个词库问题)
5. 分号上屏第二选项(这个好像已经有此功能)
6. 大小字符集切换(这个应该在 pyim-wbdict 包里添加)

**Comment by tumashu** [comment]
```
大小字符集切换(这个应该在 pyim-wbdict 包里添加)
```
另外一个方式是，添加一个hook，自动过滤

**Comment by yefeiyu** [comment]
刚才简单试了一会儿，较之前的方式有一定的改进，省掉了一直按退格键删除的繁琐。
现在的模式是输入N个词，都是修改版虚拟四码上屏，在视觉上较为完善，但实际上在后台仍然“悬着”，直到第N+1个字时空格键上屏，那么本次共计N+1个词的输入算全落定了。如果在按空格之前退格删除输入的字母，一旦删除超过最后一个词的所输入字母数(<4)，即删至N-1个字母时，本次输入的N个词会全部抹除。
这个方法仍然不是太完美。

思路方面
1、是否可以第5个字母输入后，判断该字母前面：
a、有空格键的输入则无动作
b、无空格键的输入则：删除第5个字母同时将第5个字母放入粘贴板；空格确认；粘贴第5个字母以继续输入
（这属于乱弹哈：）
2、或者借鉴windows下的freeime极点，或者unix/linux下的fcitx、scim，或者mac下的清歌输入法，看看他们的是如何解决该问题的。

3、或者拆分pyim为pyim-py、pyim-wb两种输入法，单独在pyim-im中解决该问题。

**Comment by yefeiyu** [comment]
> 暂时只能这样子了，因为涉及到 emacs 底层 event 的一些代码

翻过旧贴，过了两年还是听到同一个消息，我感觉沉痛的心疼。

**Comment by tumashu** [comment]
哈哈，这没法，emacs输入法框架需要慢慢的学习

**Comment by yefeiyu** [comment]
这个9问题的解决可以说是pyim“可用”和“能用”的分水岭。求助emacs社区及官方或前辈高人看看可以吗

**Comment by yefeiyu** [comment]
试了一会儿，效果非常好，四码上屏可以说完美解决。
明晚给楼主拜年，并在捐赠页面发红包感谢：）

**Comment by tumashu** [comment]
哈哈，春节快乐 too, 这个我就暂时关闭了
