### ISSUE TITLE
在捐赠页给pyim发了一个红包，拜年了哈:-)

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#253]
非常非常感谢tumashu的付出。

捐赠

您可以通过小额捐赠的方式支持 pyim 的开发工作，具体方式：
通过支付宝收款账户：tumashu@163.com
通过支付宝钱包扫描：
![img_0248](https://user-images.githubusercontent.com/4845104/52179870-7218cf00-281a-11e9-9cda-a289ddc36323.jpeg)

**Comment by tumashu** [comment]
谢啦！

**Comment by yefeiyu** [comment]
哈，这么快关了，我还想着号召一下呢。惭愧啊嘿嘿
