### ISSUE TITLE
这个输入法非常好

### ISSUE THREAD

**Issue by sosoeo** [tumashu/pyim#255]
我换了win10专业版新笔记本,新装cygwin,结果里面的emacs经常不能切换使用系统自带输入中文输入法，用cygwin和Emacs 这些年总时不时有这些问题，这个输入法非常好，这样就可以配置自己的.emacs文件夹了，下次换新环境就更方便了

**Comment by tumashu** [comment]
能帮到其他 emacser ，我也很高兴，pyim是我在 emacs下的主要输入法

**Comment by yefeiyu** [comment]
> 我换了win10专业版新笔记本,新装cygwin,结果里面的emacs经常不能切换使用系统自带输入中文输入法，用cygwin和Emacs 这些年总时不时有这些问题，这个输入法非常好，这样就可以配置自己的.emacs文件夹了，下次换新环境就更方便了

欢迎新朋友
