### ISSUE TITLE
pymap 的上游资源

### ISSUE THREAD

**Issue by girzel** [tumashu/pyim#258]
pyim-pymap.el 里的comments提到，这个mapping是来自rime-pinyin-simp，再追一步是来自Google的PinyinIME。我下了后者的源代码，它并没有文本的mapping，好像是binary，不知道怎么取出来。如今Emacs的维护者愿意更新emacs的拼音mapping，但我希望能用到Google的最新版本，你知道怎么要到吗？

**Comment by tumashu** [comment]
这个我不知道啊，我是直接用的rime里面的

**Comment by girzel** [comment]
好的！我就直接问他们。最近在看 libpinyin，觉得很有意思，说不定什么时候可以作为输入法的后台。

https://github.com/libpinyin/libpinyin

**Comment by tumashu** [comment]
有可能，不过到目前为止，没人hack，我前一段时间折腾rime支持，效果非常不错
