### ISSUE TITLE
posframe最近更新之后输入框变窄了

### ISSUE THREAD

**Issue by xiangsheng** [tumashu/pyim#259]
最近posframe更新之后pyim的输入框比原来变小了，第一行的候选变窄了，而且整体宽度也不够，如下图所示
![pyim](https://user-images.githubusercontent.com/5061641/54528331-a8b83c80-49b7-11e9-85d0-8ce2e4571825.png)

**Comment by tumashu** [comment]
嗯，设置pyim-posframe-border-width就可以了

**Comment by xiangsheng** [comment]
确实如此，谢谢！
