### ISSUE TITLE
How to us evil-escape when I am input Chinese using pyim?

### ISSUE THREAD

**Issue by yanghaoxie** [tumashu/pyim#260]
It seems that I cannot use `evil-escape` to get back to `evil-normal-state`, when I am using pyim to insert Chinese. By the way, my `evil-escape` and `pyim` configurations are show as followings:
```
(use-package evil-escape
    :defer 5
    :diminish evil-escape-mode
    :init
    (setq evil-escape-key-sequence "jk"
	  evil-escape-unordered-key-sequence t)
    :config
    (evil-escape-mode))
```
```
(use-package pyim
  :defer t
  :commands (pyim-convert-string-at-point toggle-input-method)
  :init
  :general
  ("M-j" 'pyim-convert-string-at-point)
  :config
  (setq pyim-fuzzy-pinyin-alist '(("s" "sh")
				  ("c" "ch")
				  ("z" "zh")
				  ("in" "ing")
				  ("en" "eng")
				  ("l" "n")))
  (setq default-input-method "pyim")
  (setq pyim-default-scheme 'quanpin)
  (setq-default pyim-english-input-switch-functions
		'(pyim-probe-dynamic-english
		  pyim-probe-isearch-mode
		  pyim-probe-program-mode
		  pyim-probe-org-structure-template))

  (setq-default pyim-punctuation-half-width-functions
		'(pyim-probe-punctuation-line-beginning
		  pyim-probe-punctuation-after-punctuation))
  (if (version<= "26.1" emacs-version)
      (progn
	(setq pyim-page-tooltip 'posframe)))
  (setq pyim-page-length 5))
```

**Comment by tumashu** [comment]
maybe probe: pyim-probe-evil-normal-mode  can help you

**Comment by yanghaoxie** [comment]
It seems like this prob is just make `pyim` switch to English imput method when we are in `evil-normal-state`, but this is not what I want.
It would be great to have the following feature,
when I am inputting using pyim, if  I the keys I pressed match the `evil-escape-key-sequence`, I can escape from insert state to normal state.

**Comment by tumashu** [comment]
do you mean when you press j, switch to nornal mode?  but how to input Chinese jing?

**Comment by yanghaoxie** [comment]
It is not what I mean.

It seems like that `evil-escape` use a timer to achieve this feature.

For example, if I enter `jk` in `0.1` second, then I will get back to normal state and `jk` will be delete from the buffer, but if the time interval is larger that `0.1`, `jk` will be insert to the buffer.

For `pyim`, I guess a similar mechanism may be possible.

If this is possible, it would be painless for `evil-escape` users to use `pyim`.

**Comment by tumashu** [comment]
This feature is not possible at the moment.  need more thought about a beautiful way.

**Comment by yanghaoxie** [comment]
I see.

Thank you very much! I wish someday it will be possible.

**Comment by tumashu** [comment]
Maybe I can find a hack way for you:

```
(defun pyim-self-insert-command ()
  "Pyim 版本的 self-insert-command."
  (interactive "*")
  (let* ((scheme-name (pyim-scheme-name))
         (class (pyim-scheme-get-option scheme-name :class))
         (n (pyim-scheme-get-option scheme-name :code-split-length)))
    (princ pyim-entered)
    (cond
     ((and (equal pyim-entered "j")
           (equal last-command-event ?k))
      (push last-command-event unread-command-events)
      (pyim-outcome-handle 'pyim-entered)
      (pyim-terminate-translation)
      ;; Now jk is insert to buffer, do some change may work

      )
     ((and pyim-auto-select
           (eq class 'xingma)
           (= (length pyim-entered) n))
      ;; 五笔等型码输入法，重码率很低，90%以上的情况都是选择第一个词条，
      ;; 这里添加自动选择功能，减少按空格强制选词的机会。
      (push last-command-event unread-command-events)
      (unless (equal pyim-candidates (list pyim-entered))
        (pyim-outcome-handle 'candidate))
      (pyim-terminate-translation))
     ((pyim-input-chinese-p)
      (pyim-entered-handle
       (concat pyim-entered
               (char-to-string last-command-event))))
     (pyim-candidates
      (pyim-outcome-handle 'candidate-and-last-char)
      (pyim-terminate-translation))
     (t
      (pyim-outcome-handle 'last-char)
      (pyim-terminate-translation)))))

```

**Comment by driftcrow** [comment]
> Maybe I can find a hack way for you:
> 
> ```
> (defun pyim-self-insert-command ()
>   "Pyim 版本的 self-insert-command."
>   (interactive "*")
>   (let* ((scheme-name (pyim-scheme-name))
>          (class (pyim-scheme-get-option scheme-name :class))
>          (n (pyim-scheme-get-option scheme-name :code-split-length)))
>     (princ pyim-entered)
>     (cond
>      ((and (equal pyim-entered "j")
>            (equal last-command-event ?k))
>       (push last-command-event unread-command-events)
>       (pyim-outcome-handle 'pyim-entered)
>       (pyim-terminate-translation)
>       ;; Now jk is insert to buffer, do some change may work
> 
>       )
>      ((and pyim-auto-select
>            (eq class 'xingma)
>            (= (length pyim-entered) n))
>       ;; 五笔等型码输入法，重码率很低，90%以上的情况都是选择第一个词条，
>       ;; 这里添加自动选择功能，减少按空格强制选词的机会。
>       (push last-command-event unread-command-events)
>       (unless (equal pyim-candidates (list pyim-entered))
>         (pyim-outcome-handle 'candidate))
>       (pyim-terminate-translation))
>      ((pyim-input-chinese-p)
>       (pyim-entered-handle
>        (concat pyim-entered
>                (char-to-string last-command-event))))
>      (pyim-candidates
>       (pyim-outcome-handle 'candidate-and-last-char)
>       (pyim-terminate-translation))
>      (t
>       (pyim-outcome-handle 'last-char)
>       (pyim-terminate-translation)))))
> ```

函数不能用了。

**Comment by tumashu** [comment]
```
(defun my-pyim-self-insert-command (orig-func)
  (interactive "*")
  (if (and (equal (pyim-entered-get) "j")
           (equal last-command-event ?k))
      (progn
        (push last-command-event unread-command-events)
        (pyim-outcome-handle 'pyim-entered)
        (pyim-terminate-translation))
    (call-interactively orig-func)))

(advice-add 'pyim-self-insert-command :around #'my-pyim-self-insert-command)
```

**Comment by tumashu** [comment]
试试

**Comment by driftcrow** [comment]
谢谢，效率真高 。 这个可以按jk 进入normal 模式，只是好像 没办法 输入jk码的字，如蝇，蜈。。。

**Comment by tumashu** [comment]
再试试

**Comment by driftcrow** [comment]
中文字后面输入jk直接进入normal 模式，回显区显示 

> Pyim: pyim-convert-string-at-point do noting. 

前面为空格时正常控制，就是快输进入normal,慢输输入jk英文字符。（我是用的你配置里的自动探针）

**Comment by tumashu** [comment]
再试

**Comment by driftcrow** [comment]
这次效果还差些,中文后输入jk不进入normal 状态，候选区是编码kkj的候选字

**Comment by tumashu** [comment]
这次行不行？

**Comment by driftcrow** [comment]
还是不行，这次中文后输入jk，不进入 normal状态，buffer中输入` jkkj`进入英文状态

**Comment by tumashu** [comment]
我感觉是两个包使用同一种emacs 机制导致的冲突，估计不太容易解决

**Comment by driftcrow** [comment]
嗯，辛苦了 👍   evil-escape 本来就是很GEEK的东东，这个问题算是中西文化冲突的产物  😆

**Comment by driftcrow** [comment]
@tumashu 感觉你第一版的处理已经差不多了，所以仔细思考了下，差的只是如何输入jk编码的字，所以做了下修改，基本达到了evil-escape的流畅操作。

中文输入后 jk 进入 normal 模式，要输入 jk 编码的中文字时先输入；；作探针再输入
jk 就可以输入 jk 编码的字了



    (defun my-pyim-self-insert-command (orig-func)
    (interactive "*")
    (if (looking-back "；；.?" (- (point) 4))
        (set (make-local-variable 'temp-evil-escape-mode) nil)
        (set (make-local-variable 'temp-evil-escape-mode) t)
        )
    (if (and temp-evil-escape-mode
            (equal (pyim-entered-get) "j")
            (equal last-command-event ?k))
        (progn
            (push last-command-event unread-command-events)
            (pyim-outcome-handle 'pyim-entered)
            (pyim-terminate-translation))
        (progn
        (call-interactively orig-func)
        (if (and (not temp-evil-escape-mode)
            (equal (pyim-entered-get) "jk")
            )
            (save-excursion
                (backward-char)
                (backward-delete-char 2)))))
        )

    (advice-add 'pyim-self-insert-command :around #'my-pyim-self-insert-command)

**Comment by driftcrow** [comment]
看来是想弯了，这次应该是真的可以了，直接 比较 时间就可以了  😭 


    (defun my-pyim-self-insert-command (orig-func)
    (interactive "*")
    (if (and (local-variable-p 'last-event-time)
            (floatp last-event-time)
            (< (- (float-time) last-event-time) 0.2))
        (set (make-local-variable 'temp-evil-escape-mode) t)
        (set (make-local-variable 'temp-evil-escape-mode) nil)
        )
    (if (and temp-evil-escape-mode
            (equal (pyim-entered-get) "j")
            (equal last-command-event ?k))
        (progn
            (push last-command-event unread-command-events)
            (pyim-outcome-handle 'pyim-entered)
            (pyim-terminate-translation))
        (progn
        (call-interactively orig-func)
        (set (make-local-variable 'last-event-time) (float-time))
        ))
        )

    (advice-add 'pyim-self-insert-command :around #'my-pyim-self-insert-command)

**Comment by tumashu** [comment]
赞， 我看了一下 evil-escape 的代码，发现用一个时间限制的 read-event, 想了半天，也不知道该怎么获取这个时间限制，没想到竟然有 last-event-time 。。。

**Comment by driftcrow** [comment]
@tumashu 我觉得可以整理下放进包里，这样就可以减少使用者的配置，无缝切换了。可能改下函数名什么的

    (if (functionp 'evil-escape-p)
        (advice-add 'pyim-self-insert-command :around #'my-pyim-self-insert-command))

**Comment by tumashu** [comment]
这个还是放在配置里面吧，太小众太hack  :-)

**Comment by minyez** [comment]
@driftcrow @tumashu thanks for the work! After adapted to the new pyim version (3.9.5), the snippet works like a charm. This comment is left for reference.

The adaption is simply to change `pyim-outcome-handle` to `pyim-process-outcome-handle` and `pyim-terminate-translation` to `pyim-process-terminate`, i.e. compared to the [comment](https://github.com/tumashu/pyim/issues/260#issuecomment-570921604) by @driftcrow 

```diff
(defun my-pyim-self-insert-command (orig-func)
(interactive "*")
(if (and (local-variable-p 'last-event-time)
        (floatp last-event-time)
        (< (- (float-time) last-event-time) 0.2))
    (set (make-local-variable 'temp-evil-escape-mode) t)
    (set (make-local-variable 'temp-evil-escape-mode) nil)
    )
(if (and temp-evil-escape-mode
        (equal (pyim-entered-get) "j")
        (equal last-command-event ?k))
    (progn
        (push last-command-event unread-command-events)
-       (pyim-outcome-handle 'pyim-entered)
-       (pyim-terminate-translation))
+       (pyim-process-outcome-handle 'pyim-entered)
+       (pyim-process-terminate)
    (progn
    (call-interactively orig-func)
    (set (make-local-variable 'last-event-time) (float-time))
    ))
    )

(advice-add 'pyim-self-insert-command :around #'my-pyim-self-insert-command)
```

I think this should work for pyim after commit [6a916b](https://github.com/tumashu/pyim/commit/6a916b2989818900f8b47790a3329b8fd58e39aa).

**Comment by tumashu** [comment]
liuhui同学提出一个更好的解决方案，大家可以参考： https://emacs-china.org/t/pyim-key-chord-pyim/20633/12?u=tumashu
