### ISSUE TITLE
中文输入状态下输入u开头的单词，上屏时会交换u之后字母顺序

### ISSUE THREAD

**Issue by xiangsheng** [tumashu/pyim#262]
在中文输入状态下输入比如uab，按回车上屏后会自动变成uba。更具体地说，会把紧邻u的下一个字母交换至单词末尾，如uabcd会变成ubcda。这是为什么呢？而且即便u出现在单词中间也是如此，比如fluent会变成flunte。

**Comment by tumashu** [comment]
我这边测试了以下，似乎没有这个问题

**Comment by xiangsheng** [comment]
排查了一下，似乎是因为与[multi-keys](https://github.com/Liu233w/multi-keys.el)的按键设置有些冲突，我把`u8`绑定到了切换buffer，要是能在输入法状态中自动禁用`multi-keys`就好了。

**Comment by tumashu** [comment]
这个包似乎是一个pyim的用户写的，不过看起来已经不维护了，两年没更新了

**Comment by xiangsheng** [comment]
确实，在emacs-china上还见过关于这个包的[帖子](https://emacs-china.org/t/key-chord/1693)。看了一下代码似乎原因在于这个包修改了`key-translation-map`这个变量所致。

**Comment by tumashu** [comment]
这个pyim这边确实做不了什么。
