### ISSUE TITLE
liberime 支持

### ISSUE THREAD

**Issue by tumashu** [tumashu/pyim#264]

**Comment by tumashu** [comment]
@merrickluo emacs 26好像因为某个bug，无法使用liberime模块，我用emacs27试了一下， 一运行 liberime-search， emacs就崩溃退出了

**Comment by merrickluo** [comment]
我这里mac上一直用的emacs-nightly（27），Arch Linux 上是26.2都没问题呢，试试重新编译一下？

**Comment by tumashu** [comment]
emacs27就是我重新编译的，最后报错段错误

**Comment by tumashu** [comment]
https://gitlab.com/liberime/liberime/issues/5

**Comment by tumashu** [comment]
另外，这个问题好处理不？ https://gitlab.com/liberime/liberime/issues/3

**Comment by tumashu** [comment]
今天折腾了一晚上，终于找到可能的问题点了：
1.  liberime-start 的路径处理可能有问题， 对 ~ 和 “软链接” 支持存在某种bug，或者两种组合
2. liberime-start 的user-data-dir，必须要有词库，如果没有，就会报错。

@merrickluo

**Comment by tumashu** [comment]
暂时从elisp这边解决了

**Comment by tumashu** [comment]
@merrickluo 要不将 liberime 挪到 github上面来吧， gitlab 好像特别特别慢，点开个东西都不停的转圈圈

**Comment by tumashu** [comment]
@merrickluo 现在liberime是什么状态，还在维护吗？

**Comment by merrickluo** [comment]
我自己一直在用着，有什么问题吗？

tumashu <notifications@github.com> 於 2019年10月20日 週日 下午6:58 寫道：

**Comment by QiangF** [comment]
现在主要问题好像是在pyim里面使用无法使用Rime输入法的造词和字频排序功能
   https://github.com/tumashu/pyim/issues/295

**Comment by QiangF** [comment]
好像rime支持用户词库保存和同步，需要修改 pyim-create-word 和 pyim-delete-word

**Comment by tumashu** [comment]
@merrickluo 我看见gitlab上面的issue没动静，好奇问问，如果哥们没时间维护的话，就告诉我一声，我直接将liberime的代码放到pyim项目里，另外我以前折腾过几天liberime, https://github.com/tumashu/liberime，你看看有没有能用的东西，有用的话我就抽个时间发个pr，现学现卖的c，不知道好坏。

**Comment by tumashu** [comment]
@merrickluo 不过听到你还在维护liberime，还是非常高兴:-)

**Comment by merrickluo** [comment]
去看了一眼...不知道是不是设置不对，那几个issue我都没收到邮件...因为我自己一直用着没出啥问题所以也没怎么管，我明天把项目放到GitHub来吧...

tumashu <notifications@github.com> 於 2019年10月20日 週日 下午10:53 寫道：
