### ISSUE TITLE
rime输入五笔配置

### ISSUE THREAD

**Issue by shuxiao9058** [tumashu/pyim#265]
如图所示，因为码表我自己重定义了。

重定义后的关系的码表为“mexl”，但是使用pyim输入`mex`能够显示“关系”，但是输入“mexl”时不显示结果。见图

![output-2019-04-22-00:37:29](https://user-images.githubusercontent.com/3312525/56472930-59be6500-6497-11e9-885c-7111b67329d7.gif)

**Comment by tumashu** [comment]
1. 激活rime后，pyim仅仅处理词条显示问题，词库自定义需要用rime的方式
2. rime更改后，要重新deploy，目前只能重新启动emacs

**Comment by shuxiao9058** [comment]
@tumashu refer to https://github.com/tumashu/liberime/issues/1
