### ISSUE TITLE
EXWM floating window 怎么显示 tool tip

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#267]
采用默认的pyim-page-tooltip （use minibuffer），但是floating window 不显示minibuffer，大家怎么弄的啊？

**Comment by tumashu** [comment]
确实没有什么好法子， popup和posframe在这种情况下都没法使用， 如果 minibuffer 可以重定向，就好了

**Comment by QiangF** [comment]
如果floating window为当前窗口，M-x 依然可以打开一个非floating的minibuffer，也许EXWM的作者有办法。

**Comment by QiangF** [comment]
也许是pyim的问题？在全拼输入法下，输入i，i能正确显示在floating window后面的echo area里面。

**Comment by QiangF** [comment]
Possible workaround:
只要是中文输入模式，怎么默认使用 exwmx-sendstring-from-kill-ring，如果用exwmx-sendstring会报delete-window: Attempt to delete minibuffer or sole ordinary window

**Comment by QiangF** [comment]
EXWM 作者建议Detaching minibuffer，我试了如下的设置即时是floating window也可以显示备选栏，

    (setq exwm-workspace-minibuffer-position 'bottom
          minibuffer-auto-raise nil
          exwm-workspace-display-echo-area-timeout 2)

采用上面设置有一个问题：下面这种情况无法看备选项

      (read-from-minibuffer "Try type with an input method (eg. chinese):"))

因为minibuffer没有自动调节大小。

**Comment by QiangF** [comment]
EXWM minibuffer pyim 选词框不能自动调节大小的问题这样解决：

    (defun my-set-minibuffer-height (orig-func &rest args)
        (let ((set-height (and exwm-workspace--minibuffer (= 1 (frame-height exwm-workspace--minibuffer)))))
            (when set-height
                (set-frame-height exwm-workspace--minibuffer 2))
            (apply orig-func args)
            (when set-height
                (set-frame-height exwm-workspace--minibuffer 1))))

    (advice-add 'pyim-minibuffer-message :around #'my-set-minibuffer-height)

但是每输入一个字母候选词就闪烁一下，眼睛看着很不舒服。很奇怪，如果在minibuffer里面输入中文则没这个现象。例如：

    (read-from-minibuffer "Chinese input: ")))

大师有没有好方法？

**Comment by QiangF** [comment]
The solution is to check if pyim-translating before hide the
minibuffer.

    (defun exwm-workspace--on-echo-area-clear ()
    "Run in echo-area-clear-hook to hide echo area container."
    (unless (exwm-workspace--client-p)
        (unless (or (active-minibuffer-window) pyim-translating)
        (exwm-workspace--hide-minibuffer))
        (when exwm-workspace--display-echo-area-timer
        (cancel-timer exwm-workspace--display-echo-area-timer)
        (setq exwm-workspace--display-echo-area-timer nil))))

I also need to advice pyim-terminate-translation to hide the echo
area, pyim-terminate-translation set pyim-translating to nil, but
that happens before echo area clear.

    (advice-add 'pyim-terminate-translation :after 'exwm-workspace--on-echo-area-clear)
