### ISSUE TITLE
Can you provide configuration for Doom Emacs?

### ISSUE THREAD

**Issue by whjiang** [tumashu/pyim#268]
I love this PYIM. However, when I trying to add it to Doom Emacs, I encountered some issue. My steps are:
1. copy your configuration use-package to doom config, with minor changing from use-package to def-package!. 
2. use `(packages! pyim)` to enable pyim.
3. add 
```
(setq default-input-method "pyim")
(global-set-key (kbd "C-\\") 'toggle-input-method)
```
 to my doom configuration.

4. launch Emacs. In *stratch*, I pressed Ctrl-\ to switch input, however, it says 
```
activate-input-method: Can’t activate input method ‘pyim’ 
```

**Comment by tumashu** [comment]
maybe doom delay pyim's configure load, so when you active input method, pyim do not load

**Comment by whjiang** [comment]
If I skipped step #3, Ctrl-\ will switch to chinese-py-punct input method "拼符" instead of pyim.

**Comment by whjiang** [comment]
I also tried following code to replace step #3 
```
(after! pyim
  (setq default-input-method "pyim")
  (global-set-key (kbd "C-\\") 'toggle-input-method)
)
```
with no success.

**Comment by tumashu** [comment]
你如果直接使用 require， 看看什么情况

**Comment by tumashu** [comment]
按照我使用 use-package 的经验， after 只是说明 这些设置是在 pyim 加载完之后，才加载， 这样设置，搞不好 pyim 所有的设置都不会生效

**Comment by whjiang** [comment]
直接用你的配置，按`ctrl-\`显示`灵通-AU英`。但输入还是英文。

**Comment by whjiang** [comment]
搞清楚了，是眼前我在行首的缘故，在中文字后面就是中文输入了。

不过我的doom启动时间从1.5秒变成了3s多

**Comment by tumashu** [comment]
;; 设置 pyim 探针设置，这是 pyim 高级功能设置，可以实现 *无痛* 中英文切换 :-) ;; 我自己使用的中英文动态切换规则是： ;; 1. 光标只有在注释里面时，才可以输入中文。 ;; 2. 光标前是汉字字符时，才能输入中文。 ;; 3. 使用 M-j 快捷键，强制将光标前的拼音字符串转换为中文。 (setq-default pyim-english-input-switch-functions '(pyim-probe-dynamic-english pyim-probe-isearch-mode pyim-probe-program-mode pyim-probe-org-structure-template)) (setq-default pyim-punctuation-half-width-functions '(pyim-probe-punctuation-line-beginning pyim-probe-punctuation-after-punctuation))

**Comment by tumashu** [comment]
我的配置启用了探针功能

**Comment by whjiang** [comment]
你的探针整体还好，但感觉对于行首的处理不好。在行首，我按`m-j`也没法变成中文输入。

**Comment by tumashu** [comment]
可能我们使用的习惯不一样， 我一般是在 buffer 中直接输入拼音，如果需要转换，就按M-j，拼音就转换为中文了，接着继续输入
