### ISSUE TITLE
改善性能和内存占用的建议

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#273]
只使用默认的词库，切换输入法时比较卡，内存占用将近200M.而原始词库`pyim-basedit`大概是2M大小。

我以前用C做过输入法，所以还有点经验。问题关键在于lisp比较慢，读入文件后再为其建立表数据结构非常花时间且占用内存。

我以前的做法是是词库读入内存，不建立任何额外的数据结构，使用二分法（如何辞典是按序排列的）和正则表达式搜索原始文本。速度足够快且消耗内存很少。

如果你觉得这个建议可行，我可以提交pull request.

**Comment by tumashu** [comment]
pyim以前是用buffer做二分法，速度稍微有点慢，不知道你说的方式速度实际可以达到多少

**Comment by redguardtoo** [comment]
可以试试,我在`counsel-etags`用纯正则表达式,不优化250M的也就一秒延迟.有一个技巧就是不用buffer,用纯字符串搜索,这样速度快.可以把词库引擎做成动态切换的.这样可以保留现在的引擎.让用户选择.我可以先做点调研.

**Comment by tumashu** [comment]
行呢，可以试试

**Comment by redguardtoo** [comment]
请教个问题,以下三个cache文件有什么区别吗?

pyim-dcache-code2word
pyim-dcache-shortcode2word
pyim-dcache-icode2word

**Comment by tumashu** [comment]
第一个是词库直接生成的缓存，第二个是由词库缓存扩展而来的，比如 hao 好，扩展为 h 好，ha 好，第三个是用户选择过的词生成的缓存

**Comment by redguardtoo** [comment]
好消息.测试了一下`pyim-bigdict.pyim`,速度很快,内存消耗只有20M.还没有进行进一步优化. 诀窍就是只用原生C API,避免使用lisp写的API.

**Comment by redguardtoo** [comment]
另外模糊音怎么处理的?我是南方人,后鼻音和前鼻音分不太清.

**Comment by tumashu** [comment]
pyim-imobjs-find-fuzzy:quanpin

**Comment by redguardtoo** [comment]
在`pyim-create-word`的变量`orig-value`好像没有定义?

**Comment by redguardtoo** [comment]
目前测试80M的辞典输入会有一点延迟,比老的算法慢一点.如果辞典在20M一下,则延迟几乎可以忽略.

辞典载入速度非常快,消耗内存少.因为不需要建立hash表.基本算法就是把以拼音首字母把辞典分成26个块.在快中用正则表达式搜索.

**Comment by redguardtoo** [comment]
还有个问题,怎么关掉联想?

**Comment by tumashu** [comment]
暂时没有直接方式

**Comment by tumashu** [comment]
我看了一下你的实现，个人感觉不能和dcache搅和在一起，太乱，也许我们应该新取一个二级前缀，比如 dregcache, 原来的dcache 改为 dhashcache，都独立成新的文件

**Comment by tumashu** [comment]
词语联想需要的速度怎么样，因为联想需要大量的搜索

**Comment by redguardtoo** [comment]
是的,现在用`mapping-file`区分.实际数据结构是完全独立.

`dcache`和`file-mapping`独立出独立的文件是个好主意.

**Comment by QiangF** [comment]
大师有没有考虑用外部的命令，比如ag，会不会快一点？

**Comment by redguardtoo** [comment]
一次载入文件后是纯内存操作了.而且估算下来优化后的搜索就是对2M的字符串做搜索,rg不会快到哪里去.

**Comment by redguardtoo** [comment]
> 词语联想需要的速度怎么样，因为联想需要大量的搜索
联想就是把单个拼音拓展成正则表达式,没有什么特别,速度和其他搜索是一样的.

**Comment by tumashu** [comment]
mapping-file 这个名字换一个吧，pyim里面的对象名称都是一个单词

**Comment by redguardtoo** [comment]
> mapping-file 这个名字换一个吧，pyim里面的对象名称都是一个单词

已换成了`dregcache`
