### ISSUE TITLE
没有中文破折号

### ISSUE THREAD

**Issue by xuan-w** [tumashu/pyim#276]
大部分中文输入法将shift - 映射为中文破折号“——” u+2014
而pyim将其映射为"―" u+2015，这会导致在许多字体下显示为上划线而非破折号

根据 https://thetype.com/2019/03/14918/ 的说法，目前u+2014是事实上的标准，Windows、Mac、GBK-Unicode、JIS-Unicode、python、perl、Java虽然早先使用过u+2015，最新版操作系统及软件均已改用u+2014

**Comment by tumashu** [comment]
理由好充分啊。。。
