### ISSUE TITLE
排除无效的code

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#282]
我注意到在使用双拼时会搜索额外无效的code.

比如输入`wo`会产生`wuo`. 可以在 `pyim-dhashcahe-get` 或者 `pyim-dregcach-get` 中排除.

不过最好的办法是从源头排除. 是不是应从 `pyim-codes-create` 开始, 或者有其他更好的地方?

**Comment by tumashu** [comment]
这个可能得不偿失吧？

**Comment by redguardtoo** [comment]
一条if语句`(if (string-match "\wuo\\|wua"`足够判断一个长度有限的code,也就几毫秒而已.而且生成code的时候正在和用户交互,用户不会察觉这点延迟的.

**Comment by tumashu** [comment]
关键是这种没意义的搭配多么？

**Comment by redguardtoo** [comment]
双拼还蛮多的. 比如"我快了"

"我"有`wo`, `wuo`, "快"有, `kuai`, `king`, `kin` (模糊音),  所以共有 2*3 = 6 种组合.实际有效的只有一种组合.

如果是"我快来了"就是12种组合.

**Comment by tumashu** [comment]
那可能在这个函数里面过滤更好 pyim-imobjs-create:quanpin
