### ISSUE TITLE
hi-lock 干扰 pyim

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#284]
可以这样重现：
1. (global-hi-lock-mode)
2. 切换到pyim输入法
3. 在行首输入“ni”
4. 按2次backspace
5. 再按“n”

n直接上屏了！

**Comment by QiangF** [comment]
我找到原因了，原来是我的一个设置（在'pyim-terminate-translation后重新设置单独的minibuffer高度）。
请教大师，上面步骤4把用户输入全部删除，此时pyim-terminate-translation是不是没有执行，导致步骤5的时候和我的advice产生干扰。

我的设置如下：

    (advice-add 'pyim-minibuffer-message :around #'my-set-minibuffer-height)
    (advice-add 'pyim-terminate-translation :after #'my-restore-minibuffer-height)

    (defun my-set-minibuffer-height (orig-func &rest args)
        (let ((set-height (and exwm-workspace--minibuffer (= 1 (frame-height exwm-workspace--minibuffer)))))
            (when set-height
              ;; (exwm-workspace--update-minibuffer-height t))
              (set-frame-height exwm-workspace--minibuffer 2))
            (apply orig-func args)))

    (defun my-restore-minibuffer-height ()
              (exwm-workspace--update-minibuffer-height t))

这个设置是为了解决 https://github.com/tumashu/pyim/issues/267

**Comment by tumashu** [comment]
我靠，你玩的好高大上。。。。

**Comment by QiangF** [comment]
啊，这样可以了

    (defun my-restore-minibuffer-height ()
      (when (string-equal pyim-entered "")
              (exwm-workspace--update-minibuffer-height t)))

issue267如果不用单独开一个frame显示minibuffer就少好多麻烦。

**Comment by QiangF** [comment]
大师你能不能改下pyim呢，只加一行，我这里维护设置太麻烦
    (defun pyim-terminate-translation ()
    "Terminate the translation of the current key."

    (when (string-equal pyim-entered "")

    (setq pyim-translating nil)
    (pyim-preview-delete-string)
    (setq pyim-candidates nil)
    (setq pyim-assistant-scheme-enable nil)
    (setq pyim-force-input-chinese nil)
    (when (and (memq pyim-page-tooltip '(posframe child-frame))
                (pyim-posframe-valid-p))
        (posframe-hide pyim-page-tooltip-posframe-buffer))))

**Comment by tumashu** [comment]
给我发个PR吧

**Comment by tumashu** [comment]
如果提交代码，记得发个PR，不建议直接贴例子， 人肉 diff 太耗脑仁  :-)

**Comment by QiangF** [comment]
好的，测试发现只能在我的配置里改。
