### ISSUE TITLE
[重要] 优化词频策略

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#287]
今天发现pyim并不是在每次输入刷新1次候选词列表里的顺序，必须执行

    (pyim-dregcache-update-personal-words t)

是不是担心卡顿，如果是这样能不能单独创建一个变量呢？比如 pyim-dregcache-recent2word
每输入1次就采用 pyim-dregcache-iword2count 更新一下 pyim-dregcache-recent2word 里的词频，
然后：

    ; 用户执行
    (pyim-dregcache-update-personal-words t)
    ; 重置
    (setq pyim-dregcache-recent2word nil)

**Comment by tumashu** [comment]
我记得以前词频调整的策略是： iword第一个词是动态调整，iword后面的词按词频排序，下次启动pyim的时候生效

**Comment by QiangF** [comment]
现在好像不是这样子了

    (defun pyim-candidates-create:quanpin (imobjs scheme-name)
            znabc-words
            pinyin-chars
            personal-words
            common-words)

并且在 pyim-page-select-word 里，单独的一个字都不计词频了

      (unless (member pyim-outcome pyim-candidates)
          (pyim-create-word pyim-outcome))

反复输入1个字都得选，感觉没以前好用了

**Comment by QiangF** [comment]
https://github.com/tumashu/pyim/issues/39

**Comment by tumashu** [comment]
有可能，过年的时候，我花了半个月时间，把 pyim 重构了一次，有可能引入了新bug

**Comment by tumashu** [comment]
我想到的策略是：
1.  如果一个词是新建的，输入这个词后，就自动放到候选词后面
2.  如果一个词已经在候选词列表里面，输入这个词后，就自动就放到第一位
3. 关闭 pyim 的时候，使用词频对 个人词库进行排序，

这种模式的话， 第一个词位，就是当前 session 的临时词位， 不知道这种处理方式合理不合理。

**Comment by tumashu** [comment]
或者三步策略，第一次输入一个词，放到最后，第二次选择这个词，放到第二位，以后输入这个词，直接放到第一位

**Comment by QiangF** [comment]
如果我的理解是正确的，那么
1. 词频只保存在 pyim-dregcache-iword2count
2. 词频通过 pyim-create-word 修改
3. pyim-dregcache-iword2count 只有在 pyim-dregcache-sort-icode2word 使用了

那么要实时更新词频就应该
1. 修改 pyim-create-word，每次修改词频后进行 pyim-dregcache-sort-icode2word， 这样 pyim-dregcache-get-icode2word 下次查到的词顺序就反映了新词频。
2. 修改 pyim-dcache-get，把搜索结果用 pyim-dregcache-iword2count 进行排序，这样就避免了每次修改词频后进行 pyim-dregcache-sort-icode2word。

**Comment by tumashu** [comment]
出了第一个词，pyim目前不会实时更新其它词的词频，都是这次更新，下次使用，因为我认为，如果词频数字很大的时候，一次session几乎不会影响排序

**Comment by tumashu** [comment]
实时排序实现起来不难，但我不知道性能如何

**Comment by tumashu** [comment]
已经添加动态词频调整功能
