### ISSUE TITLE
在小鹤双拼中输入`aj`没有得到`an`

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#288]
在我使用的ibus chinese-pinyin中这是有效的输入.

**Comment by tumashu** [comment]
看看小鹤官方有没有这个，如果有的话，就加上

**Comment by redguardtoo** [comment]
好像官方没有,应该是ibus自己加的.要么还是加上吧. ibus我选的是小鹤, 但是`an`没有匹配项.

![image](https://user-images.githubusercontent.com/184553/61459841-f7e79b80-a9b0-11e9-92af-a9cfc5f0235a.png)
