### ISSUE TITLE
小建议：输入的拼音可以返回修改

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#292]
1. 就是输入了一大串，发现候选词没有想要的，原来拼音有个小错误，能不能返回把错误修改了，比如绑定C-p C-n C-a C-e为在输入的拼音中间移动，M-n M-p以im object快速移动
2. 当用户在拼音中移动时候，只对光标前的进行翻译，（此时可以用空格和数字确认部分候选词）继续往后移动光标，移动前已经确认的拼音不做新的处理，如果往前移动则撤销确认的部分，最终直到拼音全部处理完后空格上屏

目前，比如我要输入：
1. 假设输入完 jinshidundaomeiguo
2. 假设候选里有 金士顿， 我用数字选了 金士顿
3. 我改变主义后面加上niuyue，现在输入的拼音变成 jinshidundaomeiguoniuyue
4. 这时候选竟然还有 金士顿， 我用数字再选了 金士顿 屏幕上竟然有2个 金士顿 （问题出在3, 用户确定 金士顿 后就应该把 jinshidun 从输入里去掉）
5. 现在如果继续删除拼音，删除到jinshidun的时候，一直到最后一个字母，候选词都是 金士顿，应该实时更新候选词

**Comment by QiangF** [comment]
这个功能可以显著提高 长词/长句 输入体验，因为没有它，输入一大堆，没找到候选的，还得全部删除重来，风险太大。

**Comment by tumashu** [comment]
到目前为止，我还没有想到实现的方式，我喜欢短词输入，因为我知道pyim对长句输入支持很差:-)

**Comment by QiangF** [comment]
开始输入时，专门创建一个buffer, 就叫*pyim-entered*,输入完毕把它关了
1. 绑定C-p C-n C-a C-e为在输入的拼音中间移动，M-n M-p以im object快速移动,
2. 其他有效拼音输入同时在*pyim-entered*输入一份
3. 把pyim-entered用 *pyim-entered* 的(buffer-string)代替
这样实现了单一词拼音的修改，充分利用已有的输入(pyim-entered)，不然已有的输入全部作废有点可惜。
