### ISSUE TITLE
请问有没有记录功能。

### ISSUE THREAD

**Issue by awerdx520** [tumashu/pyim#293]
pyim可以记录用户习惯吗，把显示的词组按频率来显示，像搜狗一样。

**Comment by redguardtoo** [comment]
`~/.emacs.d/pyim/dcache/pyim-dregcache-iword2count` 或者 `~/.emacs.d/pyim/dcache/pyim-dhashcache-iword2count` 保存词频。取决于你用`pyim-dregcache` or `pyim-dhashcache`.

@tumashu , 我觉得词频可以用纯文本格式保存，类似于词典格式，并且用户可以指定默认目录。同样原则也适用于个人词：
- 保护用户隐私
- 便于管理（如版本控制）

**Comment by tumashu** [comment]
把dcache的目录更改不就可以了？

**Comment by redguardtoo** [comment]
最好不要存为lisp sexp，一个简单的多行文本便于管理。

**Comment by tumashu** [comment]
这个看后端吧，对于dhashcache，因为都是保存hash，所以当前的设置可以简化代码，对于dregcache,完全可以实现你说的那种格式

**Comment by redguardtoo** [comment]
从用户角度，最好能统一格式。可以保存的时候转换为plain text 格式。载入的时候再转为hashtable 格式。关键是性能怎么样。

例如词频文件可以保存为，
```
开心 9
开箱 4
```

**Comment by tumashu** [comment]
其实dcache本来就是词库缓存，大多数用户不应该关注，他们需要的可能是pyim-export 和 pyim-import

**Comment by redguardtoo** [comment]
export/import也可以，不过最好一步到位，另外我蛮担心自己隐私的，因为我的`.emacs.d`是公开的。

**Comment by QiangF** [comment]
大师看我的配置

    (defun pyim-dregcache-insert-export-content ()
      ;; 在默认情况下，用户选择过的词生成的缓存中存在的词条，
      ;; `pyim-dhashcache-iword2count' 中也一定存在
      (maphash
       #'(lambda (key value)
           (insert (format "%s %s\n" key value)))
       pyim-dregcache-iword2count))

    (defvar personal-wordcount-path)
    (setq personal-wordcount-path "~/.dotfiles/emacs/emacs.d/pyim/personal.pyimc")

    (defun my-pyim-import (file)
      "words are links in org mode, eg [[王八蛋]]" 
      (interactive "FFile path:")
      (let ((temp-file "/tmp/my-temporary-dict"))
        ;; parse file
        (let ((word-list
               (with-temp-buffer
                 (let ((coding-system-for-read 'utf-8-unix))
                   (insert-file-contents file))
                 (org-element-map (org-element-parse-buffer) 'link
                   (lambda (link)
                     ;; (when (string= (org-element-property :type link) "file")
                     (when (org-element-property :type link)
                       (org-element-property :path link)))))))
          (with-temp-file temp-file
            (insert ";;; -*- coding: utf-8-unix -*-\n")
            (insert (string-join word-list "\n"))
            (when (file-writable-p file)
              (write-region (point-min) (point-max) temp-file))))
        (pyim-import temp-file)))

    (defun pyim-pull (&optional file)
      (interactive)
      (let ((file-path (or file personal-wordcount-path)))
      (when (file-exists-p file-path)
        (message "Import %s" file-path)
        (pyim-import file-path))))

    ;; 同步
    (defun pyim-sync ()
      (interactive)
      (when (file-exists-p personal-wordcount-path)
        (pyim-pull))
      (when (pyim-dcache-backend-api "iword2count")
        (pyim-export personal-wordcount-path)))

iword最好还是弄到gitignore里面

**Comment by tumashu** [comment]
```
另外我蛮担心自己隐私的，因为我的.emacs.d是公开的。最好iword开头的缓存可以放在.emacs.d外部
```
我还是觉得你应该更改 pyim-dcache-directory， 将其放到一个安全的地方

**Comment by redguardtoo** [comment]
嗯，这也是个办法。

**Comment by QiangF** [comment]
写了2个用于同步用户词的函数，只保留词，好处是可以方便查看变化的部分，词频变化太频繁。加入iword2count
的时候只导入现有iword2count里没有的词，以加快导入速度。 pyim-dregcache-iword2count 要是纯文本，支持
正则表达式搜索，合并也学就会快一点。

    (defun my-pyim-export ()
      "只保留词，好处是可以方便查看变化的部分，词频变化太频繁"
      (interactive)
      (with-temp-file personal-wordcount-path
        (maphash #'(lambda (key value)
                     (insert (format "%s\n" key)))
                 (symbol-value (pyim-dcache-backend-api "iword2count")))
        ;; sort
        (sort-lines nil (point-min) (point-max))
        (goto-char (point-min))
        (insert ";;; -*- coding: utf-8-unix -*-\n")))

    (defun my-pyim-import (file)
      "从词语文件中导入词条，文件一行一个词，不包含词频信息"
      (interactive "F导入词条相关信息文件: ")
      (declare (indent 0))
      (let ((temp-buffer (generate-new-buffer "*temp-buffer*"))
            (coding-system-for-read 'utf-8-unix)
            (searching-first-duplicate t)
            prev-point)
        (with-current-buffer temp-buffer
          (insert-file-contents file)
          ;; delete encoding specification
          (delete-region 1 (progn (forward-line 1) (point)))
          ;; (message "!%s" (buffer-string))
          (goto-char (point-max))
          (maphash #'(lambda (key value)
                       ;; make sure all word in iword2count are duplicated and will be removed
                       (insert (format "%s\n%s\n" key key)))
                   (symbol-value (pyim-dcache-backend-api "iword2count")))
          (sort-lines nil (point-min) (point-max))
          ;; (message "middle :%s" (buffer-string))
          ;; delete line and its duplicate lines
          (goto-char (point-min))
          (setq prev-point (point))
          (setq prev-line (buffer-substring-no-properties 1 (line-end-position)))
          ;; line-end-position donesn't contain "\n"
          (forward-line 1)
          (while (not (eobp))
            (setq line (buffer-substring-no-properties
                        (line-beginning-position)
                        (line-end-position)))
            (if (string-equal line prev-line)
                (if searching-first-duplicate
                    (progn 
                      ;; delete first and duplicate instance, next line goes up, equivalent to auto forward-line
                      (delete-region prev-point (1+ (line-end-position)))
                      (setq searching-first-duplicate nil))
                  ;; delete the duplicate instance only
                  (progn 
                    (delete-region (line-beginning-position)
                                   (1+ (line-end-position)))))
              (setq prev-point (line-beginning-position))
              (forward-line 1)
              (setq searching-first-duplicate t)
              (setq prev-line line)))
          ;; add words
          (goto-char (point-min))
          (while (not (eobp))
            (let* ((word (car (pyim-dline-parse))))
              (pyim-create-word word nil nil))
            (forward-line 1))
          (unless pyim-prefer-emacs-thread
            (pyim-dcache-save-caches))
          ;; 更新相关的 dcache
          (funcall (pyim-dcache-backend-api "update-personal-words") t)
          (message "pyim: 词条相关信息导入完成！"))
        (and (buffer-live-p temp-buffer)
             (kill-buffer temp-buffer))))

**Comment by redguardtoo** [comment]
可以做成纯文本，这样导入导出就没必要了。如 @tumashu 所说，改一下 `pyim-dcache-directory`就行了。
我甚至觉得可以把`pyim-dregcache-icode2word`和`pyim-dregcache-iword2count`合并成一个文本文件。

**Comment by QiangF** [comment]
但是用户可能有好几台电脑，还需要合并不同电脑上的用户词库。

**Comment by redguardtoo** [comment]
嗯，这倒也是个问题。
