### ISSUE TITLE
添加两个函数

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#294]
(defun pyim-page-select-word-no-addition ()
    "从选词框中选择当前词条，不加入用户词库。
     用于输入某个字需要翻很多页，输入以该字开头的词再删除一个字则不用翻页，这时不需要保存该词"
      (interactive)
      (if (null pyim-candidates)        ; 如果没有选项，输入空格
          (pyim-outcome-handle 'last-char)
        (pyim-outcome-handle 'candidate))
      (pyim-terminate-translation))

    (defun pyim-dregcache-delete-word-1 (word)
    "将中文词条 WORD 从个人词库中删除"
        (let* ((pinyins (pyim-hanzi2pinyin word nil "-" t nil t))) ;使用了多音字校正
          ;; 从个人缓存删除词条
          (dolist (py pinyins)
            (unless (pyim-string-match-p "[^ a-z-]" py)
              (setq pyim-dregcache-icode2word
                    (delete (concat py " " word) pyim-dregcache-icode2word)))))
        ;; 删除对应词条的词频
        (remhash word pyim-dregcache-iword2count))

用户可以这样设置(用use-package)：

     :bind
     (:map pyim-mode-map
     ("C-SPC" . pyim-page-select-word-no-addition))

pull request 太烦琐了，这两个函数跟其它代码每关系，所以直接提issue了

**Comment by redguardtoo** [comment]
`dregcache`部分的代码我可以看一下，其他的得 @tumashu  负责了

**Comment by QiangF** [comment]
第一个的用处：比如有个人叫王潼，潼字得找半天，潼关很快就找到了

**Comment by QiangF** [comment]
另外，由于不能返回修改（https://github.com/tumashu/pyim/issues/292），如果输入5个字，前3个是正确的，我一般是让它上屏然后再删除，如果没有这个功能，就多了一个不想要的词。

**Comment by tumashu** [comment]
按词选字是一个非常有用的功能，我经常使用， 如果能一部到位，那就更好了，比如M-1 选择第一个汉字，M-2 选择第二个汉字， 要是能想到一种简单的范围选择方式，那就更好了
