### ISSUE TITLE
使用 rime 输入法的时候，自动造词没办法使用

### ISSUE THREAD

**Issue by zilongshanren** [tumashu/pyim#295]
Rime输入法支持自动造词和词频顺序调整，使用外部Rime输入法的时候，这些都可以很好的工作，但是在pyim里面无法使用。不知道是liberime没有实现，还是pyim没有适配呢？

**Comment by tumashu** [comment]
基本上 pyim 对 rime 的支持处于停滞状态， liberime 的原开发者可能已经放弃维护 liberime 了，我试着更改了一下 lberime，发现已经超出我的能力。。。。。

**Comment by zilongshanren** [comment]
😂 目前感觉就缺这两个功能，造词和字频排序，更多的功能也不需要了。

**Comment by tumashu** [comment]
有两种方案， 第一种是通过 libeime 来实现这个功能， 这样词频信息就保存到 rime 词库中， 以后和其他rime同步词库可能简单一点， 第二种方案时使用 pyim 的词频和造词机制，实现起来也很简单，唯一的不好处就是和其他 rime 同步词库的话，麻烦一点

**Comment by zilongshanren** [comment]
恩， 最好是通过 liberime来实现，跟外部rime输入法共享字频数据和造词库。

**Comment by tumashu** [comment]
刚刚去 liberime 的gitlab， 好像还在维护， 赞！

**Comment by merrickluo** [comment]
昨天把仓库挪到 GitHub 了，其实关于词频的解决办法就是把选词交给 librime 来做，或者说是pyim在选词后同步给 librime，记得之前瞎改了下 pyim 就是用第一种方式： https://github.com/merrickluo/pyim/pull/1

**Comment by tumashu** [comment]
```
或者说是pyim在选词后同步给 librime
```
这种方式代码可能更简单，因为pyim已经有专门用于 rime 选词的函数，所以工作量就是，
让liberime 提供一个词频调整接口

第一种方式代码太混乱了。。。。

**Comment by tumashu** [comment]
```
(defun pyim-page-select-word:rime ()
  "从选词框中选择当前词条， 专门用于 rime 输入法支持。"
  (interactive)
  (if (null pyim-candidates)  ; 如果没有选项，输入空格
      (progn
        (pyim-outcome-handle 'last-char)
        (pyim-terminate-translation))
    ;; pyim 告诉 liberime 选择其他的词条
    (liberime-select-candidate (- pyim-candidate-position 1))
    (let* ((context (liberime-get-context))
           imobjs)
      (pyim-outcome-handle 'candidate)
      (if (not context)
          (progn
            (unless (member (pyim-outcome-get) pyim-candidates)
              (pyim-create-word (pyim-outcome-get)))
            (pyim-terminate-translation)
            ;; pyim 使用这个 hook 来处理联想词。
            (run-hooks 'pyim-page-select-finish-hook))
        ;; BUG: 默认 liberime 得到的 candidate 是分页的，一页只包含5个词条，
        ;; pyim 需要 liberime 不分页，或者一页包含尽可能多个词。
        (setq pyim-candidates
              (let* ((menu (alist-get 'menu context))
                     (candidates (alist-get 'candidates menu)))
                candidates))
        (setq pyim-candidate-position 1)
        (pyim-preview-refresh)
```

**Comment by merrickluo** [comment]
有点尴尬，我之前理解是用了这个应该librime就会做词频记录这些事了，看起来不是的，印象中也没有调整词频这样的API，感觉得稍微看下librime的实现才行呢。

**Comment by merrick-edmodo** [comment]
https://github.com/rime/librime/issues/319 根据这边的讨论来看，其实用户词频记录是有的，具体本地的情况可以通过查看 `~/.emacs.d/rime/luna_pinyin.userdb` 来检查。我这边看到确实是有内容的，不过由于配置是分开的所以没办法和其他输入法共享确实是个问题，librime 有一个同步词库的功能不过我还没怎么玩懂，到时候研究清楚了可以加到文档里面。

**Comment by merrickluo** [comment]
https://github.com/rime/librime/issues/319 根据这边的讨论来看，其实用户词频记录是有的，具体本地的情况可以通过查看 ~/.emacs.d/rime/luna_pinyin.userdb 来检查。我这边看到确实是有内容的，不过由于配置是分开的所以没办法和其他输入法共享确实是个问题，librime 有一个同步词库的功能不过我还没怎么玩懂，到时候研究清楚了可以加到文档里面。

------
刚才用错帐号，请忽略...

**Comment by tumashu** [comment]
有可能是这种情况，词频调整是需要在 librime 中“选择” 某个词条的， 而 pyim 使用 librime 是直接获取词条列表，所以导致词频不会调整

**Comment by tumashu** [comment]
不对， pyim已经调用了 liberime-select-candidate， 应该是选择了

**Comment by merrickluo** [comment]
恩，是有的，我这边看到 luna_pinyin_userdb 里面是有记录的。

**Comment by datacruiser** [comment]
> 恩，是有的，我这边看到 luna_pinyin_userdb 里面是有记录的。

我发现如果换了一个输入法，比如xiaohe-shuanpin，词频并不会进行调整。

**Comment by tumashu** [comment]
我今天在debian10上面测试了一下，好像支持词频调整吧？ 难道我出现幻觉了？

**Comment by QiangF** [comment]
最新的好像支持用戶詞庫了，最好能自動和其他pyim backend整合就好了。

**Comment by QiangF** [comment]
liberime 会导致一个问题，就是在 Emacs 中输入中文时，词库跟系统输入法不一致， 需要sync. 默认情况下 liberime 的 installation.yaml 在 $HOME/.emacs.d/rime/installation.yaml，用户只需要在里面添加 sync_dir ，就可以使用 liberime-config 提供的 (liberime-sync) 方法进行同步了。

如果直接用EXWM， 应该不存在同步的问题。

**Comment by QiangF** [comment]
sync dir 里面的同步文件是文本文档，
词条格式是：
wang jiu dan 	王久蛋	c=1 d=1 t=24
不知道 c d t 分别代表啥

**Comment by tumashu** [comment]
这个issue好像可以关闭了。
