### ISSUE TITLE
用 posframe 显示 pyim-page-tooltip 某些情况下字母直接上屏

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#297]
posframe 有时候会直接拼音上屏，比如按w，删除，然后按w，w直接上屏输入了。popup 就没有这个问题。字母直接上屏遇到很多次，这个我可以重复。这是我用的最简配置：

    (require 'package)
    (setq package-enable-at-startup nil
        package-user-dir "~/.emacs.d/elpa/")
    (add-to-list 'load-path "/home/q/pyim")
    (add-to-list 'load-path "/home/q/.dotfiles/emacs/emacs.d/site-lisp/popup")
    (add-to-list 'load-path "/home/q/.emacs.d/elpa/posframe-20190608.343")
    (package-initialize)

    (require 'evil)
    (evil-mode 1)

    (require 'posframe)
    (require 'pyim)
    (require 'pyim-dhashcache)
    (setq pyim-dcache-backend 'pyim-dregcache
        default-input-method "pyim")
    (setq pyim-page-tooltip 'posframe)
    (setq pyim-prefer-emacs-thread t)
    (setq pyim-default-pinyin-scheme 'quanpin)
    (defun my-toggle-input-method ()
        (interactive)
        (if current-input-method (deactivate-input-method)
        (activate-input-method "pyim")))
    (setq pyim-dicts
        '((:name "base"
        :file "~/.dotfiles/emacs/emacs.d/pyim/pyim-basedict.pyim"
        :coding utf-8-unix
        :dict-type pinyin-dict)))

    (when window-system
        (progn (tool-bar-mode -1)
            (toggle-frame-fullscreen)
            (scroll-bar-mode -1)
            (menu-bar-mode -1)
            (mouse-wheel-mode t)))

**Comment by tumashu** [comment]
我这边试不出来。

**Comment by tumashu** [comment]
这个问题我这边重现不了，所以关闭了
