### ISSUE TITLE
pyim-convert-string-at-point遇到－前面的英文也会转换为中文

### ISSUE THREAD

**Issue by ab9986** [tumashu/pyim#304]
我输入good-ni,调用pyim-convert-string-at-point，发现goodni全部转成中文，但实际上只要转换-后面ni为中文即可，所以我对pyim-convert-string-at-point做了修改，将-进行过滤，帮忙看看是否可行
;; +++ pyim.el	(working copy)
;;      (cond ((string-match
;;              ;; 创建一个 regexp, 用于提取出光标处一个适合
;;              ;; 转换的字符串。
;; -            (format "[%s]+ *$"
;; -                    (cl-delete-duplicates
;; -                     (concat first-chars rest-chars "'-")))
;; +            (replace-regexp-in-string "-" "" (format "[%s]+ *$"
;; +                                                     (cl-delete-duplicates
;; +                                                      (concat first-chars rest-chars "'-")))) 
;;              string)
;;             (setq code
;;                   ;; 一些编程语言使用单引号 ' 做为字符串的标记，这里需要特殊处理。

**Comment by tumashu** [comment]
这样做有点hack，不过个人用还是可以的，产生这个问题的根本原因是，pyim里面允许拼音中有-号

**Comment by ab9986** [comment]
我试一下，输入中文时，无法输入-，只是看到词典pyim-basedict.pyim中用-进行分割拼英例如：ren-ran。另外我用过rg进行搜索词典pyim-basedict.pyim，全词匹配很快，所以想pyim后端用rg匹配取词，这样emacs内存占用大问题可以解决。

**Comment by tumashu** [comment]
(quanpin
     :document "全拼输入法方案（不可删除）。"
     :class quanpin
     :first-chars "abcdefghijklmnopqrstuwxyz"
     :rest-chars "vmpfwckzyjqdltxuognbhsrei'-a"
:prefer-trigger-chars "v")

是这个地方设置的缘故，

**Comment by tumashu** [comment]
最近有朋友添加了一个pyim-dregcache后端，内存消耗很小，你可以试试

(setq pyim-dcache-backend 'pyim-dregcache)

**Comment by ab9986** [comment]
(setq pyim-dcache-backend 'pyim-dregcache) 非常不错
另外:rest-chars "vmpfwckzyjqdltxuognbhsrei'-a" 作用不大
pyim.el只有pyim-input-chinese-p和pyim-convert-string-at-point用到
