### ISSUE TITLE
更新后出现问题

### ISSUE THREAD

**Issue by awerdx520** [tumashu/pyim#305]
我昨天更新pyim包过后，出现如果按下退格键会消掉把两个字母
![深度截图_选择区域_20190806203029](https://user-images.githubusercontent.com/15448027/62539965-0d9e0180-b889-11e9-9506-99e61b5305dd.png)
大于两个正常。在lisp中输入，光标前是汉字字符，后面还是英文，只能使用 `M-j` 转换，之前是正常的。配置使用的是开发者给出的。
![深度截图_选择区域_20190806205932](https://user-images.githubusercontent.com/15448027/62541815-1f81a380-b88d-11e9-960f-861c21aab7b4.png)

**Comment by tumashu** [comment]
有可能，前几天添加了输入编辑功能，有可能不小心引入了bug

**Comment by tumashu** [comment]
emacs-lisp 模式激活之后， 只能在注释和字符串里面输入中文

**Comment by awerdx520** [comment]
修复过后正常，melpa 更新是延迟吗？

**Comment by tumashu** [comment]
4个小时的延迟吧

**Comment by awerdx520** [comment]
又出现了新的bug，当我按退格键删除字母，pyim卡死，提示错误，不定时出现。设置（setq debug-no-error t）没又显示任何信息
![深度截图_选择区域_20190807123300](https://user-images.githubusercontent.com/15448027/62595097-82b41a00-b90f-11e9-8195-122a5a0ecfe6.png)

**Comment by tumashu** [comment]
试试吧，应该修复了

**Comment by awerdx520** [comment]
虽然不会报错了 但是还是不能全部删除
![深度截图_选择区域_20190809205211](https://user-images.githubusercontent.com/15448027/62780161-9ade9180-bae7-11e9-9401-22cd3f47b2a5.png)

**Comment by tumashu** [comment]
这是正常的，因为sf这两个字符在光标后面，pyim有向前删除和向后删除两个命令
