### ISSUE TITLE
pyim-minibuffer-message 中的第一句 (message nil) 是不是多余

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#310]
主要是这一句干扰awesome-tray，没有它这个advice不执行

    (defun awesome-tray-message-advice (old-message &rest arguments)
    (condition-case nil
            (if awesome-tray-active-p
            (progn (cond
                    ;; Just flush tray info if message string is empty.
                    ((not (car arguments))
                        (apply old-message arguments)
                        (awesome-tray-flush-info))
                    ;; Otherwise, wrap message string with tray info.
                    (t
                        (apply old-message "%s" (cons (awesome-tray-get-echo-format-string (apply 'format arguments)) '()))))
                    (when (and exwm_enable (exwm-workspace--minibuffer-own-frame-p))
                    (exwm-workspace--update-minibuffer-height t)))
            (apply old-message arguments))
        (apply old-message arguments)))

**Comment by tumashu** [comment]
不知道，这个是从 eim 继承过来的代码，不知道这句话有什么特殊的作用

**Comment by QiangF** [comment]
我把它删除了，加了一行 (inhibit-message t)
好像没甚么问题

    (defun pyim-minibuffer-message (string)
    (let ((inhibit-quit t)
          (inhibit-message t)
            point-1)
        (save-excursion
        (insert string)
        (setq point-1 (point)))
        (sit-for 1000000)
        (delete-region (point) point-1)
        (when quit-flag
        (setq quit-flag nil
                unread-command-events '(7)))))

**Comment by tumashu** [comment]
：-）

**Comment by tumashu** [comment]
可以删除的话就提个 pr

**Comment by QiangF** [comment]
不太确定，感觉pyim太复杂了，我弄了一个精简版的，感觉台湾人虽然娘娘腔，输入法做的还真不错，大师可以试试：
https://gist.github.com/QiangF/d726722d4ceee0cd31fc59163ae2a5bd

**Comment by tumashu** [comment]
以前见过你发链接，不过我这边由于某种原因，打不开。。。。汗，强烈建议做成melpa 包

**Comment by QiangF** [comment]
关键我没那个水平，大部分都是抄你的，呵呵

**Comment by tumashu** [comment]
抄就对了，抄的多说明代码有用。。。
