### ISSUE TITLE
eww 模式下不能输入中文

### ISSUE THREAD

**Issue by awerdx520** [tumashu/pyim#312]
我使用的时开发者提供的默认配置，不能在搜索框了输入中文，按下 `Ctrl-\` 可以启动输入法。但是`M-j`不能将英文转换。其它模式模式显示正常，message buffer 无任何信息。
![image](https://user-images.githubusercontent.com/15448027/63139213-0ce73700-c010-11e9-810b-566abb2509cc.png)

**Comment by rateyu** [comment]
同问

**Comment by LeoGitHuber** [comment]
请问题主是如何解决这个问题的？
