### ISSUE TITLE
小鹤双拼打不出"况"字,但是可以打出"黄"字

### ISSUE THREAD

**Issue by ggufeng** [tumashu/pyim#313]
小鹤双拼中l对应uang.
但是输入kl只能得到kl作为反馈结果,所以打不出任何发音为kuang的字.
可是输入hl就能得到"黄","皇"等等作为反馈结果.

**Comment by redguardtoo** [comment]
`C-h v pyim-backend`?

**Comment by redguardtoo** [comment]
不好意思，之前做双拼优化时把kuang误删除了。现在我把所有排除模式都在basedict验证了一遍。应该不会出现这个问题了。

8e3bae5 cannot input "kuang" in shuangpin mode (Chen Bin)
