### ISSUE TITLE
关于用户词库的几个问题

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#319]
用户词库是输入法的灵魂，离开我的词库，再好的输入法都是别人的。下面3个小建议：

1. 保存iword2count hash table时保存1个备份，当加载出错时（odd number of item in hashtable）加载备份
2. 定期将用户词语转换成pyim格式的词典并按词频调序，同时删除词频文件（可以使词频文件很小，词频只对编码相同的词有用，数字一直增长没有意义）
3. create word时搜索词典，词典有则只保存词频，不对多音字进行排列组合（尽量避免污染用户词典）

**Comment by tumashu** [comment]
```
保存iword2count hash table时保存1个备份，当加载出错时（odd number of item in hashtable）加载备份
```
不知道为什么你会经常遇到这种情况，我这边只遇到过一次，这个可以研究研究，如果不需要太复杂的代码，可以考虑。

···
定期将用户词语转换成pyim格式的词典并按词频调序，同时删除词频文件（可以使词频文件很小，词频只对编码相同的词有用，数字一直增长没有意义）
···
暂时不做考虑，pyim现有的模式更简单

```
create word时搜索词典，词典有则只保存词频，不对多音字进行排列组合（尽量避免污染用户词典）
```
我个人感觉，个人词库污染对于输入而言，不是一个大问题，创建新词比污染词库更重要，毕竟我们是为了方便输入，而不是为了词库好看

**Comment by QiangF** [comment]
嗯 用exwm就是经常kill emacs，然后就不知道怎么hash table坏了

**Comment by ab9986** [comment]
hash table坏了 ，是不遇到我一样问题： 载入词库报：(wrong-type-argument hash-table-p nil)
可以看看#333，这个问题已经解决，用最新代码试一下

**Comment by tumashu** [comment]
@ab9986 QiangF 遇到的问题和你遇到的不太一样：-）

**Comment by QiangF** [comment]
如果有备份，可以忽略hash table错误

   (defun pyim-dcache-get-value-from-file (file)
     "读取保存到 FILE 里面的 value."
     (when (file-exists-p file)
       (condition-case nil
           (with-temp-buffer
             (insert-file-contents file)
             (eval (read (current-buffer))))
         (error nil))))
