### ISSUE TITLE
计划启用lexical-binding？

### ISSUE THREAD

**Issue by cireu** [tumashu/pyim#324]

**Comment by cireu** [comment]
On Fri, 13 Sep 2019 13:22:08 +0800,
tumashu wrote:
> 
> [1  <text/plain; UTF-8 (base64)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
> 没测试过，等抽时间测试一下
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

其实有兴趣可以搞个单元测试, 以前想给pyim弄一个, 不过没什么头绪测试这种带UI的东
西...(或者只测试非UI部分?)

**Comment by tumashu** [comment]
确实，我也想过，但想到又有界面，内部又有许多依托全局变量的状态切换，我就打退堂鼓了

**Comment by tumashu** [comment]
已经启用
