### ISSUE TITLE
不可预测的字母上屏

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#326]
录了一个视频，主要是重复 “输入 s 和 删除前一个字符”，有时s可以显示候选字，有时就直接上屏（org-self-insert）了，这种直接上屏主要发生在删除操作后面。

![Peek 2019-09-24 10-43](https://user-images.githubusercontent.com/8192731/65477461-f8247b80-deb8-11e9-957b-20fab4f21c01.gif)

**Comment by QiangF** [comment]
这样设置同样会出现

    (setq-default pyim-english-input-switch-functions nil)

**Comment by QiangF** [comment]
字母直接上屏的时候， pyim-input-method is not called.

**Comment by tumashu** [comment]
不应该出现这种情况， 如果pyim启动之后， 按理说 pyim-input-method 会调用， emacs -q 可以重现么？

**Comment by QiangF** [comment]
好像就是在mini-modeline-mode 启用后，key event 没有被input method function 处理，直接被弄成binding 执行command 了。
我试着增加一个minor mode ，然后把所有字母键绑定到 input method function, input method function 输出英文时造成死循环。 
暂时give up 了。

**Comment by QiangF** [comment]
我觉得是这个原因
https://github.com/ch11ng/exwm/issues/705
