### ISSUE TITLE
使用rime没法翻页了

### ISSUE THREAD

**Issue by zedhugh** [tumashu/pyim#331]
如果候选词超过5个，就会显示不出来
而且始终显示只有1页
已经按照配置说明，把 “menu/page_size"设置成了100了

**Comment by zedhugh** [comment]
仔细检查了一下，是yaml文件里面有拼写错误，现在已经修复了

**Comment by tumashu** [comment]
我靠，你们rime用的听嘚啊，我这边连编译还没搞定:-{

**Comment by zedhugh** [comment]
用的是 `gentoo` ，编译很方便，而且这个应该编译好了就可以在所有linux发行版通用了吧

另外，`feat-config` 这个分支里面已经实现了设置 `menu/page_size` 的功能了

但我看设置结果就是写到`default.custom.yaml`这个文件里面的
