### ISSUE TITLE
载入词库报：(wrong-type-argument hash-table-p nil)

### ISSUE THREAD

**Issue by ab9986** [tumashu/pyim#333]
最近启动emacs经常报：(wrong-type-argument hash-table-p nil)
后在启动emacs命令中增加--debug-init，报如下错误：
`Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("代" nil)
  #f(compiled-function (a b) #<bytecode 0x2b617d9>)("代" "大")
  sort(("大") #f(compiled-function (a b) #<bytecode 0x2b617d9>))
  pyim-dregcache-sort-words(("大"))
  pyim-dregcache-sort-icode2word()
  pyim-dregcache-update-personal-words(t)
  pyim-dregcache-init-variables()
  apply(pyim-dregcache-init-variables nil)
  pyim-dcache-call-api(init-variables)
  pyim-dcache-init-variables()
  pyim-start("pyim" nil t t nil)
  pyim-restart-1(t)
  (progn (pyim-restart-1 t))
  (if (display-graphic-p) (progn (pyim-restart-1 t)))
  eval-buffer(#<buffer  *load*-394376> nil "d:/ab9986/home/.emacs.d/lisp/emacs-config.el" nil t)  ; Reading at buffer position 25052
  load-with-code-conversion("d:/ab9986/home/.emacs.d/lisp/emacs-config.el" "d:/ab9986/home/.emacs.d/lisp/emacs-config.el" nil t)
  require(emacs-config)
  (if (file-exists-p emacs-config-el-path) (require (quote emacs-config)) (progn (modify-coding-system-alist (quote file) "\\.org\\'" (quote utf-8)) (require (quote org-install)) (require (quote ob-tangle)) (org-babel-load-file emacs-config-org-path) (byte-compile-file emacs-config-el-path)))
  eval-buffer(#<buffer  *load*> nil "d:/ab9986/home/.emacs.d/init.el" nil t)  ; Reading at buffer position 1377
  load-with-code-conversion("d:/ab9986/home/.emacs.d/init.el" "d:/ab9986/home/.emacs.d/init.el" t t)
  load("d:/ab9986/home/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000baab9>)()
  command-line()
  normal-top-level()
`
附件有pyim dcache.zip

[dcache.zip](https://github.com/tumashu/pyim/files/3777074/dcache.zip)

**Comment by tumashu** [comment]
你的dcache出问题了，建议将其删除，重新建立

在 2019-10-28 12:07:34，Tommy <notifications@github.com> 写道：


最近启动emacs经常报：(wrong-type-argument hash-table-p nil)
后在启动emacs命令中增加--debug-init，报如下错误：
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil) gethash("代" nil) #f(compiled-function (a b) #<bytecode 0x2b617d9>)("代" "大") sort(("大") #f(compiled-function (a b) #<bytecode 0x2b617d9>)) pyim-dregcache-sort-words(("大")) pyim-dregcache-sort-icode2word() pyim-dregcache-update-personal-words(t) pyim-dregcache-init-variables() apply(pyim-dregcache-init-variables nil) pyim-dcache-call-api(init-variables) pyim-dcache-init-variables() pyim-start("pyim" nil t t nil) pyim-restart-1(t) (progn (pyim-restart-1 t)) (if (display-graphic-p) (progn (pyim-restart-1 t))) eval-buffer(#<buffer *load*-394376> nil "d:/ab9986/home/.emacs.d/lisp/emacs-config.el" nil t) ; Reading at buffer position 25052 load-with-code-conversion("d:/ab9986/home/.emacs.d/lisp/emacs-config.el" "d:/ab9986/home/.emacs.d/lisp/emacs-config.el" nil t) require(emacs-config) (if (file-exists-p emacs-config-el-path) (require (quote emacs-config)) (progn (modify-coding-system-alist (quote file) "\\.org\\'" (quote utf-8)) (require (quote org-install)) (require (quote ob-tangle)) (org-babel-load-file emacs-config-org-path) (byte-compile-file emacs-config-el-path))) eval-buffer(#<buffer *load*> nil "d:/ab9986/home/.emacs.d/init.el" nil t) ; Reading at buffer position 1377 load-with-code-conversion("d:/ab9986/home/.emacs.d/init.el" "d:/ab9986/home/.emacs.d/init.el" t t) load("d:/ab9986/home/.emacs.d/init" t t) #f(compiled-function () #<bytecode 0x1000baab9>)() command-line() normal-top-level()
附件有pyim dcache.zip

dcache.zip

**Comment by ab9986** [comment]
跟踪了代码，原因初步找到：
(defun pyim-dregcache-init-variables ()
  "初始化 cache 缓存相关变量."
  (unless pyim-dregcache-icode2word
    (pyim-dregcache-update-personal-words t))
  (pyim-dcache-set-variable
   'pyim-dregcache-iword2count
   nil
   ;; dregcache 引擎也需要词频信息，第一次使用 dregcache 引擎的时候，
   ;; 自动导入 dhashcache 引擎的词频信息，以后两个引擎的词频信息就
   ;; 完全分开了。
   (pyim-dcache-get-variable 'pyim-dhashcache-iword2count)))
pyim-dregcache.el 中方法 pyim-dregcache-init-variables 存在bug。
  (unless pyim-dregcache-icode2word
    (pyim-dregcache-update-personal-words t)) 会用到pyim-dregcache-iword2count变量，但是初始化却在后，将该条语句放后就可以解决报错(wrong-type-argument hash-table-p nil) 。
修改后如下：
(defun pyim-dregcache-init-variables ()
  "初始化 cache 缓存相关变量."
  (pyim-dcache-set-variable
   'pyim-dregcache-iword2count
   nil
   ;; dregcache 引擎也需要词频信息，第一次使用 dregcache 引擎的时候，
   ;; 自动导入 dhashcache 引擎的词频信息，以后两个引擎的词频信息就
   ;; 完全分开了。
   (pyim-dcache-get-variable 'pyim-dhashcache-iword2count))
   (unless pyim-dregcache-icode2word
    (pyim-dregcache-update-personal-words t)))

**Comment by tumashu** [comment]
Fixed, thanks!
