### ISSUE TITLE
rime 翻页后按数字键选择文字，结果其他字上屏

### ISSUE THREAD

**Issue by RenWenshan** [tumashu/pyim#336]
有在 emacs-china 上问过，就不重复问题本身了，详见：https://emacs-china.org/t/pyim-rime/11077

今天 emacs -q 重现了问题，也试了基本的 rime 全拼输入法：
```elisp
(liberime-select-schema "luna_pinyin_simp")
(setq pyim-default-schema 'rime)
```
也是同样的问题。

**Comment by tumashu** [comment]
感觉很诡异，按理说不应该出现这种问题，我这边暂时无法编译 liberime， 没法测试  :-(

**Comment by tumashu** [comment]
我今天在debian10上面测试了一下，没发现这种情况呀？

**Comment by RenWenshan** [comment]
我发现如果用 +/-翻页再选就没事儿，如果一直按 C-n 翻到了下一页，再选就会有问题，你可以试一下，但目前不影响我使用了

**Comment by tumashu** [comment]
我这边用C-n也好像没啥问题

**Comment by tumashu** [comment]
应该修复了。
