### ISSUE TITLE
pyim-cregexp-build-1 支持双拼

### ISSUE THREAD

**Issue by 275761919** [tumashu/pyim#337]
支持ivy的拼音搜索很好用
但是 pyim-cregexp-build-1 目前好像还不支持双拼

**Comment by tumashu** [comment]
恩，暂时不支持，因为我不用双拼，而拼音搜索的时候是支持首字母搜索的，比如 nh 搜索 你好，暂时没有动力搞

**Comment by xlshiz** [comment]
我fork了[pinyinlib.el](https://github.com/xlshiz/pinyinlib.el/blob/master/pinyinlib.el)，修订了一个支持小鹤双拼的方案。不然每次用都需要增加额外的脑负担。

**Comment by tumashu** [comment]
我刚刚看了一下 pyim-cregexp-build-1 的代码，发现它好像支持双拼，我估计是有人提交过 pr， 我合并了，不过不支持繁体。

**Comment by tumashu** [comment]
```
(setq pyim-default-scheme 'xiaohe-shuangpin)
(pyim-cregexp-build-1 "nihc")
```
```
"\\(?:nihc\\|[你拟尼呢泥妳妮腻逆倪昵匿霓溺年念粘廿捻黏碾蔫撵娘酿鸟尿嬲脲袅溺捏聂涅镍孽您宁凝拧柠甯佞牛妞扭纽钮拗忸][好号浩豪耗郝昊皓毫灏]\\)"
```
