### ISSUE TITLE
关于中英文切换方式，可以输入两个空格来切换吗？

### ISSUE THREAD

**Issue by toure00** [tumashu/pyim#338]
我的想法是这样的，如果在输入的时候，敲两个空格，就自动切换输入法，并且删除其中一个空格，这样一来，中英文既可以用空格隔开，还可以比较流畅的切换输入法，您觉得这个想法可行吗？好实现吗？

**Comment by tumashu** [comment]
应该可以，自己写一个探针函数就可以了

**Comment by tumashu** [comment]
我日常使用的模式是，一个空格后切换到英文输入，

**Comment by toure00** [comment]
我是觉得有时会输入两个单词，或者一句单词，用一个空格切换的话，那些场景就不好用了

**Comment by toure00** [comment]
实际感受了一下 一个空格后切换到英文输入 ，很舒服，混合输入需要输两个单词或一句话的情况很少，                 
```
(pyim-probe-auto-english)
```
这个探针很好用
