### ISSUE TITLE
librime 五笔不能自动上屏

### ISSUE THREAD

**Issue by driftcrow** [tumashu/pyim#340]
使用librime后感觉很流畅，但是五笔不能自动上屏。

比如：“没有”的五笔码是 imde ,输入前三个码 imd 时出现了“没有”和其他候选字词，但输入第四码e时，这时候 *没有* 应该是唯一候选词自动上屏，但是librime中不但没有上屏，而且候选区变为输入码imde了，“没有”这个词都没有了。这样要输入 **没有** 这个词的时候就只能输入 imd 然后在候选区选 3选择

**Comment by tumashu** [comment]
你首先要关闭输入法自身的自动选择功能，好让 pyim 捕获词条

```
patch:
     "menu/page_size": 100
     "speller/auto_select": false
     "speller/auto_select_unique_candidate": false
```

**Comment by tumashu** [comment]
剩下的自动选择功能，就和这个 https://github.com/tumashu/pyim/issues/317 类似了

**Comment by driftcrow** [comment]
果然如此，太好 了，谢谢 👍 
搜索过竟然没看见前面的ISSUES ，惭愧
现在就希望能解决 evil-escape 的问题了 #260

**Comment by driftcrow** [comment]
哦，现在的情况是没有自动上屏，但是手工 上屏没有问题。至少没有出现唯一候选字词时转为输入码的现象。对我来说习惯手工上屏，所以问题不大
