### ISSUE TITLE
straight.el方式下载的pyim 状态栏会乱码，就是显示当前输入法(灵通U)的地方会这样显示

### ISSUE THREAD

**Issue by keke-cute** [tumashu/pyim#341]
![2020-01-05-162606_1920x1080_scrot](https://user-images.githubusercontent.com/37539103/71777432-dc159780-2fda-11ea-86bf-f0d12329b803.png)

**Comment by keke-cute** [comment]
使用melpa 源正常

**Comment by tumashu** [comment]
这个感觉像straight.el的问题吧？

**Comment by keke-cute** [comment]
使用(setq pyim-title "xxx")已解决

**Comment by tumashu** [comment]
😂😂😂

**Comment by loyalpartner** [comment]
> 使用(setq pyim-title "xxx")已解决

我也遇到了这个问题，设置 pyim-title 后，会显示正常，但是如果你用 evil 从 insert 切换到 normal 这个问题又出现了，再次切回 insert 模式，显示又正常。问题变成了 在evil 的normal 模式显示这个乱码

**Comment by keke-cute** [comment]
> > 使用(setq pyim-title "xxx")已解决
> 
> 我也遇到了这个问题，设置 pyim-title 后，会显示正常，但是如果你用 evil 从 insert 切换到 normal 这个问题又出现了，再次切回 insert 模式，显示又正常。问题变成了 在evil 的normal 模式显示这个乱码

好像要把这个配置放在evil之前

**Comment by loyalpartner** [comment]
> > > 使用(setq pyim-title "xxx")已解决
> > 
> > 
> > 我也遇到了这个问题，设置 pyim-title 后，会显示正常，但是如果你用 evil 从 insert 切换到 normal 这个问题又出现了，再次切回 insert 模式，显示又正常。问题变成了 在evil 的normal 模式显示这个乱码
> 
> 好像要把这个配置放在evil之前，你多试试，是载入顺序问题

嗯，我试着你的方法，现在可以了。
我发现出现这个问题的根源和文件 straight/build/pyim/pyim-autoload.el 有关，我把这个文件删除，也modeline 也正常。

**Comment by tumashu** [comment]
默认使用 PYIM 了， 这样就不会出现乱码了 :-)
