### ISSUE TITLE
如何配置不同的 mode 使用不同的探针规则

### ISSUE THREAD

**Issue by SteamedFish** [tumashu/pyim#342]
我希望 prog-mode 和 text-mode 使用不同的探针规则。因此尝试在 `prog-mode-hook` 和 `text-mode-hook` 中设置不同的 `(setq pyim-english-input-switch-functions)` 值。

但是 `pyim-start` 和 `pyim-inactivate` 时会重置所有的 local variable 导致设置失败。

不知道每次重置 local variable 的原因是什么，我应该如何实现 buffer 级别的探针设置？

我现在使用以下代码可以实现我想要的逻辑，但是不确定会不会引发什么 bug。

```lisp
(setq pyim-local-variable-list (delete 'pyim-english-input-switch-functions pyim-local-variable-list))
```

**Comment by tumashu** [comment]
一个简单的办法就是，编写一个大探针作为代理

**Comment by tumashu** [comment]
至于能不能buffer 化，我觉得应该可以，只不过这样设置探针就稍微啰嗦了。。。

**Comment by SteamedFish** [comment]
我比较好奇 pyim 每次激活的时候都要重置 local variable 的原因是什么（这个原因关系到我现在这样设置变量 buffer 化会不会出现问题），如果不重置 local variable 实际上不会出现问题，我就保留我现在的设置。

编写一个大探针的问题是，我需要在很多地方设置不同的探针，我更希望设置探针的操作和这个 mode 的其他设置放置在一起（放置在这个 mode 的 `use-package` 下面），这样看起来更舒服一些。

**Comment by tumashu** [comment]
```
我比较好奇 pyim 每次激活的时候都要重置 local variable 的原因是什么
```
1. 继承之 emacs-eim, 
2. 可能这样处理不容易出现一些稀奇古怪的边界事件，粗暴但是简单 :-)

**Comment by tumashu** [comment]
至于     pyim-english-input-switch-functions 能不能设置全局变量，其实我感觉可以，但没有试过， pyim内部交互有时候我也头晕

**Comment by SteamedFish** [comment]
明白了，我先按我现在的代码试试，看看会不会出现什么问题

**Comment by SteamedFish** [comment]
用了一段时间，没有发现把 `pyim-english-input-switch-functions` 从 `pyim-local-variable-list` 去掉会导致什么问题。

**Comment by tumashu** [comment]
ok
