### ISSUE TITLE
通过配置来隐藏pyim的message输出

### ISSUE THREAD

**Issue by samsonwang** [tumashu/pyim#344]
在pyim初始化时会向message输入一些信息。
是否可以考虑通过增加一个配置项使pyim静默初始化，类似于 [这样](https://github.com/samsonwang/dot-emacs/blob/af6353443761abfa8756ac65f86058beae980e0c/site-lisp/idle-require/idle-require.el#L96-L98) 。

**Comment by tumashu** [comment]
感觉好像没有必要，message 信息有时候很重要，特别是 pyim 需要进行某种不兼容升级的时候。

**Comment by samsonwang** [comment]
可以考虑异常信息留在message中，正常的加载信息可以通过配置隐藏。
