### ISSUE TITLE
关于 rime 后端3个问题 

### ISSUE THREAD

**Issue by QiangF** [tumashu/pyim#345]
在 (setq pyim-default-scheme 'rime) 的情况下：

1. 无法输入以 “/” 开头的表情符号 https://github.com/zYeoman/Rime/blob/master/luna_pinyin.extended/symbols.yaml
2. 无法输入大写字母开头英文单词 如 Bible
3. pyim-translate-trigger-char 能不能设为 \

我的定制文件
https://gist.github.com/QiangF/7b78e5c23bee6f3af979e0b420641cc6

**Comment by tumashu** [comment]
可能你需要自定义一个 scheme， 然后吧那几个字符添加到 first-chars
```
     :first-chars "abcdefghjklmnopqrstwxyz"
     :rest-chars "vmpfwckzyjqdltxuognbhsrei'-a"

```

**Comment by tumashu** [comment]
你那个定制文件我看不见，qiang你懂得

**Comment by QiangF** [comment]
我自己改写了一个，基本不存在这些问题了。
https://gist.github.com/QiangF/7673e50c837c72cd63c120b2633aec87
