### ISSUE TITLE
新安装五笔没成功

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#348]
切换到中文输入后，输入任意字符出错。（如输入了"j"）开启(setq debug-on-error t)后提示如下：
```
Debugger entered--Lisp error: (void-function string-empty-p)
  string-empty-p("j")
  #f(compiled-function (x) #<bytecode 0x4b87a1>)("j")
  mapc(#f(compiled-function (x) #<bytecode 0x4b87a1>) ("j"))
  pyim-imobjs-create:xingma("j" wubi)
  pyim-imobjs-create("j" wubi)
  pyim-entered-refresh-1()
  pyim-entered-refresh()
  pyim-self-insert-command()
  funcall-interactively(pyim-self-insert-command)
  call-interactively(pyim-self-insert-command)
  pyim-start-translation(106)
  pyim-input-method(106)
```
全新安装emacs、重新安装pyim时log如下面两个文件[一个是使用(package-initialize)安装、一个手动安装]
[compile-log2.log](https://github.com/tumashu/pyim/files/4164144/compile-log2.log)
[compile-log.log](https://github.com/tumashu/pyim/files/4164145/compile-log.log)

**Comment by yefeiyu** [comment]
.emacs文件仅使用了下面三行配置：

```


(require 'pyim)
(setq default-input-method "pyim")
(setq pyim-default-scheme 'wubi)
(setq debug-on-error t)
```

**Comment by cpleft** [comment]
我也是，应该是五笔这个包的问题吧

**Comment by tumashu** [comment]
已经更新，试试

**Comment by yefeiyu** [comment]
非常感谢，问题解决了。
多说一点不解的：
1、若写为(set-language-environment 'utf-8)，状态栏"灵通"二字出不来，只出现一个"m
"，只能输入字母。   
2、若写上(set-language-environment 'chinese-gbk)   这行，状态栏很奇怪的出现的是"拼符"字样，输入拼音；
3、去掉这行，新版本已正常。

**Comment by tumashu** [comment]
(setq-default default-input-method "pyim") 试试
