### ISSUE TITLE
export个人词典时排除单字词

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#351]
@tumashu 你能否看一下，提交代码时我搞错repo了，以为是提交到我个人clone的项目，结果直接提交到这里了。不好意思。

caf0319 exclude single char word when exporting personal dictionary (Chen Bin)

**Comment by tumashu** [comment]
如果运行正常，就ok

**Comment by redguardtoo** [comment]
测了`M-x pyim-export-personal-words`， 没什么问题。

**Comment by tumashu** [comment]
那就没事
