### ISSUE TITLE
(setq pyim-page-style 'two-lines) has no effect

### ISSUE THREAD

**Issue by vjohansen** [tumashu/pyim#352]
the default is one line. i tried the to other settings

(setq pyim-page-style 'two-lines)

did not have any effect. it looked the sameas the one-line

the 'vertical worked as expected

 pyim               20200221.153  installed             A Chinese input method support quanpin, shuangpin, wubi and cangjie.

**Comment by tumashu** [comment]
默认是 two lines

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/75431424-cf347500-5987-11ea-87a7-94a72e845780.png)
this is one-line
