### ISSUE TITLE
rime后端，选择部分词后，剩下的拼音显示错误

### ISSUE THREAD

**Issue by xlshiz** [tumashu/pyim#355]
我使用最新版本的pyim+rime，输入方案是小鹤双拼，输入`wo mf dv`（全拼`wo men dui`）显示：
![１](https://user-images.githubusercontent.com/4076325/75638558-625efa80-5c67-11ea-828a-33035a6e96a3.png)
选择`我们`后显示：
![２](https://user-images.githubusercontent.com/4076325/75638585-87536d80-5c67-11ea-9bf0-e43d706d6086.png)
正确的应该是显示`dv`（全拼`dui`）的候选词，估计是把全拼发给后端了，后端按照双拼解析了。

**Comment by tumashu** [comment]
使用rime 的时候 pyim-default-scheme 要设置为 rime，

**Comment by xhcoding** [comment]
使用小鹤双拼，同样的问题。

选择 `小` 前
![Snipaste_2020-03-02_11-17-15](https://user-images.githubusercontent.com/30917129/75642781-b1ad2700-5c77-11ea-89df-b3cb108a73fa.png)

选择 `小` 后
![Snipaste_2020-03-02_11-17-38](https://user-images.githubusercontent.com/30917129/75642811-d0132280-5c77-11ea-86d9-411ebb4733ea.png)

**Comment by xlshiz** [comment]
> 使用rime 的时候 pyim-default-scheme 要设置为 rime，

pyim-default-scheme 已经设置为 rime，pyim+rime已经使用很长时间了。

**Comment by tumashu** [comment]
```
(liberime-search "womfdv")
(liberime-select-candidate 2)
(liberime-get-context)
```
看看返回什么

**Comment by xlshiz** [comment]
三句返回值
``` elisp
("我们队" "我们" "我" "喔" "窝" "握" "卧" "沃" "硪" "涡" "倭" "渥" "蜗" "肟" "斡" "偓" "幄" "挝" "龌" "埚" "㳡" "莴" "仴" "涴" "瓁" "雘" "瞃" "捼" "濣" "婑" "焥" "猧" "腛" "踒" "踠" "擭" "薶" "婐" "捰")
t
((commit-text-preview . "我们对") (composition (length . 10) (cursor-pos . 10) (sel-start . 3) (sel-end . 10) (preedit . "我men dui")) (menu (highlighted-candidate-index . 0) (last-page-p . t) (num-candidates . 19) (page-no . 0) (page-size . 100) (candidates "们对" "门对" "们" "门" "闷" "焖" "扪" "満" "悗" "亹" "懑" "鞔" "暪" "钔" "菛" "虋" "殙" "𫞩" "椚")))
```

**Comment by tumashu** [comment]
这是一个很坑人的问题，我先问问 librime 的维护者，看有没有简单的法子 https://github.com/rime/librime/issues/349

**Comment by tumashu** [comment]
我用一个笨办法处理这个问题，速度有点慢，试试看行不行

**Comment by xlshiz** [comment]
简单测试了一下，没有问题了。
