### ISSUE TITLE
pyim+rime 五笔选择多字词异常

### ISSUE THREAD

**Issue by cnsunyour** [tumashu/pyim#360]
环境：
MacOS 10.15.3
emacs-plus 26.3
doom-emacs
pyim和liberime都已更新至最新版
86五笔极点词库，在系统中输入正常。

输入法编码 yqbb ，如图：
![image](https://user-images.githubusercontent.com/3713312/76690072-a7c3f480-6677-11ea-95df-c5bbea79757d.png)
此时如选择第2个候选词，就会变成这样：
![image](https://user-images.githubusercontent.com/3713312/76690090-d80b9300-6677-11ea-9aaa-5e1e7ef9cb08.png)
这样如果再选择一次第2个候选词，则会变成这样：
![image](https://user-images.githubusercontent.com/3713312/76690105-f96c7f00-6677-11ea-8285-014b1404db10.png)
也就是每选一次第2候选词，候选词不会上屏，并且会把第一个默认候选词加在后面。
这时如果按空格上屏，就会把全部3个词连起来的所有字上屏，并且会自动造词。
重新输入代码后会在候选框中显示刚才上屏的新词，如图：
![image](https://user-images.githubusercontent.com/3713312/76690158-6b44c880-6678-11ea-9f33-7d8236dbb15c.png)

而如果是二字词就没事，可以正常上屏，三字或三字以上的词就会出现这样的情况。

另外我 rime 里候选词是不排序的，可是在 pyim+rime 里又是排序了。

**Comment by tumashu** [comment]
我试着修复修复了一下，也许可以了

**Comment by cnsunyour** [comment]
@tumashu 选字异常的问题可以了，多谢。

还有个排序的问题，我在 rime 的 输入方案里设置是不排序，但是在 pyim 中是排序的，排序的逻辑貌似是只要选择过一次就会排在第一位（这样的话遇到需要偶尔选择一次的词就会有些困扰）。

另外排序没有保存，重启后排序依然是未排序状态。如此使用起来会比较迷。

我是否应该为此再开一个 issue 单独报告一下？

**Comment by tumashu** [comment]
再更新一下，然后(setq pyim-prefer-personal-dcache nil)

**Comment by cnsunyour** [comment]
好的，多谢。
