### ISSUE TITLE
elpa上最新版pyim无法在搜索时调出输入法(evil)

### ISSUE THREAD

**Issue by byhc2** [tumashu/pyim#361]
evil环境下，按/进入搜索，再按C - \ 无法切换到中文输入法。minibuffer下显示

`Symbol's function definition is void: nil`

用emacs的原始的I-search一样有问题。确认elpa之前的版本没问题（版本号好像是201911xxx）。

emacs 26.3和27.0下都一样。

**Comment by tumashu** [comment]
我试着hack了一下，也许有用
