### ISSUE TITLE
候选词窗口不显示

### ISSUE THREAD

**Issue by tepmnthar** [tumashu/pyim#362]
一个是在 ivy 的 minibuffer 里按 <kbd>M-j</kbd> 无效，这个是跟 `ivy-minibuffer-map` 里的 `ivy-yank-word` 默认按键冲突了

我现在是这样弄的，不知道有没有更好的办法
```
(use-package ivy
  :config
  (progn
    (define-key ivy-minibuffer-map (kbd "M-j") nil)))
```

另外一个是，在 isearch 里有什么办法可以执行 `pyim-convert-string-at-point` 么，因为默认用的不是拼音，搜索时有时会打断思路。。。这个比较奇怪的是，是极少数情况下似乎会出选词框，不清楚是哪的设置错了。。。

配置基本跟那个样例差不多，除了改成了五笔其他都一样

**Comment by tumashu** [comment]
五笔的话，默认会自动上屏，只有需要选择的时候才会出现选词框

在 2020-03-26 12:38:41，tepmnthar <notifications@github.com> 写道：


一个是在 ivy 的 minibuffer 里按 M-j 无效，这个是跟 ivy-minibuffer-map 里的 ivy-yank-word 默认按键冲突了

我现在是这样弄的，不知道有没有更好的办法

(use-package ivy
  :config
  (progn
    (define-key ivy-minibuffer-map (kbd "M-j") nil)))


另外一个是，在 isearch 里有什么办法可以执行 pyim-convert-string-at-point 么，因为默认用的不是拼音，搜索时有时会打断思路。。。这个比较奇怪的是，是极少数情况下似乎会出选词框，不清楚是哪的设置错了。。。

配置基本跟那个样例差不多，除了改成了五笔其他都一样

**Comment by tepmnthar** [comment]
感谢回复
刚刚又试了下，正常应该是这样的
![WX20200326-132638](https://user-images.githubusercontent.com/12714593/77613673-3ed95800-6f66-11ea-8090-9e58299a9ed6.png)
但绝大多数情况都没有选词框
![WX20200326-133208](https://user-images.githubusercontent.com/12714593/77613700-51ec2800-6f66-11ea-967c-797e75c1530b.png)

**Comment by tepmnthar** [comment]
我现在试出来的规律是，只有在正常 buffer 里出现选词框浮窗后，不要按回车确认而是 <kbd>C-g</kbd> 取消，这样之后的第一次 isearch 才会出选词框。。。
[操作视频](https://vimeo.com/400873610)
这里的 <kbd>C-g</kbd> 有做什么额外操作么？

**Comment by tumashu** [comment]
。。。你厉害，这么复杂操作都让你试出来了。。。。 暂时我也搞不清楚什么原因， 不过如果是简单场合，你可以试试 pyim-isearch-mode, 启用这个 mode 之后，直接就可以用 五笔码搜索中文了，我前几天加的功能。

**Comment by tepmnthar** [comment]
```
(defun pyim-terminate-translation ()
  "Terminate the translation of the current key."
  (setq pyim-translating nil)
  (pyim-preview-delete-string)
  (setq pyim-candidates nil)
  (setq pyim-candidates-last nil)
  (setq pyim-assistant-scheme-enable nil)
  ;; C-g 的操作不会取消选词，也不会执行该方法，只是把窗口关了，所以之后在任何时间后的第一次空格或类似操作都会在当前位置打出取消前的词
  ;; 在 C-g 关掉候选窗后，手动执行到这句之前都可以在 isearch 中输中文
  ;; 看上去 isearch 中无法弹出候选窗才是正常的，能输中文是之前的状态没有重置？
  (setq pyim-force-input-chinese nil)
  ;;
  (when (and (memq pyim-page-tooltip '(posframe child-frame))
             (pyim-posframe-valid-p))
    (posframe-hide pyim-page-tooltip-posframe-buffer))
  (pyim-entered-erase-buffer)
  (when (eq (pyim-scheme-get-option (pyim-scheme-name) :class) 'rime)
    (pyim-terminate-translation:rime)))
```

**Comment by tumashu** [comment]
我这边试了一下五笔，好像是正常的呀？

**Comment by tumashu** [comment]
试试 C-\ 启动输入法

**Comment by tepmnthar** [comment]
emmm 还是没有效果
我自己用的是 emacs26.1，[emacsformacosx的版本](https://emacsformacosx.com)，包都是最新的，init.el 基本删干净也不行
刚刚用 26.3 也试了下，一样
回头换个系统的 emacs 试下

**Comment by tumashu** [comment]
我刚才又测试了一下， isearch-mode 下 C-\ 可以打开输入法。
