### ISSUE TITLE
使用回车上屏英文如果里面有e有一个奇怪的行为

### ISSUE THREAD

**Issue by merrickluo** [tumashu/pyim#366]
如图，输入`subject`然后敲回车，会把e挪到最后并显示候选词。
![image](https://user-images.githubusercontent.com/1495875/80458366-3d36f180-8963-11ea-9c40-970887a05b74.png)

**Comment by tumashu** [comment]
我这边试了一下，好像没发现这个问题

**Comment by merrickluo** [comment]
恩，研究了一下看起来是 evil-escape 的问题，closing。
