### ISSUE TITLE
五笔词库不生效

### ISSUE THREAD

**Issue by drcxd** [tumashu/pyim#368]
包管理系统安装的pyim和pyim-wbdict

配置文件如下

    (require 'pyim)
    (setq pyim-default-scheme 'wubi)
    (require 'pyim-wbdict)
    (pyim-wbdict-gbk-enable)

启用pyim之后，似乎是无法读取词库，输入任何序列例如"aaaa"弹出的选词框里没有任何候选词。

另，如何配置使用YeFeiyu的词库？不会lisp，到这种情形就不会改了。

**Comment by tumashu** [comment]
pyim-restart

**Comment by drcxd** [comment]
试了，没用。

**Comment by tumashu** [comment]
现在这个问题还存在吗？

**Comment by tumashu** [comment]
我这边测试已经没有此问题了
