### ISSUE TITLE
岁寒拼音滑行输入方案

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#369]
@tumashu 
https://zhuanlan.zhihu.com/p/165009660
你觉得pyim集成这个方案容易吗？

**Comment by tumashu** [comment]
没有仔细研究过，这个太小众了。。。

**Comment by tumashu** [comment]
我最近觉得，pyim还是关注常见的几种输入法比较好，小众输入法除非有pyim开发者使用，否则很难很好的支持。
