### ISSUE TITLE
小鹤音形的词库不生效

### ISSUE THREAD

**Issue by jinboowu** [tumashu/pyim#371]
利用深蓝的转换将自定义短语转换为pyim格式的词库，显示转换成功。
然后在spacemacs下通过dict manager安装成功 
设置为首选词库，但是似乎没有作用，音形的词库的候选字应该不超过2个，但似乎仍显示为基础词库的多个候选字
而且形码似乎也没有起作用，比如说按mfd键应该显示候选字为“门” 
但是其候选字显示为“门的”

**Comment by tumashu** [comment]
因为 pyim 只支持小鹤拼音，不支持小鹤音型， 小鹤音型可能和五笔更加相似。

**Comment by tumashu** [comment]
同学可以参考 https://github.com/p1uxtar/pyim-smzmdict ，只要注意不要让 :code-prefix 和其它输入法的重复就可以。
