### ISSUE TITLE
在 .dir-locals.el 中设定 pyim-punctuation-translate-p 无法生效

### ISSUE THREAD

**Issue by AirManH** [tumashu/pyim#372]
## 环境

- `GNU Emacs 27.1`
- `pyim 20200929.138`

## 问题

我想在不同的项目使用不同形式的标点。

如果在 `.dir-locals.el` 将 `pyim-punctuation-translate-p` 设定为 `'(no yes auto)`，那么一旦我用 `toggle-input-method` 激活 `pyim`，这个变量的值会被修改回默认值 `'(auto yes no)`

如果我的做法不正确，我该怎样设定才能在不同文件中使用不同的标点？

## 复现

我的 `pyim` 的配置：

``` elisp
(global-set-key (kbd "C-\\") 'toggle-input-method)
(setq default-input-method "pyim")

(use-package pyim
  :defer t
  :config
  (progn
    (use-package pyim-basedict
      :config
      (pyim-basedict-enable))
    (setq pyim-default-scheme 'xiaohe-shuangpin)
    (setq pyim-page-length 5)
    (use-package posframe
      :config
      (setq pyim-page-tooltip 'popup)))
  )
```

`.dir-locals.el`

``` elisp
((org-mode . ((pyim-punctuation-translate-p . '(no yes auto)))))
```

1. 打开一个 `.org` 文件
2. 按 `y` 确定使用不安全的变量 `pyim-punctuation-translate-p`
3. `C-h v` + `pyim-punctuation-translate-p`
   显示为 `'(no yes auto)`
4. 按下 `C-\` 切换至 `pyim`
5. `C-h v` + `pyim-punctuation-translate-p`
   显示 `Its value is (auto yes no)`

**Comment by tumashu** [comment]
应该不太可能吧，我搜索了一下代码，除了 pyim-punctuation-toggle ，好像没有函数改变这个变量的值啊

**Comment by tumashu** [comment]
你试试在 pyim-load-hook 中设置这个变量，看行不行

**Comment by AirManH** [comment]
> 
> 
> 应该不太可能吧，我搜索了一下代码，除了 pyim-punctuation-toggle ，好像没有函数改变这个变量的值啊

我进行了一些简单的调试，发现问题应当在于：

在 `pyim-start` 中执行了 `(mapc 'kill-local-variable pyim-local-variable-list)` 和 `(mapc 'make-local-variable pyim-local-variable-list)` 导致变量被 **重置**

## 相关代码：

首先代码将 `pyim-punctuation-translate-p` 加入了 `pyim-local-variable-list`

https://github.com/tumashu/pyim/blob/3d94ab74bef8e353df9b4e75f1813ca1ed416999/pyim.el#L1118

然后在 `pyim-start` （也包括 `pyim-inactivate`） 中 **重置** 了该变量

https://github.com/tumashu/pyim/blob/3d94ab74bef8e353df9b4e75f1813ca1ed416999/pyim.el#L1319-L1322

## 调试

将 `pyim-start`  中的

``` elisp
 (interactive) 
 (mapc 'kill-local-variable pyim-local-variable-list) 
 (mapc 'make-local-variable pyim-local-variable-list) 
 (when (and restart save-personal-dcache) 
```

改为

``` elisp
  (interactive)
  (message "[pyim-start n:1320] pyim-punctuation-translate-p is %s" pyim-punctuation-translate-p)
  (mapc 'kill-local-variable pyim-local-variable-list)
  (message "[pyim-start n:1322] pyim-punctuation-translate-p is %s" pyim-punctuation-translate-p)
  (mapc 'make-local-variable pyim-local-variable-list)
  (message "[pyim-start n:1324] pyim-punctuation-translate-p is %s" pyim-punctuation-translate-p)
```

重复 https://github.com/tumashu/pyim/issues/372#issue-730376464 中的操作，得到 `*Message*` 中的信息为

``` text
For information about GNU Emacs and the GNU system, type C-h C-a.
Please type y, n, or !, or C-v/M-v to scroll: y
Add pyim dict "Basedict-elpa" to ‘pyim-extra-dicts’.
[pyim-start n:1320] pyim-punctuation-translate-p is '(no yes auto)
[pyim-start n:1322] pyim-punctuation-translate-p is (auto yes no)
[pyim-start n:1324] pyim-punctuation-translate-p is (auto yes no)
[pyim-inactivate n:4127] kill vars
Loading /home/air/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
```

**Comment by AirManH** [comment]
> 
> 
> 你试试在 pyim-load-hook 中设置这个变量，看行不行

我可以在 `.dir-locals.el` 中修改 `pyim-load-hook` 吗？因为我不想在 _我的配置文件_ 中 _猜测_ 或是 _限定_ 使用何种标点，我想要自行决定在 _不同的项目_ 中使用何种标点

**Comment by tumashu** [comment]
你把 pyim-punctuation-translate-p 从 pyim-local-variable-list 去除应该就可以了吧？setq 一下试试

**Comment by AirManH** [comment]
> 
> 
> 你把 pyim-punctuation-translate-p 从 pyim-local-variable-list 去除应该就可以了吧？setq 一下试试

这可以解决我的问题。

但是这样需要源码层面的修改。你是否考虑提供一个可自定义的变量，例如

``` elisp
(defvar pyim-fix-current-punctuation-width nil)
```

这个变量将决定在当前 buffer 中是否固定 `pyim-punctuation-translate-p` 不被重置。这样，用户就可以在 `.local-dir.el` 中使用如下的语句来依项目限定使用何种标点了。

``` elisp
((org-mode . ((pyim-punctuation-translate-p . '(no yes auto))
              (pyim-fix-current-punctuation-width . t))))
```

**Comment by tumashu** [comment]
可以试试这样
```
(setq pyim-local-variable-list
      (remove 'pyim-punctuation-translate-p pyim-local-variable-list))
```

**Comment by tumashu** [comment]
```
但是这样需要源码层面的修改。你是否考虑提供一个可自定义的变量，例如
```
这个我暂时不考虑。

**Comment by AirManH** [comment]
以下的配置可以实现我的目的：

``` elisp
(defvar air-pyim-fix-punctuation-width nil
  "Whether the punctuation width should be fixed.")

(use-package pyim
  ;; ...
  :config
  (progn
    (when air-pyim-fix-punctuation-width
      (setq pyim-local-variable-list
            (remove 'pyim-punctuation-translate-p pyim-local-variable-list)))
    ;; ...
    )
  )
```

`.dir-locals.el`

``` elisp
((org-mode . ((pyim-punctuation-translate-p . '(no yes auto))
              (air-pyim-fix-punctuation-width . t))))
```
