### ISSUE TITLE
加上每日构建功能

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#373]
我可以提供一个最初的配置，就用github提供的travis-ci.org

**Comment by tumashu** [comment]
可以研究研究

**Comment by redguardtoo** [comment]
ci 已在运行了，你可以在README开头加上ci的状态图标，
https://travis-ci.org/tumashu/pyim.svg?branch=master

![image](https://user-images.githubusercontent.com/184553/99865041-3facb180-2bfb-11eb-820d-2e83bed71338.png)

**Comment by tumashu** [comment]
pyim 用 el2org 生成的 README，感觉不太好加这个链接。。。。
