### ISSUE TITLE
发布了基于清华大学开放中文词库建立的pyim词典

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/pyim#375]
见 https://github.com/redguardtoo/pyim-another-dict 用下来还不错，是严格基于词的使用频率优化的。是否可以考虑在README上提一笔？

他们的网站是说可以作为研究目的开源的。我会去联系他们，看看是否可以用GPL

**Comment by tumashu** [comment]
先联系联系，看能不能解决版权问题，如果可以，替换现有的词库都可以。

**Comment by tumashu** [comment]
@redguardtoo 这个有希望解决版权问题么？

**Comment by redguardtoo** [comment]
不确定。信发了两个礼拜没回音。

**Comment by tumashu** [comment]
那估计就悬了。。。。。

**Comment by tumashu** [comment]
如果我们搞不定协议，只能README里面推荐给想用的同学了，这个词库你要不改个名字吧， another-dict 感觉有点随意

**Comment by redguardtoo** [comment]
tsinghua, maybe?

**Comment by tumashu** [comment]
pyim-thuocl 怎么样？

**Comment by tumashu** [comment]
也行

在 2021-03-01 13:07:15，"Chen Bin" <notifications@github.com> 写道：


tsinghua, maybe?

**Comment by tumashu** [comment]
尽量 pyim+一个单词

**Comment by tumashu** [comment]
```
基于清华词库，但删掉了一半的不常用词。
```
我觉得最好添加两个词库文件，一个是精简版，一个是全版，也许有些同学由于特殊原因，想使用全版。

**Comment by tumashu** [comment]
这个事情估计没戏了  :-\ ,  这个 issue 就关了吧。

**Comment by redguardtoo** [comment]
不好意思，事情太多，完全忘了。这个周末可以做一下。就只能弄一个词库了。

**Comment by tumashu** [comment]
:-)   对了， dregcache 是不是只支持全拼？

**Comment by redguardtoo** [comment]
> :-) 对了， dregcache 是不是只支持全拼？

只要是拼音词库都支持。是一个底层的库。

**Comment by tumashu** [comment]
像五笔，仓颉 支持不？  他们的编码和拼音不一样

**Comment by redguardtoo** [comment]
> 像五笔，仓颉 支持不？ 他们的编码和拼音不一样

不支持。正则表达搜索每一行开头的拼音，假设所有行都是按拼音排序的。

**Comment by tumashu** [comment]
明白了。

**Comment by redguardtoo** [comment]
词库名改了 https://github.com/redguardtoo/pyim-tsinghua-dict

**Comment by tumashu** [comment]
词库文件名没改吧？

**Comment by redguardtoo** [comment]
改了。
