### ISSUE TITLE
[idea] pyim become a GNU elpa package.

### ISSUE THREAD

**Issue by tumashu** [tumashu/pyim#376]
Should to be a good idea, but maybe hard to finish, two jobs:
1.  emacs-eim's GPL paper status.
2. pyim's GPL paper status.

**Comment by redguardtoo** [comment]
Good idea. I've already signed the paper of GNU ages ago.

**Comment by tumashu** [comment]
[ ] https://github.com/tumashu/pyim/commits?author=sun409              @sun409         
[ ] https://github.com/tumashu/pyim/commits?author=RenWenshan          @RenWenshan     
[ ] QiangF                                                             @QiangF
[ ] https://github.com/tumashu/pyim/commits?author=cireu               @cireu          
[ ] https://github.com/tumashu/pyim/commits?author=levindu             @levindu        
[ ] https://github.com/tumashu/pyim/commits?author=smallst             @smallst        
[ ] https://github.com/tumashu/pyim/commits?author=hitswint            @hitswint       
[ ] https://github.com/tumashu/pyim/commits?author=realasking          @realasking     

[X] https://github.com/tumashu/pyim/commits?author=Z572                @Z572            <15
[X] https://github.com/tumashu/pyim/commits?author=redguardtoo         @redguardtoo    
[X] https://github.com/tumashu/pyim/commits?author=akirak              @akirak          <15
[X] https://github.com/tumashu/pyim/commits?author=laampui             @laampui         <15
[X] https://github.com/tumashu/pyim/commits?author=manateelazycat      @manateelazycat 
[X] https://github.com/tumashu/pyim/commits?author=whatacold           @whatacold       <15
[X] https://github.com/tumashu/pyim/commits?author=albert748           @albert748       <15
[X] https://github.com/tumashu/pyim/commits?author=jiegec              @jiegec          <15
[X] 魔仙灵梦                                                                            <15
[X] https://github.com/tumashu/pyim/commits?author=et2010              @et2010          <15
[X] https://github.com/tumashu/pyim/commits?author=jackycxh            @jackycxh        <15
[X] https://github.com/tumashu/pyim/commits?author=Liu233w             @Liu233w         <15
[X] https://github.com/tumashu/pyim/commits?author=w0lker              @w0lker          <15
[X] https://github.com/tumashu/pyim/commits?author=xuchunyang          @xuchunyang      <15

**Comment by cireu** [comment]
I've signed assignment.

**Comment by RenWenshan** [comment]
No problem here. Could you please share a guide for signing the assignment (if all contributors need to sign)?

**Comment by tumashu** [comment]
主要过程如下：
1. 首先到 emacs-devel mailling list 中发一个邮件，告诉 emacs 维护者说你想签署 GPL 纸质协议， 开发者会私发一个邮件给你, 可以参考： https://lists.gnu.org/archive/html/emacs-devel/2020-10/msg01611.html
2. 打开邮件里面的链接后，会要求填写一些个人信息，用于生成 pdf 协议文件。
3. 下载 pdf 文件，打印，签字，扫描为 pdf 文件。
4. 将扫描好的pdf文件发送到要求电子邮箱。

**Comment by tumashu** [comment]
@RenWenshan 标记为 [X] 的不需要做什么事情，要不就是已经签署，要不就是累计贡献代码行数 < 15,  累计代码行数 < 15 行的可以不用签署，如果以后准备给 emacs 贡献代码，也建议签署

**Comment by cireu** [comment]
> 
> 
> 主要过程如下：
> 
>     1. 首先到 emacs-devel mailling list 中发一个邮件，告诉 emacs 维护者说你想签署 GPL 纸质协议， 开发者会私发一个邮件给你, 可以参考： https://lists.gnu.org/archive/html/emacs-devel/2020-10/msg01611.html
> 
>     2. 打开邮件里面的链接后，会要求填写一些个人信息，用于生成 pdf 协议文件。
> 
>     3. 下载 pdf 文件，打印，签字，扫描为 pdf 文件。
> 
>     4. 将扫描好的pdf文件发送到指定的电子邮箱。

现在不建议为了assignment发邮件到Emacs devel，应该发给 emacs-tagnents@gnu.org

**Comment by cireu** [comment]
在搜集完所有committer的assignment前, 可以先做一些事情, 让pyim符合ELPA的收录标准

1. [ ] 所有pyim的Elisp文件应当加入license声明。（这里是GPL2+）
2. [ ] 根据[GNU Coding Standards的要求](https://www.gnu.org/prep/standards/html_node/Comments.html#Comments),GNU软件应当使用英语书写注释。

**Comment by tumashu** [comment]
第一条的话简单，第二条我准备到时候提交到elpa的时候看看情况再说，毕竟这个软件99%都是中国人用，中文注释更适合

**Comment by tumashu** [comment]
不过最大的问题是pyim最初是依托emacs-eim开发的，我知道它的主要开发者已经签署协议，但不知道有没有合作开发者，github上面问了，到目前还没有回应

**Comment by levindu** [comment]
发信给 emacs-tagnents@gnu.org 提示：

Address not found

Your message wasn't delivered to emacs-tagnents@gnu.org because the
address couldn't be found, or is unable to receive mail.
The response from the remote server was:

550 Callout verification failed: 550 Unrouteable address


On Mon, Nov 23, 2020 at 11:54 AM Zhu Zihao <notifications@github.com> wrote:
>
> 主要过程如下：
>
> 1. 首先到 emacs-devel mailling list 中发一个邮件，告诉 emacs 维护者说你想签署 GPL 纸质协议， 开发者会私发一个邮件给你, 可以参考： https://lists.gnu.org/archive/html/emacs-devel/2020-10/msg01611.html
>
> 2. 打开邮件里面的链接后，会要求填写一些个人信息，用于生成 pdf 协议文件。
>
> 3. 下载 pdf 文件，打印，签字，扫描为 pdf 文件。
>
> 4. 将扫描好的pdf文件发送到指定的电子邮箱。
>
> 现在不建议为了assignment发邮件到Emacs devel，应该发给 emacs-tagnents@gnu.org
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Thanks and Regards,
Levin

**Comment by tumashu** [comment]
https://lists.gnu.org/mailman/listinfo/emacs-tangents  估计需要你加入  mailling list

@levindu

**Comment by sun409** [comment]
> 
> 
> > 主要过程如下：
> > ```
> > 1. 首先到 emacs-devel mailling list 中发一个邮件，告诉 emacs 维护者说你想签署 GPL 纸质协议， 开发者会私发一个邮件给你, 可以参考： https://lists.gnu.org/archive/html/emacs-devel/2020-10/msg01611.html
> > 
> > 2. 打开邮件里面的链接后，会要求填写一些个人信息，用于生成 pdf 协议文件。
> > 
> > 3. 下载 pdf 文件，打印，签字，扫描为 pdf 文件。
> > 
> > 4. 将扫描好的pdf文件发送到指定的电子邮箱。
> > ```
> 
> 现在不建议为了assignment发邮件到Emacs devel，应该发给 [emacs-tagnents@gnu.org](mailto:emacs-tagnents@gnu.org)

文件裡還是這樣寫的：
https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

我前幾天在 mailing list 發的也很快收到私信
https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg01191.html

所以，應該還是往 emacs-devel 發？

**Comment by tumashu** [comment]
只要收到维护者回复就行。。。。

**Comment by levindu** [comment]
> > > 主要过程如下：
> > > ```
> > > 1. 首先到 emacs-devel mailling list 中发一个邮件，告诉 emacs 维护者说你想签署 GPL 纸质协议， 开发者会私发一个邮件给你, 可以参考： https://lists.gnu.org/archive/html/emacs-devel/2020-10/msg01611.html
> > > 
> > > 2. 打开邮件里面的链接后，会要求填写一些个人信息，用于生成 pdf 协议文件。
> > > 
> > > 3. 下载 pdf 文件，打印，签字，扫描为 pdf 文件。
> > > 
> > > 4. 将扫描好的pdf文件发送到指定的电子邮箱。
> > > ```
> > 
> > 
> > 现在不建议为了assignment发邮件到Emacs devel，应该发给 [emacs-tagnents@gnu.org](mailto:emacs-tagnents@gnu.org)
> 
> 文件裡還是這樣寫的：
> https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html
> 
> 我前幾天在 mailing list 發的也很快收到私信
> https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg01191.html
> 
> 所以，應該還是往 emacs-devel 發？

@sun409 可以发一份在这里或网盘吗？应该都是通用的吧？如果要签，很多人也需要。

**Comment by sun409** [comment]
Attached below.  Please fill and email according to instructions.
Thank you for your interest in Emacs.

----------------------------------------------------------------------
Please email the following information to assign@gnu.org, and we
will send you the assignment form for your past and future changes.

Please use your full legal name (in ASCII characters) as the subject
line of the message.
----------------------------------------------------------------------
REQUEST: SEND FORM FOR PAST AND FUTURE CHANGES

[What is the name of the program or package you're contributing to?]


[Did you copy any files or text written by someone else in these changes?
Even if that material is free software, we need to know about it.]


[Do you have an employer who might have a basis to claim to own
your changes?  Do you attend a school which might make such a claim?]


[For the copyright registration, what country are you a citizen of?]


[What year were you born?]


[Please write your email address here.]


[Please write your postal address here.]





[Which files have you changed so far, and which new files have you written
so far?]

**Comment by levindu** [comment]
发去 assign@gnu.org 的信，一般多久会收到回复呢？

**Comment by cireu** [comment]
> 发去 [assign@gnu.org](mailto:assign@gnu.org) 的信，一般多久会收到回复呢？

好像三到四天内会回信，然后发一个pdf给你，你需要把pdf打印下来签名，然后扫描成pdf发回去（可黑白），前后花了两星期

**Comment by sun409** [comment]
> 
> 
> 发去 [assign@gnu.org](mailto:assign@gnu.org) 的信，一般多久会收到回复呢？

大家应该都是希望 GNU 好，建议把 email 删除，或此 comment 删除。

**Comment by sun409** [comment]
已完成，收到 FSF 回传的 PDF 了。

**Comment by tumashu** [comment]
ok

**Comment by tumashu** [comment]
@RenWenshan @QiangF @smallst @hitswint @realasking  ping :-)

**Comment by RenWenshan** [comment]
@tumashu 不好意思，刚发了邮件到 emacs-devel，等待回复中

**Comment by RenWenshan** [comment]
@tumashu 搞定了，已收到 FSF 回传的 PDF

**Comment by tumashu** [comment]
@RenWenshan ok

**Comment by tumashu** [comment]
完成

**Comment by smallst** [comment]
天呐，github发我的邮件太多了居然在完成了才看到这个issue。
还好我提交的代码少hhh

**Comment by tumashu** [comment]
@smallst  :-)
