### ISSUE TITLE
一个人会翻译 readme 吗？

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [tumashu/pyim#381]
你好，

因为我的中文不这么好，所以我没明白你们的 readme。一个人告诉了我 pyim 很有用，但是我现在不知道怎么可以用你们的 pyim。

谢谢！
小龙

**Comment by tumashu** [comment]
you can try the below config:
```
(require 'pyim)
(setq default-input-method "pyim")

;; 使用全拼
(setq pyim-default-scheme 'quanpin)
(setq pyim-page-tooltip 'posframe)

;; 显示5个候选词。
(setq pyim-page-length 5)

(require 'pyim-basedict)
(pyim-basedict-enable)

```

**Comment by ZelphirKaltstahl** [comment]
Thank you, this works.

In general, of course it would still be great to have a translated readme ; )

**Comment by tumashu** [comment]
我暂时不会翻译 readme，如果其他人有兴趣，可以 pr  :-)
