### ISSUE TITLE
在你提供的配置例子中，如何手动切换中英文？

### ISSUE THREAD

**Issue by xukongwen** [tumashu/pyim#384]
你好，这个插件简直太好了，解决了我的痛。
刚刚试用，在用你提供的配置例子，请问如何手动切换中英文呢？

比如按shift之类的？

谢谢！

**Comment by tumashu** [comment]
不支持 shift， 这可能是 emacs 的限制，我提供的配置里面有探针设置，一般是自动切换中英文。

**Comment by xukongwen** [comment]
比如说，我打开一个新文档，但你的设置是默认英文，我如何开启中文呢？
谢谢

**Comment by xukongwen** [comment]
说没有正确安装或emac版本不支持porframe
我的emacs是26.1

**Comment by tumashu** [comment]
我的设置是用 M-j, 你可以去掉探针设置，然后是 C-\  开启输入法 ，

**Comment by xukongwen** [comment]
谢谢

**Comment by searene** [comment]
@tumashu 请问使用探针模式的时候，有没有办法简便地在英文后面输入中文？比如下面这句话：

> 这是Johnson的一次实验

在探针模型下，“这是Johnson”可以顺利输入，但是要打“的”的时候就遇到了问题，如果直接打“de“，然后按M-j的话，整个Johnsonde都会被转化为拼音，我现在的做法是，先在Johnson后面打一个空格，然后打de，然后按M-j将de转化为“的”，然后再把”的”前面的空格去掉，然后再把光标移动到“的” 的后面，请问你也是这样做的么？好像有点麻烦的样子，不知道有没有更方便的做法。

**Comment by tumashu** [comment]
我是习惯中英文之间加空格，所以没有你的烦恼 :-)

**Comment by searene** [comment]
看了一下你之前的评论，确实中英文之间都加了空格 :)

不过感觉不加空格的人还是很多的，发现了之前的一个issue也是同样的问题 #139 

https://github.com/tumashu/pyim/issues/139

这个点子挺好，M-j的时候删除前面的空格，可以考虑将删不删除空格设为配置点

**Comment by tumashu** [comment]
@searene 

```
(add-hook 'pyim-convert-string-at-point-hook
          (lambda ()
            (when (equal (char-before) ? )
              (delete-char -1))))
```

**Comment by tumashu** [comment]
当然，你如果使用全拼，也可以试试 v字快捷键， 
```
(defcustom pyim-outcome-trigger-function 'pyim-outcome-trigger-function-default
  "可以使用 `pyim-outcome-trigger' 激活的函数。

这个函数与『单字快捷键配合使用』，当光标前面的字符为汉字字符时，
按 `pyim-outcome-trigger' 对应字符，可以调用这个函数来清洗
光标前面的文字内容。"
  :type 'function)

```

**Comment by searene** [comment]
@tumashu 谢谢，我试了一下pyim-convert-string-at-point-hook，非常好用！

不过我不太明白pyim-outcome-trigger-function是怎么解决这个问题的。我明白v可以将光标前的中文标点切换为英文标点，不过这个和现在讨论的问题有什么关系。。。

**Comment by tumashu** [comment]
如果光标前是汉字，v字键就会调用 pyim-outcome-trigger-function, 自定义这个函数就可以实现你需要的功能

**Comment by searene** [comment]
> 如果光标前是汉字，v字键就会调用 pyim-outcome-trigger-function, 自定义这个函数就可以实现你需要的功能

明白了，谢谢 :)

**Comment by tumashu** [comment]
你可以研究研究 pyim-outcome-trigger-function-default   :-)

**Comment by young40** [comment]
`(setq pyim-chinese-status t)
  (defun pyim-chinese-switch()
    (interactive)
    (setq pyim-chinese-status (not pyim-chinese-status))
    (if pyim-chinese-status
      (message "Pyim Chinese: On")
      (message "Pyim Chinese: Off"))
    )
  (defun pyim-chinese-probe() (not pyim-chinese-status))

  (global-set-key (kbd "H-k") 'pyim-chinese-switch)
  (setq pyim-english-input-switch-functions
        '(pyim-chinese-probe))
`

我用了一个变量状态来保存是否是中文输入, 绑定一个快捷键来切换变量.

再写一个最简单的probe来返回这个变量状态
