### ISSUE TITLE
请问posframe具体怎么设置？

### ISSUE THREAD

**Issue by xukongwen** [tumashu/pyim#385]
我在源中下载安装了，请问具体如何在init.le中设置呢？
歇息！

**Comment by tumashu** [comment]
一般按照 posframe 包，然后，(setq pyim-page-tooltip 'posframe)

**Comment by xukongwen** [comment]
我安装了，然后说是报错。
谢谢这么快的回复。

**Comment by tumashu** [comment]
报什么错误？

**Comment by xukongwen** [comment]
说没有正确安装或emac版本不支持porframe
我的emacs是26.1

**Comment by tumashu** [comment]
posframe 不支持终端
