### ISSUE TITLE
refactor pyim.el

### ISSUE THREAD

**Issue by davidshen84** [tumashu/pyim#387]
Hi,

这个文件太长了。还有很多注释都和readme里重复。可以把这个文件按功能和输入法分割一下吗？然后写一个开发说明，指导大家怎么贡献代码。

**Comment by tumashu** [comment]
以前这个文件是分割成多个文件的，后来我嫌弃处理警告之类的太麻烦，把它合并为一个文件了

**Comment by tumashu** [comment]
pyim 已经拆分成多个文件了，这个 issue 就关了。
