### ISSUE TITLE
拼音分隔符在某些情况下没有处理

### ISSUE THREAD

**Issue by searene** [tumashu/pyim#393]
复现过程：
1. 打英文字母：`qingbazhebijin'e`   （对应中文：“请把这笔金额”）
2. 执行函数`pyim-convert-string-at-point`，把英文转化为中文
3. 前面的几个字转换都没有问题，转换到`jin'e`的时候，pyim没有识别出中间的`'`，而是把它理解为`jine`，因此就只有“今年”之类不是很匹配的候选词
4. 另外需要注意的是，直接打`jin'e`然后转化为中文是没有问题的，只有`jin'e`前面还存在其他拼音的时候才会出现上述问题

![image](https://user-images.githubusercontent.com/3351317/116037336-874bd380-a69a-11eb-8133-4d6fcb815954.png)

**Comment by tumashu** [comment]
我这边试了一下，似乎没这个问题

**Comment by searene** [comment]
这挺奇怪的，我这里一个Linux系统，一个macOS，全都有这个问题。。。我一开始猜测可能跟配置有关，不过我把pyim的配置全部删掉了，只留下加载pyim包的命令，也还是这种情况。。
