### ISSUE TITLE
[idea] 更新 code-prefix 的格式

### ISSUE THREAD

**Issue by tumashu** [tumashu/pyim#394]
当前 code-prefix 都使用一个标点符号，多种输入法 code-prefix 冲突的可能性极大, 比如：
```
.aaaa 工
.aad 式
```

我想将其改成类似下面的格式：

```
wubi/aaaa 工
wubi/aad 式

```

@redguardtoo 陈，这样更改对 dreghash 影响大么？ 好不好调整？

**Comment by redguardtoo** [comment]
代码没问题。但用户可能有很大问题。比如用户用旧词库但是代码是新的。最好在支持旧数据格式的情况下加入新词库格式。

**Comment by tumashu** [comment]
全拼和双拼不影响，因为他们不用prefix

**Comment by tumashu** [comment]
受影响的是哪些自己维护五笔或者仓颉词库的用户，但我个人感觉人数很少，因为仓颉五笔都有现成的包，这些包我已经切换到新格式
