### ISSUE TITLE
3.7版造词功能有点问题

### ISSUE THREAD

**Issue by lld2001** [tumashu/pyim#395]
https://emacs-china.org/uploads/default/original/2X/1/18c943583676a03e0fa48c3d1ff5a29bb1a599e1.gif

我调试了一下，发现是在 pyim-cstring-to-xingma:wubi 函数中， (pyim-code-search string 'wubi) 这句找不到“红河”这个词，就会返回" "（空格），后续判断(when (string-empty-p code)，会一直把空格返回到上级函数。我把string-empty-p换成string-blank-p就正常了。

**Comment by tumashu** [comment]
赞，五一后修复，现在回老家没电脑 :-)

**Comment by lld2001** [comment]
谢谢，五一快乐！

另外，还有两个问题请教：

1.  五笔能不能调整词频
2.  删除个人造的词时，在pyim-dhashcache-icode2word文件还有相应的 key 存在。如下：wubi/xais是红河的五笔编码。
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("wubi/ihfg" nil "wubi/xais" nil))

**Comment by tumashu** [comment]
应该修复了，试试吧

**Comment by tumashu** [comment]
空编码的问题已经修复，可以试试

**Comment by tumashu** [comment]
五笔字不调整词频，词应该会调整

**Comment by lld2001** [comment]
> 空编码的问题已经修复，可以试试

造词和空编码都可以了。

**Comment by lld2001** [comment]
> 五笔字不调整词频，词应该会调整

词频好像不会调整，还是我不会用。我用xais造了“红河”这个词，这个编码有个“红酒”，输入“红河”多次后，退出重启emacs，“红河”不会排在第一个。

**Comment by tumashu** [comment]
我刚刚调整了一下，再试试看

**Comment by lld2001** [comment]
强！现在可以了。

close #395
