### ISSUE TITLE
用倉頡輸入法每次按空白鍵都會報錯

### ISSUE THREAD

**Issue by shth** [tumashu/pyim#401]
每次按空白鍵都會報以下的錯誤
```
Debugger entered--Lisp error: (void-function pyim-hanzi2xingma:cangjie)
  pyim-hanzi2xingma:cangjie("你")
  pyim-hanzi2xingma("你" cangjie t)
  pyim-create-pyim-word("你" t)
  pyim-page-select-word:xingma()
  pyim-page-select-word()
  funcall-interactively(pyim-page-select-word)
  call-interactively(pyim-page-select-word)
  pyim-start-translation(111)
  pyim-input-method(111)
```

點進`pyim-hanzi2xingma` 看看發現的確是沒有 `pyim-hanzi2xingma:cangjie` 這個function
![Capture](https://user-images.githubusercontent.com/15711961/120884299-f828c880-c614-11eb-9844-c2b18670fd04.PNG)

但奇怪的是在github這裡發現連`pyim-hanzi2xingma`都早已被刪除
我去查看版本,應該都是最新的
(這裡安裝了兩次,我猜會不會是DOOM安裝的,不過應該版本也不算舊)
![Capture2](https://user-images.githubusercontent.com/15711961/120884403-9c127400-c615-11eb-883a-998e8402174e.PNG)

以下是我的config檔
```
.doom.d/config.el

(use-package! pyim-cangjiedict                                             
                 :config                                                          
                 (setq default-input-method "pyim")                  
                 (setq pyim-page-tooltip 'popup)                          
                 (setq pyim-default-scheme 'cangjie)           
                 (pyim-cangjie5dict-enable) ;; 啓用五代詞庫(Enable cangjie5)    
                 ) 
```

謝謝!

**Comment by tumashu** [comment]
我感觉你是有旧版本的影响

在 2021-06-05 15:56:43，shth ***@***.***> 写道：


每次按空白鍵都會報以下的錯誤

Debugger entered--Lisp error: (void-function pyim-hanzi2xingma:cangjie)

  pyim-hanzi2xingma:cangjie("你")

  pyim-hanzi2xingma("你" cangjie t)

  pyim-create-pyim-word("你" t)

  pyim-page-select-word:xingma()

  pyim-page-select-word()

  funcall-interactively(pyim-page-select-word)

  call-interactively(pyim-page-select-word)

  pyim-start-translation(111)

  pyim-input-method(111)



點進pyim-hanzi2xingma 看看發現的確是沒有 pyim-hanzi2xingma:cangjie 這個function


但奇怪的是在github這裡發現連pyim-hanzi2xingma都早已被刪除
我去查看版本,應該都是最新的
(這裡安裝了兩次,我猜會不會是DOOM安裝的,不過應該版本也不算舊)


以下是我的config檔

.doom.d/config.el



(use-package! pyim-cangjiedict                                             

                 :config                                                          

                 (setq default-input-method "pyim")                  

                 (setq pyim-page-tooltip 'popup)                          

                 (setq pyim-default-scheme 'cangjie)           

                 (pyim-cangjie5dict-enable) ;; 啓用五代詞庫(Enable cangjie5)    

                 ) 



謝謝!

**Comment by shth** [comment]
你說得對,執行
`doom sync -u; doom build; doom clean`
之後就可以了

話說我是從這裡得知的
https://discourse.doomemacs.org/docs?category=69&topic=53#debug-the-issue-yourself
