### ISSUE TITLE
<no-record> is undefined

### ISSUE THREAD

**Issue by Doerthous** [tumashu/pyim#402]
MobaXTerm远程打开的emacs中无法正常使用, 提示<no-record> is undefined

本地emacs 27.2
远程emacs 26.3
pyim 20210618.732
pyim-basedict 20210517.43

**Comment by tumashu** [comment]
有详细的报错信息吗？

**Comment by jizai** [comment]
> 
> 
> 有详细的报错信息吗？

我也遇到了类似情况，使用的是陈斌的配置，最近更新后，“C-\”开启输入之后，minibuffer中就显示"<no-record> is undefined"  没有其他的报错信息。

**Comment by tumashu** [comment]
@jizai 用 emacs -Q 测试一下，看有没有这个问题。

**Comment by jizai** [comment]
> 
> 
> @jizai 用 emacs -Q 测试一下，看有没有这个问题。

还是存在，如下图：
![Snipaste_2021-06-30_17-04-21](https://user-images.githubusercontent.com/12199375/123933996-73d42600-d9c5-11eb-896f-a0df34ef406a.png)

本机环境：虚拟机ubuntu18.04    测试时使用xshell连接
之前版本都是正常使用的，最近更新了一下，就不行了。

**Comment by tumashu** [comment]
<no-record> 是不是一个键？

**Comment by tumashu** [comment]
```
<f6> is undefined
```

**Comment by jizai** [comment]
> 
> 
> 是不是一个键？
> 
> ```
> <f6> is undefined
> ```

随便按任何字母键，都会显示上面的那个信息。

**Comment by tumashu** [comment]
试试这个函数行不行
```
(defun pyim-add-unread-command-events (key &optional reset)
  (when reset
    (setq unread-command-events nil))
  (setq unread-command-events
        (if (characterp key)
            (cons key unread-command-events)
          (append (mapcan (lambda (e) (list e))
                          (append key nil))
                  unread-command-events))))
```

**Comment by jizai** [comment]
> 
> 
> 试试这个函数行不行
> 
> ```
> (defun pyim-add-unread-command-events (key &optional reset)
>   (when reset
>     (setq unread-command-events nil))
>   (setq unread-command-events
>         (if (characterp key)
>             (cons key unread-command-events)
>           (append (mapcan (lambda (e) (list e))
>                           (append key nil))
>                   unread-command-events))))
> ```
这回可以啦，感谢！能大概讲下是什么原因吗？

![11111](https://user-images.githubusercontent.com/12199375/123938805-0aa2e180-d9ca-11eb-948c-03880d9d2b41.png)

**Comment by tumashu** [comment]
```
这回可以啦，感谢！能大概讲下是什么原因吗？
```
我将 emacs quail 的一个变更 https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=bd5c7404195e45f11946b4e0933a1f8b697d8b87  

port 到 pyim 后出现的问题，原因未知，这个主要是为了解决 emacs 键盘 macro 会出现不必要的重复问题。

**Comment by tumashu** [comment]
你可以先把这个函数拷贝到你的配置里用吧。

**Comment by jizai** [comment]
> 
> 
> 你可以先把这个函数拷贝到你的配置里用吧。

好的，非常感谢您！

**Comment by tumashu** [comment]
做了一下 ugly hack，等其他人的帮助， 毕竟键盘宏很少用，https://github.com/tumashu/pyim/commit/4d159dcc53ef41ebb26aa2e64f27f7103af09d5f

**Comment by tumashu** [comment]
@Doerthous 用最新的 pyim 时，设置 (setq pyim-hacks-for-ssh t)

**Comment by tumashu** [comment]
昨天我试了一下xshell和MobaXTerm，这个问题好像已经不存在了，所以删除了相关的hack代码。
