### ISSUE TITLE
小鹤双拼打不出按（an）字

### ISSUE THREAD

**Issue by luyajun01** [tumashu/pyim#408]
如题，pyim的小鹤双排模式下an显示不出中文字。

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/127953626-69b3a48d-b957-44f1-8c35-0adacac80ca9.png)

**Comment by tumashu** [comment]
我这边类似这样

**Comment by luyajun01** [comment]
谢谢答复，我再看下。

**Comment by 3vau** [comment]
我这里an的结果被映到了aj上，也就是a an……留待他人参考qwq
