### ISSUE TITLE
term 模式下切换到 pyim 不能输入中文

### ISSUE THREAD

**Issue by blldw** [tumashu/pyim#410]
eshell 模式下可以用 pyim 输入中文, 但是使用 M-x ansi-term 或 M-x multi-term (需要安装 multi-term 宏包) 后, 即使使用 toggle-input-method 切换到 pyim, 也不能输入中文. 光标颜色倒是变了. 可能是什么原因呢?

**Comment by tumashu** [comment]
我感觉是因为term将按键事件全部接管了的原因

**Comment by blldw** [comment]
应该是. term 模式下, Emacs 将外部 shell (Bash, Zsh 等) 嵌入进来. pyim 是 Emacs 内的输入法, 由于 term 接管按键, 不再认 Emacs 的输入法了. 经初步测试, 包括 Emacs 自带的支持中文的输入法都不能输入中文, 只认系统的输入法.

在 Emacs 中使用 shell 的时候比较多, eshell 和 shell 不如 term 强大, 因此不能在 term 中使用 pyim 还是有点遗憾. 我是昨天才接触   pyim 的, 很好! 希望这个包能不断完善下去, 造福我们中文用户~

**Comment by tumashu** [comment]
emacs-rime也值得看看

**Comment by blldw** [comment]
还没接触过 emacs-rime, 谢谢你的建议.

**Comment by tumashu** [comment]
https://github.com/laishulu/emacs-smart-input-source  也值得了解，这是目前emacs中文输入的三种比较好的方案

**Comment by blldw** [comment]
好的. 谢谢你提供的信息, 先了解一下

**Comment by blldw** [comment]
另外请问一下, pyim-liberime 包在哪里? emacs 仓库中没找到, 介绍中也没给出链接.

**Comment by tumashu** [comment]
就在pyim仓库

**Comment by blldw** [comment]
看到了

**Comment by blldw** [comment]
term mode 下又有两种模式：char mode 和 line mode. char mode 下每次输入的内容都会送到外部 shell, 而 line mode 下只有按回车才会。在 line mode 下可以用 pyim 输入中文。emacs-rime 也是类似的。
