### ISSUE TITLE
怎么显示所打的全部字？

### ISSUE THREAD

**Issue by ISouthRain** [tumashu/pyim#414]
你好，请问一下这个怎么做到？
你的这个怎么做到？
![upload_2021_11_01_17_43_23_619](https://user-images.githubusercontent.com/65887663/139652767-a83be3b5-e75f-431e-bb40-b1df4a8c2eae.jpg)
我的只能显示一个字。。
![upload_2021_11_01_17_44_13_502](https://user-images.githubusercontent.com/65887663/139652877-ee6d04e2-62cf-487b-9ce1-debe1aa01766.jpg)
请问怎么显示？我无法找到配置

**Comment by tumashu** [comment]
包装pyim-basedict试试

**Comment by ISouthRain** [comment]
你好，我不是很明白你的意思，是要我自己重新添加一个(pyim-basedict)词库吗？

**Comment by tumashu** [comment]
安装 pyim-basedict 包，然后把 pyim-basedict-enable 函数添加到配置

**Comment by ISouthRain** [comment]
问题已解决，谢谢你！

**Comment by tumashu** [comment]
ok
