### ISSUE TITLE
让forward-word和backward-word按照中文分词移动

### ISSUE THREAD

**Issue by wanghuibin0** [tumashu/pyim#416]
在中文输入状态，`forward-word`和`backward-word`，是以句子为单位移动的。
`pyim-forward-word`和`pyim-backward-word`，则是以单个字为单位移动的。

我看pyim是有中文分词的功能的，不知道是否能做到以中文分词为单位移动？

如果能，希望能把方法加入到说明文档中。
如果不能，可否加入以中文分词移动这个功能？

**Comment by tumashu** [comment]
pyim-forward-word和pyim-backward-word 就是按分词来移动的，你是不是忘记安装拼音词库了？

**Comment by wanghuibin0** [comment]
> pyim-forward-word和pyim-backward-word 就是按分词来移动的，你是不是忘记安装拼音词库了？

哎呀还真是，确实是没装拼音词库的原因，现在已经好了！

顺便再问个小问题：我用evil，想让w,b这些也能按照分词来移动，请问应该怎么做呢？

**Comment by tumashu** [comment]
不太了解 evil， 你可以看看这两个按键绑定的命令，然后参考 pyim-forward-word 的定义，写自定义命令。

**Comment by wanghuibin0** [comment]
好的，谢谢你。你这响应速度好快！

> 不太了解 evil， 你可以看看这两个按键绑定的命令，然后参考 pyim-forward-word 的定义，写自定义命令。
