### ISSUE TITLE
在开启 profile-start 后，使用 pyim 会导致 emacs 卡死

### ISSUE THREAD

**Issue by patrolli** [tumashu/pyim#418]
我这里会稳定触发这个问题，在开启 `profile-start` 后，如果再使用 pyim，当出现候选框后，emacs 就会卡死。
补充：
我的emacs 版本是 28，然后是在 wsl1 下面使用的 emacs，不知道大家会出现这个问题吗？

**Comment by tumashu** [comment]
我在linux下试了一下，没有发现这个问题
