### ISSUE TITLE
双拼模式下不同 buffer 下第二个候选词不一样

### ISSUE THREAD

**Issue by allenryb** [tumashu/pyim#433]
我使用双拼，下面是我在 `elisp-mode` 下输入 `xn` 的结果

![image](https://user-images.githubusercontent.com/6965371/148675894-218273b5-e5e8-4565-aab6-2f1d520898e3.png)

下面是在 `org-mode` 下输入 `xn` 的结果

![image](https://user-images.githubusercontent.com/6965371/148675881-3c498f63-46e8-4580-914e-2038e1ecd24d.png)

这里第二个候选词不一样。在 `tex-mode`, `markdown-mode` 下，第二个候选词都不会出来。

事实上在 `org-mode` 下输入 `xn` 后，第二奇怪的候选词 "校内" 大概是 0.5s ~ 1s 左右时间才出来，但我已经把联想词功能关掉 `(setq pyim-enable-shortcode nil)`

请问如何去掉这个晚出来的候选词？

**Comment by tumashu** [comment]
不奇怪，这个词是通过搜索当前buffer得到的，你可以将pyim-process-async-delay设置的长一点

在 2022-01-09 17:19:59，allenryb ***@***.***> 写道：


我使用双拼，下面是我在 elisp-mode 下输入 xn 的结果

下面是在 org-mode 下输入 xn 的结果

这里第二个候选词不一样。在 tex-mode, markdown-mode 下，第二个候选词都不会出来。

事实上在 org-mode 下输入 xn 后，第二奇怪的候选词 "校内" 大概是 0.5s ~ 1s 左右时间才出来，但我已经把联想词功能关掉 (setq pyim-enable-shortcode nil)

请问如何去掉这个晚出来的候选词？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tumashu** [comment]
我升级了一下，估计可以正确处理双拼的异步获取磁条了

在 2022-01-09 17:19:59，allenryb ***@***.***> 写道：


我使用双拼，下面是我在 elisp-mode 下输入 xn 的结果

下面是在 org-mode 下输入 xn 的结果

这里第二个候选词不一样。在 tex-mode, markdown-mode 下，第二个候选词都不会出来。

事实上在 org-mode 下输入 xn 后，第二奇怪的候选词 "校内" 大概是 0.5s ~ 1s 左右时间才出来，但我已经把联想词功能关掉 (setq pyim-enable-shortcode nil)

请问如何去掉这个晚出来的候选词？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by allenryb** [comment]
非常感谢～
