### ISSUE TITLE
进入pyim输入时出现 wrong-type-argument: hash-table-p:Quit错误

### ISSUE THREAD

**Issue by Leyls** [tumashu/pyim#434]
toggle-debug-on-error之后backtrace记录如下：

`Debugger entered--entering a function:`
` #f(compiled-function () #<bytecode 0x1582f46d6331>)()`
`async-handle-result(#f(compiled-function (_) #<bytecode 0x1582f471b8a9>) (async-signal (wrong-type-argument hash-table-p Quit:)) #<buffer *emacs*<2>>)`
 `async-when-done(#<process emacs<1>> "finished\n")`

使用pyim很久了，第一次出现这个错误，进入pyim后准备输入时报这个错。重启emacs再使用pyim依然报错。

**Comment by tumashu** [comment]
不好判断，可以先检查一下词库缓存是不是损坏，在.emacs.d/pyim/dcache 目录下

在 2022-02-25 17:18:21，OPa ***@***.***> 写道：


toggle-debug-on-error之后backtrace记录如下：

Debugger entered--entering a function:
#f(compiled-function () #<bytecode 0x1582f46d6331>)()
async-handle-result(#f(compiled-function (_) #<bytecode 0x1582f471b8a9>) (async-signal (wrong-type-argument hash-table-p Quit:)) #<buffer *emacs*<2>>)
async-when-done(#<process emacs<1>> "finished\n")

使用pyim很久了，第一次出现这个错误，进入pyim后准备输入时报这个错。重启emacs再使用pyim依然报错。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Leyls** [comment]
删除dcache目录之后重启emacs是一样的报错，之前dcache目录内容如下
![image](https://user-images.githubusercontent.com/45854583/155832114-1e1e46f1-85b0-4afc-8079-eb1d025b1f7a.png)

**Comment by tumashu** [comment]
把pyim和emacs-async 重装一遍试试

**Comment by tumashu** [comment]
另外词库缓存中有个人词库缓存和词频缓存，最好不要删除

**Comment by Leyls** [comment]
重新安装async和pyim也是一样的报错。
这是pyim相关配置
```lisp
(require 'pyim)
(require 'pyim-basedict)
(pyim-basedict-enable)
(setq default-input-method "pyim")
(global-set-key "\C-f" 'toggle-input-method)
```

**Comment by tumashu** [comment]
看不出什么问题，你可以试试 emacs -Q,  看能不能重现这个问题。

**Comment by Leyls** [comment]
emacs -q 启动没有问题，应该是我个人配置的问题。
