### ISSUE TITLE
候选词丢失bug(有复现步骤)

### ISSUE THREAD

**Issue by young40** [tumashu/pyim#445]
最近有遇到候选词丢失的情况, 摸索了下找到了复现步骤.

版本: pyim-20220615.126

配置
```
(use-package pyim
  :ensure t
  :init
  (use-package popup
    :ensure)
  :config
  (setq pyim-page-tooltip 'popup)
  (setq pyim-indicator-modeline-string '("中文", "英文"))
  (setq pyim-dcache-directory (expand-file-name "dcache" (expand-file-name "pyim" *ewc*)))
  (setq default-input-method 'pyim)
  (setq pyim-page-length 9)
  (setq pyim-english-input-switch-functions '(pyim-chinese-probe))
  (setq-default pyim-punctuation-translate-p '(no))
  )
```

重现步骤如下:
1. 清空dcache目录. 重启emacs
2. 打开空org文件
3. 测试“ze”, 看到候选词正常
4. 导入词频文件, 使用`pyim-import-words-and-counts` 命令
5. 打开空org文件, 测试“ze”看到候选词只剩一个字“则”了. 重启emacs, bug还在.
6. 词频文件中其他几个字也是一样只剩一个了. 

词频文件内容如下
```
;;; -*- coding: utf-8-unix -*-
阶 2
以 3
反 1
则 2
```
![test](https://user-images.githubusercontent.com/1680953/174031337-4c4f0001-8b8f-4d19-b8cf-e3267b712ad3.jpg)

谢谢!

**Comment by tumashu** [comment]
我这边试了一下，好像没有类似问题，你没有安装 pyim-basedict 之类的词库包吗？

**Comment by tumashu** [comment]
查看一下 pyim-dicts 和 pyim-extra-dicts 两个变量的取值。

**Comment by young40** [comment]
> 我这边试了一下，好像没有类似问题，你没有安装 pyim-basedict 之类的词库包吗？

没加pyim-basedict, 但不加任何词库, 没出bug前, 都是可以选词的. 是有内置的词库吗? 这是正常的吗?

我看现在版本里面应该是没有这个文件(pyim-basedict )了吧?
README里还有相关介绍


> 查看一下 pyim-dicts 和 pyim-extra-dicts 两个变量的取值。

这两个值, 在出bug前后都是nil.

<img width="725" alt="截屏2022-06-16 21 43 47" src="https://user-images.githubusercontent.com/1680953/174084059-7515265e-35c1-4385-91ab-1e68fb97f814.png">
<img width="700" alt="截屏2022-06-16 21 43 22" src="https://user-images.githubusercontent.com/1680953/174084106-6145a789-8f5e-4b29-b889-620406bc924a.png">

我用最简的配置都能每次复现这个bug. 这个只是最容易复现的步骤, 平时在用的时候, 就能发现某些字突然就候选词不对了.
感觉和记录词频的机制有关系.
```
(use-package pyim
  :ensure t
  :init
  :config
  (setq default-input-method 'pyim)
  )
```

大佬辛苦看下, 还有没有什么地方可能有问题呢?

**Comment by young40** [comment]
补一张导入词频文件的log
<img width="889" alt="截屏2022-06-16 21 44 52" src="https://user-images.githubusercontent.com/1680953/174085084-c797af4f-27c2-4230-9bf2-a7928d6f749f.png">

**Comment by young40** [comment]
终于搞明白了, 确实是词库的问题. 我自己从网上下载了一个挺大的词库, 想着应该包罗万象了, 没想到都是些词, 最基本的字反而是缺失的. 想着可能是最基础的字都是其他输入法自带的, 网上提供的词库就只提供了各种各样的词了. 

不过在不添加任何词库的情况下, 也能打字, 简单翻了下貌似也没自带词库, 不知道这个时候是怎么可以打字的?? 还挺神奇的.
就是打了几下之后, 感觉还是词频哪里机制上有些问题, 反而打不出来了...

再次感谢, 打扰了.

**Comment by tumashu** [comment]
还真是一个bug,我试着修复了一下，再试试吧

**Comment by young40** [comment]
> 还真是一个bug,我试着修复了一下，再试试吧

好了. 点赞👍
