### ISSUE TITLE
选词框没有border？

### ISSUE THREAD

**Issue by LeoGitHuber** [tumashu/pyim#450]
![image](https://user-images.githubusercontent.com/50997355/180629096-1d201acd-0e2d-429e-91fa-26bd0f701b9f.png)
请问选词框可以添加边框吗？我想这能更好地增加辨识度。

**Comment by tumashu** [comment]
1. use posframe page tooltip
2. setq (setq pyim-page-posframe-border-width 10)
3. customize-face pyim-page-border

**Comment by LeoGitHuber** [comment]
请问设置的是pyim-page-border的box属性吗？

**Comment by LeoGitHuber** [comment]
> 1. use posframe page tooltip
> 2. setq (setq pyim-page-posframe-border-width 10)
> 3. customize-face pyim-page-border

请问是设置pyim-page-border的box属性吗？

**Comment by tumashu** [comment]
设置 background 颜色

**Comment by tumashu** [comment]
LeoGitHuber ***@***.***> writes:

>  1 use posframe page tooltip
>  2 setq (setq pyim-page-posframe-border-width 10)
>  3 customize-face pyim-page-border
>
> 请问是设置pyim-page-border的box属性吗？

background

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.

--

**Comment by LeoGitHuber** [comment]
谢谢，后来看到源码才知道是background。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月26日 17:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [tumashu/pyim] 选词框没有border？ (Issue #450) |

LeoGitHuber ***@***.***> writes:

> 1 use posframe page tooltip
> 2 setq (setq pyim-page-posframe-border-width 10)
> 3 customize-face pyim-page-border
>
> 请问是设置pyim-page-border的box属性吗？

background

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.

--
