### ISSUE TITLE
输入"操作"词，报异常。大佬帮忙指教下。

### ISSUE THREAD

**Issue by HenryVonNew** [tumashu/pyim#451]
输入某些词组，会出现下面错误。新手，搞不太懂原因。大佬给指条路。多谢

报错为：
![image](https://user-images.githubusercontent.com/101700251/181937079-317323a1-9189-4e20-960b-aba7ec6e3f74.png)

栈信息：
![image](https://user-images.githubusercontent.com/101700251/181936898-94fea2f5-c980-4c20-8ab2-141c43330697.png)

配置：
(require 'pyim)
(setq default-input-method "pyim")
(require 'pyim-wbdict)
(setq pyim-default-scheme 'wubi)
(pyim-wbdict-v86-enable)
(setq debug-on-error t)

**Comment by tumashu** [comment]
升级pyim试试，感觉你好像用了pyim的旧版本，最新版本已经没有 pyim-dcache-code-split 函数了

**Comment by HenryVonNew** [comment]
重装doom emacs ，问题解决。感谢

**Comment by tumashu** [comment]
ok
