### ISSUE TITLE
`pyim-process-word-position`里的参数类型错误

### ISSUE THREAD

**Issue by zbelial** [tumashu/pyim#452]
好像是 `pyim-process--word-position` 这个变量有时候没有值，选下一页的时候会报错。
![image](https://user-images.githubusercontent.com/6436456/182774370-d001b127-d042-4399-ace7-d3f720d0b80a.png)

**Comment by tumashu** [comment]
有没有复现的步骤呢？

**Comment by zbelial** [comment]
还没总结出来必现的步骤。
我这两天再观察一下，也排除下配置的影响。

**Comment by zbelial** [comment]
我原来有些配置不适用于目前的pyim了，我改了之后，后面没再出现问题。
我先关了issue，再有问题再看吧。打扰了。
