### ISSUE TITLE
rime-quanpin的scheme中 使用v 键可以转换前面的字符 但是不能把中文加入个人词库

### ISSUE THREAD

**Issue by Mercurius-Lee** [tumashu/pyim#457]
在rime-quanpin的scheme中，快捷v键可以将前面的符号进行半角全角转换，但是不能把中文加入个人词库。
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/31580811/192107957-6888dba4-03d0-444e-ac09-610f8fe95241.png">

**Comment by Mercurius-Lee** [comment]
我的电脑系统 Mac os 10.15，部分配置如下，将rime-quanpin更换成quanpin一切正常。
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/31580811/192108328-4152efe9-b840-4ecd-a93a-343de766445f.png">

**Comment by Mercurius-Lee** [comment]
把包降级到此版本（commit: d1b28087e261814de5b3200629b023c403cb93d4），在rime-quanpin中快捷键v可以正常使用。
还有一个bug要报，https://github.com/tumashu/pyim/blob/d1b28087e261814de5b3200629b023c403cb93d4/pyim-liberime.el#L302，结尾应该将librime改成liberime，否则需要（require pyim-liberime）

**Comment by tumashu** [comment]
```
(cl-defmethod pyim-cstring-to-codes (string (_scheme pyim-scheme-rime) &optional criteria)
  "将中文字符串 STRING 转换为对应的拼音。"
  (pyim-cstring-to-codes string (pyim-scheme-get 'quanpin) criteria))

```

运行这段代码看行不行
