### ISSUE TITLE
【建议】通过检测光标前的两个单词是否都为英语，决定是否切换为英文模式。

### ISSUE THREAD

**Issue by suliveevil** [tumashu/pyim#463]
只检测一个字符的话，中英之间切换很频繁。

通过检测光标前的两个单词是否都为英语，决定是否切换为英文模式，这样能减少切换次数。

而且中文输入过程中如果要写数字/单个英文单词，也可以避免退出中文输入状态。

我用其他软件实现了这个功能，但性能太差了，pyim 利用自身分词功能应该能做得更好。

https://forum.keyboardmaestro.com/t/input-monitor-text-selection-and-character-before-the-cursor/26567

最后，感谢冯叔，感谢 pyim。

**Comment by suliveevil** [comment]
我的做法是获取光标之前的两个单词，判断光标之前有几个空格，如果两个单词都是英文，切有两个空格，才切换为英文模式。

无奈 macOS 太封闭了，只能用模拟`Option+左箭头`快捷键的方式先选中两个单词并复制，再正则匹配，效率太低了。所以虽然实现了智能切换输入法，但还是放弃了。

**Comment by tumashu** [comment]
中英文切换的模式是可以自定义的，你可以研究研究 pyim-probe：

https://github.com/tumashu/pyim/blob/master/pyim-probe.el

**Comment by suliveevil** [comment]
感谢感谢，我去看看。
