### ISSUE TITLE
输入位置越靠后候选词（开启了浮窗）的响应越慢

### ISSUE THREAD

**Issue by skunk007** [tumashu/pyim#467]
实际测试了一下大概约 3000字的文档，在前面三分之一的位置基本上输入响应没什么变化，
二分之一篇幅的位置，输入的时候就能够感觉到明显卡顿，
到最后的位置，就更慢了。

.emacs 中开启浮窗设置如下:
(require 'popup nil t)
(setq pyim-page-tooltip 'popup)

如果关闭浮窗,候选词在 minibuffer 中的话，在速度上是没有影响的（但一眼上一眼下用着实在比较苦）。

**Comment by tumashu** [comment]
试试 popon 和 posframe tooltip 看有没有改善

**Comment by tumashu** [comment]
我刚刚用红楼梦文本试了一下， popup也没有慢的无法忍受啊？

**Comment by skunk007** [comment]
我也再次试了一下，确实没有之前那种卡的感觉了。
有没有可能和连续输入有关系？
（昨天的3000多字是都用pyim 连续写的，但也不应该，因为中间关掉 EMACS 又反复试了一下）
系统配置是：
UBUNTU 20.04
GNOME3（PaperWM 平铺式窗口管理）

EMACS 26.3




我会再试下，有进一步的认识再补充。

在 2023-01-28 08:45:16，"tumashu" ***@***.***> 写道：

我刚刚用红楼梦文本试了一下， popup也没有慢的无法忍受啊？

**Comment by skunk007** [comment]
今天又反复测试了下，首先说结论：
- 从 popup 改成 posframe 是比较管用的。使用一个35万字的 txt 文档前进到各处进行输入的速度都没有明显差异。
（但有几次进行翻页【M+n/p】的时候会失去响应，只有向前一个字或向后一个字有反应，只是一个，并不能连续移动选词；一般这个时候 C+g 重新输入会恢复正常）
（posframe 需要 2022 版本，2018的报错）
- popup下复现了下之前陈述的问题，具体方式是采用 C+f 的方式每次前进约20000字，之后进行输入，两三次之后输入明显变慢，很卡。



在 2023-01-28 08:45:16，"tumashu" ***@***.***> 写道：

我刚刚用红楼梦文本试了一下， popup也没有慢的无法忍受啊？

**Comment by tumashu** [comment]
（但有几次进行翻页【M+n/p】的时候会失去响应，只有向前一个字或向后一个字有反应，只是一个，并不能连续移动选词；一般这个时候 C+g 重新输入会恢复正常）

```
(setq pyim-cloudim nil) 
(defalias 'pyim-candidates--search-buffer #'ignore)
```
试试关闭云搜词和当前 buffer 搜词试试

**Comment by skunk007** [comment]
Perfect!

可以了！感谢！！




在 2023-01-30 09:07:14，"tumashu" ***@***.***> 写道：

（但有几次进行翻页【M+n/p】的时候会失去响应，只有向前一个字或向后一个字有反应，只是一个，并不能连续移动选词；一般这个时候 C+g 重新输入会恢复正常）

(setq pyim-cloudim nil) 

(defalias 'pyim-candidates--search-buffer #'ignore)



试试关闭云搜词和当前 buffer 搜词试试

**Comment by tumashu** [comment]
我添加了一个选项，可以用来关闭buffer搜词，你可以了解了解 https://github.com/tumashu/pyim/commit/de7eff2a58d88b168e35c3c81484ea874991391c

**Comment by skunk007** [comment]
收到，辛苦了！













在 2023-02-03 08:51:51，"tumashu" ***@***.***> 写道：

我添加了一个选项，可以用来关闭buffer搜词，你可以了解了解 de7eff2
