### ISSUE TITLE
How can I diable the "pyim-translate-trigger-char" ?

### ISSUE THREAD

**Issue by lkcp** [tumashu/pyim#472]
Hi,

In my workflow, I input "v" near math symbols frequently.

I tried to disable the "pyim-translate-trigger-char"  but I failed.

I didn't find this variable by "C-h v"  , as well in the source code in this repo.

What should I do for that?

Best wishes!

**Comment by tumashu** [comment]
pyim-outcome-trigger

**Comment by lkcp** [comment]
Thanks!
