### ISSUE TITLE
光标颜色不随主题变化而变化

### ISSUE THREAD

**Issue by aGolduck** [tumashu/pyim#474]
在亮色主题下启动 pyim, 切换到暗色主题后，pyim 切换为英文输入仍然是黑色。光标与主题背景混杂基本不可见。

看了下代码，是简单地在启动 pyim 时记录了下光标颜色，是否有可能改为获取当前主题的默认光标颜色。

**Comment by tumashu** [comment]
好像 emacs 没有获取当前主题默认光标颜色的接口，在 pyim 这一块是不太好实现的。
