### ISSUE TITLE
为什么我的候选词后面总出现(buff)

### ISSUE THREAD

**Issue by mhwgoo** [tumashu/pyim#475]
如题，比如，我输入的拼音是“tishen"，候选词列表见图![image](https://github.com/tumashu/pyim/assets/20920033/87eb0e0b-af6e-447b-b7e7-a3748512aad8)

**Comment by tumashu** [comment]
词语联想功能，buf表示这个词是从当前 buffer搜索到的

**Comment by mhwgoo** [comment]
哦，这样呀。请问有办法关闭这个提示么，显得清爽一些。

p.s. 谢谢你开发了这么优秀好用的工具:)

**Comment by mhwgoo** [comment]
It worked. Thank you.
