### ISSUE TITLE
几年未用了。新安装后，词序感觉不太对啊。

### ISSUE THREAD

**Issue by yefeiyu** [tumashu/pyim#481]
在码表里下面这个词是从上到下是这样排序的：
                                                                                                                                
wubi/wcng 公司                                                                                                                                  
wubi/wcng 鹟                                                                                                                                    
wubi/wcng 鶲      

但是打wcng后，后面的单字排到最前面了。这是个bug吗？如何解决？

**Comment by yefeiyu** [comment]
感觉所有的生僻字都放到了词的前面。这个安排太不合理了。如何去掉这个功能？

**Comment by yefeiyu** [comment]
下列代码放到.emacs中
`(defun pyim-candidates-xingma-words-default (code)
  "搜索形码 CODE, 得到相应的词条列表。

按照词库中原有的字词顺序进行排序。"
  (let ((personal-words (pyim-dcache-get code '(icode2word)))
        (common-words (pyim-dcache-get code '(code2word)))
        (other-words (pyim-dcache-get code '(shortcode2word))))
    `(,@personal-words
      ,@common-words
      ,@other-words)))
`

**Comment by tumashu** [comment]
用这个设置吧，比直接覆盖 default 好一点。
```
(defcustom pyim-candidates-xingma-words-function
  #'pyim-candidates-xingma-words-default
  "形码输入法候选词列表生成函数。

如果形码输入法用户需要微调候选词词频，可以自定义这个函数。"
  :type 'function)

```

**Comment by tumashu** [comment]
形码输入法排序方式太难统一了，所以我添加了这个设置，不像再来回折腾了:-）
