### ISSUE TITLE
termux 下的emacs29.3使用报错“error in process sentinel: End of file during parsing” 

### ISSUE THREAD

**Issue by sherylynn** [tumashu/pyim#484]
现在用termux 里的emacs 29.3 还是有标题问题问题，并且会导致 base dict词库等没法用
把mac上的正常的dcache打包放进去能有词库了，但是还是会每次打开调用pyim的时候闪过上述错误或者
“error in process sentinel: async-handle-result: End of file during parsing”

一开始在doom emacs中使用，还以为是doom 自己的问题
直到自己从零开始攒emacs配置后发现还是这样

**Comment by tumashu** [comment]
Please try pyim-dregcache
```
(defcustom pyim-dcache-backend 'pyim-dhashcache
  "词库后端引擎，负责缓冲词库并提供搜索词条的算法。

目前有两个选项：

1. `pyim-dhashcache'
2. `pyim-dregcache'

`pyim-dhashcache' 是 pyim 默认使用的后端，使用 hashtable 实现，搜
索词条速度很快，但消耗内存多。

`pyim-dregcache' 消耗内存少，搜索速度和词库大小成反比，当词库小于
100M 时，速度还可以，可以尝试，需要注意的是，这个后端只支持全拼和
双拼输入法，不支持型码输入法，如果使用这个后端，用户需要自己在
Emacs 配置中添加 (require \\='pyim-dregcache)."
  :type 'symbol)
```

**Comment by sherylynn** [comment]
> Please try pyim-dregcache
> 
> ```
> (defcustom pyim-dcache-backend 'pyim-dhashcache
>   "词库后端引擎，负责缓冲词库并提供搜索词条的算法。
> 
> 目前有两个选项：
> 
> 1. `pyim-dhashcache'
> 2. `pyim-dregcache'
> 
> `pyim-dhashcache' 是 pyim 默认使用的后端，使用 hashtable 实现，搜
> 索词条速度很快，但消耗内存多。
> 
> `pyim-dregcache' 消耗内存少，搜索速度和词库大小成反比，当词库小于
> 100M 时，速度还可以，可以尝试，需要注意的是，这个后端只支持全拼和
> 双拼输入法，不支持型码输入法，如果使用这个后端，用户需要自己在
> Emacs 配置中添加 (require \\='pyim-dregcache)."
>   :type 'symbol)
> ```

非常感谢成功解决了问题！
对termux版emacs和 android native emacs都有效，成功用上

**Comment by sherylynn** [comment]
> Please try pyim-dregcache
> 
> ```
> (defcustom pyim-dcache-backend 'pyim-dhashcache
>   "词库后端引擎，负责缓冲词库并提供搜索词条的算法。
> 
> 目前有两个选项：
> 
> 1. `pyim-dhashcache'
> 2. `pyim-dregcache'
> 
> `pyim-dhashcache' 是 pyim 默认使用的后端，使用 hashtable 实现，搜
> 索词条速度很快，但消耗内存多。
> 
> `pyim-dregcache' 消耗内存少，搜索速度和词库大小成反比，当词库小于
> 100M 时，速度还可以，可以尝试，需要注意的是，这个后端只支持全拼和
> 双拼输入法，不支持型码输入法，如果使用这个后端，用户需要自己在
> Emacs 配置中添加 (require \\='pyim-dregcache)."
>   :type 'symbol)
> ```

非常感谢成功解决了问题！
对termux版emacs和 android native emacs都有效，成功用上
