### ISSUE TITLE
可否输入法使用 emacs-rime，但其他功能用 pyim？

### ISSUE THREAD

**Issue by lyserenity** [tumashu/pyim#485]
我还蛮喜欢 `pyim` 和 `vertico` 和 `avy` 的结合
但在打字上我还是比较习惯用 `emacs-rime`
有没有可能 `default-input-method` 还是用 `rime`
但和其他 package 上的应用是用 pyim 呢？

谢谢！

**Comment by tumashu** [comment]
应该可以吧，我没试过，你可以试试，有问题在沟通。

**Comment by lyserenity** [comment]
我从昨天到现在只有改 ``(setq default-input-method "rime")``
暂时没有问题
万一有问题我再来问，感谢

**Comment by lyserenity** [comment]
[让 vertico, selectrum 等补全框架，通过 orderless 支持拼音搜索候选项功能](https://github.com/tumashu/pyim?tab=readme-ov-file#%E8%AE%A9-vertico-selectrum-%E7%AD%89%E8%A1%A5%E5%85%A8%E6%A1%86%E6%9E%B6%E9%80%9A%E8%BF%87-orderless-%E6%94%AF%E6%8C%81%E6%8B%BC%E9%9F%B3%E6%90%9C%E7%B4%A2%E5%80%99%E9%80%89%E9%A1%B9%E5%8A%9F%E8%83%BD)

我最近在使用这个功能的时候，希望可以同时支援简繁，但目前似乎只能搜到简体，有没有办法同时支援呢？我应该改什么地方？

谢谢～

**Comment by tumashu** [comment]
有办法，不过可能复杂一点
1. 给 pyim-pymap 中添加繁体字
2. 运行 (pyim-pymap-cache-create t)

**Comment by lyserenity** [comment]
我去看了，真的挺复杂的

我看了下说明，pyim-pymap 用 ``|`` 分开为一、二、三级常用单字，那如果我把繁体混在里面，应该怎么排序好？
或者，如果我只是用做搜索，摆在哪一级会有差别吗？

我怕放错地方会有其他问题出现，所以想先听听大佬的建议，谢谢～

**Comment by tumashu** [comment]
主要看字常不常用，因为 emacs regexp 长度有限制，所以我们生成的中文搜索 regexp 可能会太长而无法搜索，这种情况下，pyim将抛弃最不常用的一组汉字重新生成 regexp，这个过程是递归的。

**Comment by lyserenity** [comment]
抱歉，我对 lisp 不熟（还是编程小白）

想请问一下，如果我将常用繁体加到最前方自成一级，最终成为 5 级是允许的吗？
以 ``a`` 为例，原本为 ``("a" "阿啊呵腌|嗄吖锕||錒")``，变成 ``("a" "ㄚ|阿啊呵腌|嗄吖锕||錒")``的形式可以吗？
还是我最好是把 ㄚ 并到第一级（``("a" "ㄚ阿啊呵腌|嗄吖锕||錒")``）比较好呢？

**Comment by lyserenity** [comment]
我改好了，感谢大佬～
